BasicUDPSink Class Reference
#include <BasicUDPSink.hh>
Public Types
typedef void(afterPlayingFunc) (void *clientData)
Public Member Functions
Boolean startPlaying (MediaSource &source, afterPlayingFunc *afterFunc, void *afterClientData)
virtual void stopPlaying ()
virtual Boolean isRTPSink () const
FramedSource * source () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static BasicUDPSink * createNew (UsageEnvironment &env, Groupsock *gs, unsigned maxPayloadSize=1450)
static Boolean lookupByName (UsageEnvironment &env, char const *sinkName, MediaSink *&resultSink)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
BasicUDPSink (UsageEnvironment &env, Groupsock *gs, unsigned maxPayloadSize)
virtual ~BasicUDPSink ()
virtual Boolean sourceIsCompatibleWithUs (MediaSource &source)
void onSourceClosure ()
TaskToken & nextTask ()
Static Protected Member Functions
static void onSourceClosure (void *clientData)
Protected Attributes
FramedSource * fSource
Private Member Functions
virtual Boolean continuePlaying ()
void continuePlaying1 ()
void afterGettingFrame1 (unsigned frameSize, unsigned numTruncatedBytes, unsigned durationInMicroseconds)
Static Private Member Functions
static void afterGettingFrame (void *clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds)
static void sendNext (void *firstArg)
Private Attributes
Groupsock * fGS
unsigned fMaxPayloadSize
unsigned char * fOutputBuffer
struct timeval fNextSendTime
Detailed Description
Definition at line 31 of file BasicUDPSink.hh.
Member Typedef Documentation
typedef void(MediaSink::afterPlayingFunc) (void *clientData) [inherited]
Definition at line 33 of file MediaSink.hh.
Constructor & Destructor Documentation
BasicUDPSink::BasicUDPSink (UsageEnvironment & env, Groupsock * gs, unsigned maxPayloadSize) [protected]
virtual BasicUDPSink::~BasicUDPSink () [protected], [virtual]
Member Function Documentation
static void BasicUDPSink::afterGettingFrame (void * clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds) [static], [private]
void BasicUDPSink::afterGettingFrame1 (unsigned frameSize, unsigned numTruncatedBytes, unsigned durationInMicroseconds) [private]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
virtual Boolean BasicUDPSink::continuePlaying () [private], [virtual]
Implements MediaSink .
void BasicUDPSink::continuePlaying1 () [private]
static BasicUDPSink* BasicUDPSink::createNew (UsageEnvironment & env, Groupsock * gs, unsigned maxPayloadSize = 1450) [static]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean MediaSink::isRTPSink () const [virtual], [inherited]
Reimplemented in RTPSink .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean MediaSink::lookupByName (UsageEnvironment & env, char const * sinkName, MediaSink *& resultSink) [static], [inherited]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
static void MediaSink::onSourceClosure (void * clientData) [static], [protected], [inherited]
void MediaSink::onSourceClosure () [protected], [inherited]
static void BasicUDPSink::sendNext (void * firstArg) [static], [private]
FramedSource* MediaSink::source () const [inline], [inherited]
Definition at line 42 of file MediaSink.hh.
References MediaSink::fSource.
{return fSource;}
virtual Boolean MediaSink::sourceIsCompatibleWithUs (MediaSource & source) [protected], [virtual], [inherited]
Reimplemented in H265VideoRTPSink , H264VideoRTPSink , AMRAudioRTPSink , MPEG4ESVideoRTPSink , DVVideoRTPSink , AMRAudioFileSink , JPEGVideoRTPSink , and MPEG1or2VideoRTPSink .
Boolean MediaSink::startPlaying (MediaSource & source, afterPlayingFunc * afterFunc, void * afterClientData) [inherited]
virtual void MediaSink::stopPlaying () [virtual], [inherited]
Reimplemented in MultiFramedRTPSink .
Field Documentation
Groupsock* BasicUDPSink::fGS [private]
Definition at line 56 of file BasicUDPSink.hh.
unsigned BasicUDPSink::fMaxPayloadSize [private]
Definition at line 57 of file BasicUDPSink.hh.
struct timeval BasicUDPSink::fNextSendTime [private]
Definition at line 59 of file BasicUDPSink.hh.
unsigned char* BasicUDPSink::fOutputBuffer [private]
Definition at line 58 of file BasicUDPSink.hh.
FramedSource* MediaSink::fSource [protected], [inherited]
Definition at line 58 of file MediaSink.hh.
Referenced by MediaSink::source().
The documentation for this class was generated from the following file:
liveMedia/include/BasicUDPSink.hh