PresentationTimeSessionNormalizer Class Reference
#include <ProxyServerMediaSession.hh>
Public Member Functions
PresentationTimeSessionNormalizer (UsageEnvironment &env)
virtual ~PresentationTimeSessionNormalizer ()
PresentationTimeSubsessionNormalizer * createNewPresentationTimeSubsessionNormalizer (FramedSource *inputSource, RTPSource *rtpSource, char const *codecName)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TaskToken & nextTask ()
Private Member Functions
void normalizePresentationTime (PresentationTimeSubsessionNormalizer *ssNormalizer, struct timeval &toPT, struct timeval const &fromPT)
void removePresentationTimeSubsessionNormalizer (PresentationTimeSubsessionNormalizer *ssNormalizer)
Private Attributes
PresentationTimeSubsessionNormalizer * fSubsessionNormalizers
PresentationTimeSubsessionNormalizer * fMasterSSNormalizer
struct timeval fPTAdjustment
Friends
class PresentationTimeSubsessionNormalizer
Detailed Description
Definition at line 216 of file ProxyServerMediaSession.hh.
Constructor & Destructor Documentation
PresentationTimeSessionNormalizer::PresentationTimeSessionNormalizer (UsageEnvironment & env)
virtual PresentationTimeSessionNormalizer::~PresentationTimeSessionNormalizer () [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
PresentationTimeSubsessionNormalizer* PresentationTimeSessionNormalizer::createNewPresentationTimeSubsessionNormalizer (FramedSource * inputSource, RTPSource * rtpSource, char const * codecName)
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
void PresentationTimeSessionNormalizer::normalizePresentationTime (PresentationTimeSubsessionNormalizer * ssNormalizer, struct timeval & toPT, struct timeval const & fromPT) [private]
void PresentationTimeSessionNormalizer::removePresentationTimeSubsessionNormalizer (PresentationTimeSubsessionNormalizer * ssNormalizer) [private]
Friends And Related Function Documentation
friend class PresentationTimeSubsessionNormalizer [friend]
Definition at line 225 of file ProxyServerMediaSession.hh.
Field Documentation
PresentationTimeSubsessionNormalizer* PresentationTimeSessionNormalizer::fMasterSSNormalizer [private]
Definition at line 232 of file ProxyServerMediaSession.hh.
struct timeval PresentationTimeSessionNormalizer::fPTAdjustment [private]
Definition at line 234 of file ProxyServerMediaSession.hh.
PresentationTimeSubsessionNormalizer* PresentationTimeSessionNormalizer::fSubsessionNormalizers [private]
Definition at line 231 of file ProxyServerMediaSession.hh.
The documentation for this class was generated from the following file:
liveMedia/include/ProxyServerMediaSession.hh