MediaSource Class Reference
#include <MediaSource.hh>
Public Member Functions
virtual void getAttributes () const
virtual char const * MIMEtype () const
virtual Boolean isFramedSource () const
virtual Boolean isRTPSource () const
virtual Boolean isMPEG1or2VideoStreamFramer () const
virtual Boolean isMPEG4VideoStreamFramer () const
virtual Boolean isH264VideoStreamFramer () const
virtual Boolean isH265VideoStreamFramer () const
virtual Boolean isDVVideoStreamFramer () const
virtual Boolean isJPEGVideoSource () const
virtual Boolean isAMRAudioSource () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *sourceName, MediaSource *&resultSource)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
MediaSource (UsageEnvironment &env)
virtual ~MediaSource ()
TaskToken & nextTask ()
Private Member Functions
virtual Boolean isSource () const
Detailed Description
Definition at line 28 of file MediaSource.hh.
Constructor & Destructor Documentation
MediaSource::MediaSource (UsageEnvironment & env) [protected]
virtual MediaSource::~MediaSource () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual void MediaSource::getAttributes () const [virtual]
Reimplemented in RTPSource , MP3FileSource , FramedFilter , and MP3ADUTranscoder .
virtual Boolean MediaSource::isAMRAudioSource () const [virtual]
Reimplemented in AMRAudioSource .
virtual Boolean MediaSource::isDVVideoStreamFramer () const [virtual]
Reimplemented in DVVideoStreamFramer .
virtual Boolean MediaSource::isFramedSource () const [virtual]
Reimplemented in FramedSource .
virtual Boolean MediaSource::isH264VideoStreamFramer () const [virtual]
Reimplemented in H264VideoStreamDiscreteFramer , and H264VideoStreamFramer .
virtual Boolean MediaSource::isH265VideoStreamFramer () const [virtual]
Reimplemented in H265VideoStreamDiscreteFramer , and H265VideoStreamFramer .
virtual Boolean MediaSource::isJPEGVideoSource () const [virtual]
Reimplemented in JPEGVideoSource .
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean MediaSource::isMPEG1or2VideoStreamFramer () const [virtual]
Reimplemented in MPEG1or2VideoStreamFramer .
virtual Boolean MediaSource::isMPEG4VideoStreamFramer () const [virtual]
Reimplemented in MPEG4VideoStreamFramer .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean MediaSource::isRTPSource () const [virtual]
Reimplemented in RTPSource .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean MediaSource::isSource () const [private], [virtual]
Reimplemented from Medium .
static Boolean MediaSource::lookupByName (UsageEnvironment & env, char const * sourceName, MediaSource *& resultSource) [static]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
virtual char const* MediaSource::MIMEtype () const [virtual]
Reimplemented in MP3FromADUSource , QuickTimeGenericRTPSource , MPEG4GenericRTPSource , SimpleRTPSource , H263plusVideoRTPSource , JPEGVideoRTPSource , MP3FileSource , H265VideoRTPSource , MPEG4LATMAudioRTPSource , ADUFromMP3Source , H261VideoRTPSource , MPEG1or2VideoRTPSource , VorbisAudioRTPSource , AC3AudioRTPSource , DVVideoRTPSource , MPEG1or2AudioRTPSource , MPEG4ESVideoRTPSource , H264VideoRTPSource , TheoraVideoRTPSource , VP8VideoRTPSource , VP9VideoRTPSource , MP3ADURTPSource , MPEG1or2DemuxedElementaryStream , FramedFilter , AMRAudioSource , MatroskaDemuxedTrack , and OggDemuxedTrack .
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
The documentation for this class was generated from the following file:
liveMedia/include/MediaSource.hh