ProxyRTSPClient Class Reference
#include <ProxyServerMediaSession.hh>
Public Types
typedef void(responseHandler) (RTSPClient *rtspClient, int resultCode, char *resultString)
Public Member Functions
ProxyRTSPClient (class ProxyServerMediaSession &ourServerMediaSession, char const *rtspURL, char const *username, char const *password, portNumBits tunnelOverHTTPPortNum, int verbosityLevel, int socketNumToServer)
virtual ~ProxyRTSPClient ()
void continueAfterDESCRIBE (char const *sdpDescription)
void continueAfterLivenessCommand (int resultCode, Boolean serverSupportsGetParameter)
void continueAfterSETUP (int resultCode)
void continueAfterPLAY (int resultCode)
void scheduleReset ()
unsigned sendDescribeCommand (responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendOptionsCommand (responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendAnnounceCommand (char const *sdpDescription, responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendSetupCommand (MediaSubsession &subsession, responseHandler *responseHandler, Boolean streamOutgoing=False, Boolean streamUsingTCP=False, Boolean forceMulticastOnUnspecified=False, Authenticator *authenticator=NULL)
unsigned sendPlayCommand (MediaSession &session, responseHandler *responseHandler, double start=0.0f, double end=-1.0f, float scale=1.0f, Authenticator *authenticator=NULL)
unsigned sendPlayCommand (MediaSubsession &subsession, responseHandler *responseHandler, double start=0.0f, double end=-1.0f, float scale=1.0f, Authenticator *authenticator=NULL)
unsigned sendPlayCommand (MediaSession &session, responseHandler *responseHandler, char const *absStartTime, char const *absEndTime=NULL, float scale=1.0f, Authenticator *authenticator=NULL)
unsigned sendPlayCommand (MediaSubsession &subsession, responseHandler *responseHandler, char const *absStartTime, char const *absEndTime=NULL, float scale=1.0f, Authenticator *authenticator=NULL)
unsigned sendPauseCommand (MediaSession &session, responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendPauseCommand (MediaSubsession &subsession, responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendRecordCommand (MediaSession &session, responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendRecordCommand (MediaSubsession &subsession, responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendTeardownCommand (MediaSession &session, responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendTeardownCommand (MediaSubsession &subsession, responseHandler *responseHandler, Authenticator *authenticator=NULL)
unsigned sendSetParameterCommand (MediaSession &session, responseHandler *responseHandler, char const *parameterName, char const *parameterValue, Authenticator *authenticator=NULL)
unsigned sendGetParameterCommand (MediaSession &session, responseHandler *responseHandler, char const *parameterName, Authenticator *authenticator=NULL)
void sendDummyUDPPackets (MediaSession &session, unsigned numDummyPackets=2)
void sendDummyUDPPackets (MediaSubsession &subsession, unsigned numDummyPackets=2)
void setSpeed (MediaSession &session, float speed=1.0f)
Boolean changeResponseHandler (unsigned cseq, responseHandler *newResponseHandler)
int socketNum () const
void setUserAgentString (char const *userAgentName)
void disallowBasicAuthentication ()
unsigned sessionTimeoutParameter () const
char const * url () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static RTSPClient * createNew (UsageEnvironment &env, char const *rtspURL, int verbosityLevel=0, char const *applicationName=NULL, portNumBits tunnelOverHTTPPortNum=0, int socketNumToServer=-1)
static Boolean lookupByName (UsageEnvironment &env, char const *sourceName, RTSPClient *&resultClient)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static Boolean parseRTSPURL (UsageEnvironment &env, char const *url, char *&username, char *&password, NetAddress &address, portNumBits &portNum, char const **urlSuffix=NULL)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Data Fields
u_int16_t desiredMaxIncomingPacketSize
Static Public Attributes
static unsigned responseBufferSize
Protected Member Functions
void setBaseURL (char const *url)
int grabSocket ()
virtual unsigned sendRequest (RequestRecord *request)
virtual Boolean setRequestFields (RequestRecord *request, char *&cmdURL, Boolean &cmdURLWasAllocated, char const *&protocolStr, char *&extraHeaders, Boolean &extraHeadersWereAllocated)
TaskToken & nextTask ()
Protected Attributes
int fVerbosityLevel
unsigned fCSeq
Authenticator fCurrentAuthenticator
Boolean fAllowBasicAuthentication
netAddressBits fServerAddress
Private Member Functions
void reset ()
int connectToServer (int socketNum, portNumBits remotePortNum)
Authenticator * auth ()
void scheduleLivenessCommand ()
void doReset ()
void scheduleDESCRIBECommand ()
void handleSubsessionTimeout ()
Static Private Member Functions
static void sendLivenessCommand (void *clientData)
static void doReset (void *clientData)
static void sendDESCRIBE (void *clientData)
static void subsessionTimeout (void *clientData)
Private Attributes
ProxyServerMediaSession & fOurServerMediaSession
char * fOurURL
Authenticator * fOurAuthenticator
Boolean fStreamRTPOverTCP
class ProxyServerMediaSubsession * fSetupQueueHead
class ProxyServerMediaSubsession * fSetupQueueTail
unsigned fNumSetupsDone
unsigned fNextDESCRIBEDelay
Boolean fServerSupportsGetParameter
Boolean fLastCommandWasPLAY
Boolean fDoneDESCRIBE
TaskToken fLivenessCommandTask
TaskToken fDESCRIBECommandTask
TaskToken fSubsessionTimerTask
TaskToken fResetTask
Friends
class ProxyServerMediaSession
class ProxyServerMediaSubsession
Detailed Description
Definition at line 42 of file ProxyServerMediaSession.hh.
Member Typedef Documentation
typedef void(RTSPClient::responseHandler) (RTSPClient *rtspClient, int resultCode, char *resultString) [inherited]
Definition at line 52 of file RTSPClient.hh.
Constructor & Destructor Documentation
ProxyRTSPClient::ProxyRTSPClient (class ProxyServerMediaSession & ourServerMediaSession, char const * rtspURL, char const * username, char const * password, portNumBits tunnelOverHTTPPortNum, int verbosityLevel, int socketNumToServer)
virtual ProxyRTSPClient::~ProxyRTSPClient () [virtual]
Member Function Documentation
Authenticator* ProxyRTSPClient::auth () [inline], [private]
Definition at line 59 of file ProxyServerMediaSession.hh.
References fOurAuthenticator.
{ return fOurAuthenticator; }
Boolean RTSPClient::changeResponseHandler (unsigned cseq, responseHandler * newResponseHandler) [inherited]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
int ProxyRTSPClient::connectToServer (int socketNum, portNumBits remotePortNum) [private], [virtual]
Reimplemented from RTSPClient .
void ProxyRTSPClient::continueAfterDESCRIBE (char const * sdpDescription)
void ProxyRTSPClient::continueAfterLivenessCommand (int resultCode, Boolean serverSupportsGetParameter)
void ProxyRTSPClient::continueAfterPLAY (int resultCode)
void ProxyRTSPClient::continueAfterSETUP (int resultCode)
static RTSPClient* RTSPClient::createNew (UsageEnvironment & env, char const * rtspURL, int verbosityLevel = 0, char const * applicationName = NULL, portNumBits tunnelOverHTTPPortNum = 0, int socketNumToServer = -1) [static], [inherited]
void RTSPClient::disallowBasicAuthentication () [inline], [inherited]
Definition at line 182 of file RTSPClient.hh.
References RTSPClient::fAllowBasicAuthentication, and False.
{ fAllowBasicAuthentication = False; }
void ProxyRTSPClient::doReset () [private]
static void ProxyRTSPClient::doReset (void * clientData) [static], [private]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
int RTSPClient::grabSocket () [protected], [inherited]
void ProxyRTSPClient::handleSubsessionTimeout () [private]
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
static Boolean RTSPClient::lookupByName (UsageEnvironment & env, char const * sourceName, RTSPClient *& resultClient) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
static Boolean RTSPClient::parseRTSPURL (UsageEnvironment & env, char const * url, char *& username, char *& password, NetAddress & address, portNumBits & portNum, char const ** urlSuffix = NULL) [static], [inherited]
void ProxyRTSPClient::reset () [private]
void ProxyRTSPClient::scheduleDESCRIBECommand () [private]
void ProxyRTSPClient::scheduleLivenessCommand () [private]
void ProxyRTSPClient::scheduleReset ()
unsigned RTSPClient::sendAnnounceCommand (char const * sdpDescription, responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
static void ProxyRTSPClient::sendDESCRIBE (void * clientData) [static], [private]
unsigned RTSPClient::sendDescribeCommand (responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
void RTSPClient::sendDummyUDPPackets (MediaSession & session, unsigned numDummyPackets = 2) [inherited]
void RTSPClient::sendDummyUDPPackets (MediaSubsession & subsession, unsigned numDummyPackets = 2) [inherited]
unsigned RTSPClient::sendGetParameterCommand (MediaSession & session, responseHandler * responseHandler, char const * parameterName, Authenticator * authenticator = NULL) [inherited]
static void ProxyRTSPClient::sendLivenessCommand (void * clientData) [static], [private]
unsigned RTSPClient::sendOptionsCommand (responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendPauseCommand (MediaSession & session, responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendPauseCommand (MediaSubsession & subsession, responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendPlayCommand (MediaSession & session, responseHandler * responseHandler, double start = 0.0f, double end = -1.0f, float scale = 1.0f, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendPlayCommand (MediaSubsession & subsession, responseHandler * responseHandler, double start = 0.0f, double end = -1.0f, float scale = 1.0f, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendPlayCommand (MediaSession & session, responseHandler * responseHandler, char const * absStartTime, char const * absEndTime = NULL, float scale = 1.0f, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendPlayCommand (MediaSubsession & subsession, responseHandler * responseHandler, char const * absStartTime, char const * absEndTime = NULL, float scale = 1.0f, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendRecordCommand (MediaSession & session, responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendRecordCommand (MediaSubsession & subsession, responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
virtual unsigned RTSPClient::sendRequest (RequestRecord * request) [protected], [virtual], [inherited]
unsigned RTSPClient::sendSetParameterCommand (MediaSession & session, responseHandler * responseHandler, char const * parameterName, char const * parameterValue, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendSetupCommand (MediaSubsession & subsession, responseHandler * responseHandler, Boolean streamOutgoing = False, Boolean streamUsingTCP = False, Boolean forceMulticastOnUnspecified = False, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendTeardownCommand (MediaSession & session, responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sendTeardownCommand (MediaSubsession & subsession, responseHandler * responseHandler, Authenticator * authenticator = NULL) [inherited]
unsigned RTSPClient::sessionTimeoutParameter () const [inline], [inherited]
Definition at line 186 of file RTSPClient.hh.
References RTSPClient::fSessionTimeoutParameter.
{ return fSessionTimeoutParameter; }
void RTSPClient::setBaseURL (char const * url) [protected], [inherited]
virtual Boolean RTSPClient::setRequestFields (RequestRecord * request, char *& cmdURL, Boolean & cmdURLWasAllocated, char const *& protocolStr, char *& extraHeaders, Boolean & extraHeadersWereAllocated) [protected], [virtual], [inherited]
Reimplemented in RTSPDeregisterSender , and RTSPRegisterSender .
void RTSPClient::setSpeed (MediaSession & session, float speed = 1.0f) [inherited]
void RTSPClient::setUserAgentString (char const * userAgentName) [inherited]
int RTSPClient::socketNum () const [inline], [inherited]
Definition at line 168 of file RTSPClient.hh.
References RTSPClient::fInputSocketNum.
{ return fInputSocketNum; }
static void ProxyRTSPClient::subsessionTimeout (void * clientData) [static], [private]
char const* RTSPClient::url () const [inline], [inherited]
Definition at line 188 of file RTSPClient.hh.
References RTSPClient::fBaseURL.
{ return fBaseURL; }
Friends And Related Function Documentation
friend class ProxyServerMediaSession [friend]
Definition at line 73 of file ProxyServerMediaSession.hh.
friend class ProxyServerMediaSubsession [friend]
Definition at line 74 of file ProxyServerMediaSession.hh.
Field Documentation
u_int16_t RTSPClient::desiredMaxIncomingPacketSize [inherited]
Definition at line 320 of file RTSPClient.hh.
Boolean RTSPClient::fAllowBasicAuthentication [protected], [inherited]
Definition at line 328 of file RTSPClient.hh.
Referenced by RTSPClient::disallowBasicAuthentication().
unsigned RTSPClient::fCSeq [protected], [inherited]
Definition at line 326 of file RTSPClient.hh.
Authenticator RTSPClient::fCurrentAuthenticator [protected], [inherited]
Definition at line 327 of file RTSPClient.hh.
TaskToken ProxyRTSPClient::fDESCRIBECommandTask [private]
Definition at line 83 of file ProxyServerMediaSession.hh.
Boolean ProxyRTSPClient::fDoneDESCRIBE [private]
Definition at line 82 of file ProxyServerMediaSession.hh.
Boolean ProxyRTSPClient::fLastCommandWasPLAY [private]
Definition at line 82 of file ProxyServerMediaSession.hh.
TaskToken ProxyRTSPClient::fLivenessCommandTask [private]
Definition at line 83 of file ProxyServerMediaSession.hh.
unsigned ProxyRTSPClient::fNextDESCRIBEDelay [private]
Definition at line 81 of file ProxyServerMediaSession.hh.
unsigned ProxyRTSPClient::fNumSetupsDone [private]
Definition at line 80 of file ProxyServerMediaSession.hh.
Authenticator* ProxyRTSPClient::fOurAuthenticator [private]
Definition at line 77 of file ProxyServerMediaSession.hh.
Referenced by auth().
ProxyServerMediaSession& ProxyRTSPClient::fOurServerMediaSession [private]
Definition at line 75 of file ProxyServerMediaSession.hh.
char* ProxyRTSPClient::fOurURL [private]
Definition at line 76 of file ProxyServerMediaSession.hh.
TaskToken ProxyRTSPClient::fResetTask [private]
Definition at line 83 of file ProxyServerMediaSession.hh.
netAddressBits RTSPClient::fServerAddress [protected], [inherited]
Definition at line 329 of file RTSPClient.hh.
Boolean ProxyRTSPClient::fServerSupportsGetParameter [private]
Definition at line 82 of file ProxyServerMediaSession.hh.
class ProxyServerMediaSubsession* ProxyRTSPClient::fSetupQueueHead [private]
Definition at line 79 of file ProxyServerMediaSession.hh.
class ProxyServerMediaSubsession * ProxyRTSPClient::fSetupQueueTail [private]
Definition at line 79 of file ProxyServerMediaSession.hh.
Boolean ProxyRTSPClient::fStreamRTPOverTCP [private]
Definition at line 78 of file ProxyServerMediaSession.hh.
TaskToken ProxyRTSPClient::fSubsessionTimerTask [private]
Definition at line 83 of file ProxyServerMediaSession.hh.
int RTSPClient::fVerbosityLevel [protected], [inherited]
Definition at line 325 of file RTSPClient.hh.
unsigned RTSPClient::responseBufferSize [static], [inherited]
Definition at line 190 of file RTSPClient.hh.
The documentation for this class was generated from the following file:
liveMedia/include/ProxyServerMediaSession.hh