OutputSocket Class Reference
#include <Groupsock.hh>
Public Member Functions
OutputSocket (UsageEnvironment &env)
virtual ~OutputSocket ()
virtual Boolean write (netAddressBits address, portNumBits portNum, u_int8_t ttl, unsigned char *buffer, unsigned bufferSize)
Boolean write (struct sockaddr_in &addressAndPort, u_int8_t ttl, unsigned char *buffer, unsigned bufferSize)
void reset ()
int socketNum () const
Port port () const
UsageEnvironment & env () const
Static Public Attributes
static int DebugLevel
static UsageEnvironment * DefaultUsageEnvironment
Protected Member Functions
OutputSocket (UsageEnvironment &env, Port port)
portNumBits sourcePortNum () const
Boolean changePort (Port newPort)
Private Member Functions
virtual Boolean handleRead (unsigned char *buffer, unsigned bufferMaxSize, unsigned &bytesRead, struct sockaddr_in &fromAddressAndPort)
Private Attributes
Port fSourcePort
unsigned fLastSentTTL
Detailed Description
Definition at line 39 of file Groupsock.hh.
Constructor & Destructor Documentation
OutputSocket::OutputSocket (UsageEnvironment & env)
virtual OutputSocket::~OutputSocket () [virtual]
OutputSocket::OutputSocket (UsageEnvironment & env, Port port) [protected]
Member Function Documentation
Boolean Socket::changePort (Port newPort) [protected], [inherited]
UsageEnvironment& Socket::env () const [inline], [inherited]
Definition at line 96 of file NetInterface.hh.
References Socket::fEnv.
{ return fEnv; }
virtual Boolean OutputSocket::handleRead (unsigned char * buffer, unsigned bufferMaxSize, unsigned & bytesRead, struct sockaddr_in & fromAddressAndPort) [private], [virtual]
Implements Socket .
Reimplemented in Groupsock .
Port Socket::port () const [inline], [inherited]
Definition at line 92 of file NetInterface.hh.
References Socket::fPort.
                    {
    return fPort;
  }
void Socket::reset () [inherited]
int Socket::socketNum () const [inline], [inherited]
Definition at line 90 of file NetInterface.hh.
References Socket::fSocketNum.
{ return fSocketNum; }
portNumBits OutputSocket::sourcePortNum () const [inline], [protected]
Definition at line 54 of file Groupsock.hh.
References fSourcePort, and Port::num().
{return fSourcePort.num();}
virtual Boolean OutputSocket::write (netAddressBits address, portNumBits portNum, u_int8_t ttl, unsigned char * buffer, unsigned bufferSize) [virtual]
Referenced by write().
Boolean OutputSocket::write (struct sockaddr_in & addressAndPort, u_int8_t ttl, unsigned char * buffer, unsigned bufferSize) [inline]
Definition at line 46 of file Groupsock.hh.
References write().
                                                            {
    return write(addressAndPort.sin_addr.s_addr, addressAndPort.sin_port, ttl, buffer, bufferSize);
  }
Field Documentation
int Socket::DebugLevel [static], [inherited]
Definition at line 98 of file NetInterface.hh.
UsageEnvironment* NetInterface::DefaultUsageEnvironment [static], [inherited]
Definition at line 32 of file NetInterface.hh.
unsigned OutputSocket::fLastSentTTL [private]
Definition at line 63 of file Groupsock.hh.
Port OutputSocket::fSourcePort [private]
Definition at line 62 of file Groupsock.hh.
Referenced by sourcePortNum().
The documentation for this class was generated from the following file:
groupsock/include/Groupsock.hh