Medium Class Reference
#include <Media.hh>
Public Member Functions
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
Medium (UsageEnvironment &env)
virtual ~Medium ()
TaskToken & nextTask ()
Private Attributes
UsageEnvironment & fEnviron
char fMediumName [mediumNameMaxLen]
TaskToken fNextTask
Friends
class MediaLookupTable
Detailed Description
Definition at line 50 of file Media.hh.
Constructor & Destructor Documentation
Medium::Medium (UsageEnvironment & env) [protected]
virtual Medium::~Medium () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static]
static void Medium::close (Medium * medium) [static]
UsageEnvironment& Medium::envir () const [inline]
Definition at line 59 of file Media.hh.
References fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual Boolean Medium::isMediaSession () const [virtual]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static]
char const* Medium::name () const [inline]
Definition at line 61 of file Media.hh.
References fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected]
Definition at line 77 of file Media.hh.
References fNextTask.
                        {
        return fNextTask;
  }
Friends And Related Function Documentation
friend class MediaLookupTable [friend]
Definition at line 73 of file Media.hh.
Field Documentation
UsageEnvironment& Medium::fEnviron [private]
Definition at line 82 of file Media.hh.
Referenced by envir().
char Medium::fMediumName[mediumNameMaxLen] [private]
Definition at line 83 of file Media.hh.
Referenced by name().
TaskToken Medium::fNextTask [private]
Definition at line 84 of file Media.hh.
Referenced by nextTask().
The documentation for this class was generated from the following file:
liveMedia/include/Media.hh