OggDemux Class Reference
#include <OggFile.hh>
Public Member Functions
FramedSource * newDemuxedTrack (u_int32_t &resultTrackNumber)
FramedSource * newDemuxedTrackByTrackNumber (unsigned trackNumber)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
class OggDemuxedTrack * lookupDemuxedTrack (u_int32_t trackNumber)
OggDemux (OggFile &ourFile)
virtual ~OggDemux ()
TaskToken & nextTask ()
Private Member Functions
void removeTrack (u_int32_t trackNumber)
void continueReading ()
void handleEndOfFile ()
Static Private Member Functions
static void handleEndOfFile (void *clientData)
Private Attributes
OggFile & fOurFile
class OggFileParser * fOurParser
HashTable * fDemuxedTracksTable
OggTrackTableIterator * fIter
Friends
class OggFile
class OggFileParser
class OggDemuxedTrack
Detailed Description
Definition at line 140 of file OggFile.hh.
Constructor & Destructor Documentation
OggDemux::OggDemux (OggFile & ourFile) [protected]
virtual OggDemux::~OggDemux () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
void OggDemux::continueReading () [private]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
static void OggDemux::handleEndOfFile (void * clientData) [static], [private]
void OggDemux::handleEndOfFile () [private]
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
class OggDemuxedTrack* OggDemux::lookupDemuxedTrack (u_int32_t trackNumber) [protected]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
FramedSource* OggDemux::newDemuxedTrack (u_int32_t & resultTrackNumber)
FramedSource* OggDemux::newDemuxedTrackByTrackNumber (unsigned trackNumber)
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
void OggDemux::removeTrack (u_int32_t trackNumber) [private]
Friends And Related Function Documentation
friend class OggDemuxedTrack [friend]
Definition at line 163 of file OggFile.hh.
friend class OggFile [friend]
Definition at line 155 of file OggFile.hh.
friend class OggFileParser [friend]
Definition at line 156 of file OggFile.hh.
Field Documentation
HashTable* OggDemux::fDemuxedTracksTable [private]
Definition at line 173 of file OggFile.hh.
OggTrackTableIterator* OggDemux::fIter [private]
Definition at line 174 of file OggFile.hh.
OggFile& OggDemux::fOurFile [private]
Definition at line 171 of file OggFile.hh.
class OggFileParser* OggDemux::fOurParser [private]
Definition at line 172 of file OggFile.hh.
The documentation for this class was generated from the following file:
liveMedia/include/OggFile.hh