BasicHashTable Class Reference
#include <BasicHashTable.hh>
Data Structures
class Iterator
class TableEntry
Public Member Functions
BasicHashTable (int keyType)
virtual ~BasicHashTable ()
Boolean IsEmpty () const
void * RemoveNext ()
void * getFirst ()
Static Public Member Functions
static HashTable * create (int keyType)
Private Member Functions
virtual void * Add (char const *key, void *value)
virtual Boolean Remove (char const *key)
virtual void * Lookup (char const *key) const
virtual unsigned numEntries () const
TableEntry * lookupKey (char const *key, unsigned &index) const
Boolean keyMatches (char const *key1, char const *key2) const
TableEntry * insertNewEntry (unsigned index, char const *key)
void assignKey (TableEntry *entry, char const *key)
void deleteEntry (unsigned index, TableEntry *entry)
void deleteKey (TableEntry *entry)
void rebuild ()
unsigned hashIndexFromKey (char const *key) const
unsigned randomIndex (uintptr_t i) const
Private Attributes
TableEntry ** fBuckets
TableEntry * fStaticBuckets [SMALL_HASH_TABLE_SIZE]
unsigned fNumBuckets
unsigned fNumEntries
unsigned fRebuildSize
unsigned fDownShift
unsigned fMask
int fKeyType
Friends
class Iterator
Detailed Description
Definition at line 35 of file BasicHashTable.hh.
Constructor & Destructor Documentation
BasicHashTable::BasicHashTable (int keyType)
virtual BasicHashTable::~BasicHashTable () [virtual]
Member Function Documentation
virtual void* BasicHashTable::Add (char const * key, void * value) [private], [virtual]
Implements HashTable .
void BasicHashTable::assignKey (TableEntry * entry, char const * key) [private]
static HashTable* HashTable::create (int keyType) [static], [inherited]
void BasicHashTable::deleteEntry (unsigned index, TableEntry * entry) [private]
void BasicHashTable::deleteKey (TableEntry * entry) [private]
void* HashTable::getFirst () [inherited]
unsigned BasicHashTable::hashIndexFromKey (char const * key) const [private]
TableEntry* BasicHashTable::insertNewEntry (unsigned index, char const * key) [private]
Boolean HashTable::IsEmpty () const [inline], [inherited]
Definition at line 41 of file HashTable.hh.
References HashTable::numEntries().
Referenced by DirectedNetInterfaceSet::IsEmpty().
{ return numEntries() == 0; }
Boolean BasicHashTable::keyMatches (char const * key1, char const * key2) const [private]
virtual void* BasicHashTable::Lookup (char const * key) const [private], [virtual]
Implements HashTable .
TableEntry* BasicHashTable::lookupKey (char const * key, unsigned & index) const [private]
virtual unsigned BasicHashTable::numEntries () const [private], [virtual]
Implements HashTable .
unsigned BasicHashTable::randomIndex (uintptr_t i) const [inline], [private]
Definition at line 93 of file BasicHashTable.hh.
References fDownShift, and fMask.
                                          {
    return (unsigned)(((i*1103515245) >> fDownShift) & fMask);
  }
void BasicHashTable::rebuild () [private]
virtual Boolean BasicHashTable::Remove (char const * key) [private], [virtual]
Implements HashTable .
void* HashTable::RemoveNext () [inherited]
Referenced by AddressPortLookupTable::RemoveNext().
Friends And Related Function Documentation
friend class Iterator [friend]
Definition at line 44 of file BasicHashTable.hh.
Field Documentation
TableEntry** BasicHashTable::fBuckets [private]
Definition at line 98 of file BasicHashTable.hh.
unsigned BasicHashTable::fDownShift [private]
Definition at line 100 of file BasicHashTable.hh.
Referenced by randomIndex().
int BasicHashTable::fKeyType [private]
Definition at line 101 of file BasicHashTable.hh.
unsigned BasicHashTable::fMask [private]
Definition at line 100 of file BasicHashTable.hh.
Referenced by randomIndex().
unsigned BasicHashTable::fNumBuckets [private]
Definition at line 100 of file BasicHashTable.hh.
unsigned BasicHashTable::fNumEntries [private]
Definition at line 100 of file BasicHashTable.hh.
unsigned BasicHashTable::fRebuildSize [private]
Definition at line 100 of file BasicHashTable.hh.
TableEntry* BasicHashTable::fStaticBuckets[SMALL_HASH_TABLE_SIZE] [private]
Definition at line 99 of file BasicHashTable.hh.
The documentation for this class was generated from the following file:
BasicUsageEnvironment/include/BasicHashTable.hh