MPEG1or2Demux Class Reference
#include <MPEG1or2Demux.hh>
Data Structures
struct OutputDescriptor
class SCR
Public Member Functions
MPEG1or2DemuxedElementaryStream * newElementaryStream (u_int8_t streamIdTag)
MPEG1or2DemuxedElementaryStream * newAudioStream ()
MPEG1or2DemuxedElementaryStream * newVideoStream ()
MPEG1or2DemuxedElementaryStream * newRawPESStream ()
void getNextFrame (u_int8_t streamIdTag, unsigned char *to, unsigned maxSize, FramedSource::afterGettingFunc *afterGettingFunc, void *afterGettingClientData, FramedSource::onCloseFunc *onCloseFunc, void *onCloseClientData)
void stopGettingFrames (u_int8_t streamIdTag)
FramedSource * inputSource () const
SCR & lastSeenSCR ()
unsigned char mpegVersion () const
void flushInput ()
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static MPEG1or2Demux * createNew (UsageEnvironment &env, FramedSource *inputSource, Boolean reclaimWhenLastESDies=False)
static void handleClosure (void *clientData)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TaskToken & nextTask ()
Private Types
typedef struct MPEG1or2Demux::OutputDescriptor OutputDescriptor_t
Private Member Functions
MPEG1or2Demux (UsageEnvironment &env, FramedSource *inputSource, Boolean reclaimWhenLastESDies)
virtual ~MPEG1or2Demux ()
void registerReadInterest (u_int8_t streamIdTag, unsigned char *to, unsigned maxSize, FramedSource::afterGettingFunc *afterGettingFunc, void *afterGettingClientData, FramedSource::onCloseFunc *onCloseFunc, void *onCloseClientData)
Boolean useSavedData (u_int8_t streamIdTag, unsigned char *to, unsigned maxSize, FramedSource::afterGettingFunc *afterGettingFunc, void *afterGettingClientData)
void continueReadProcessing ()
void noteElementaryStreamDeletion (MPEG1or2DemuxedElementaryStream *es)
Static Private Member Functions
static void continueReadProcessing (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime)
Private Attributes
FramedSource * fInputSource
SCR fLastSeenSCR
unsigned char fMPEGversion
unsigned char fNextAudioStreamNumber
unsigned char fNextVideoStreamNumber
Boolean fReclaimWhenLastESDies
unsigned fNumOutstandingESs
OutputDescriptor_t fOutput [256]
unsigned fNumPendingReads
Boolean fHaveUndeliveredData
class MPEGProgramStreamParser * fParser
Friends
class MPEG1or2DemuxedElementaryStream
class MPEGProgramStreamParser
Detailed Description
Definition at line 30 of file MPEG1or2Demux.hh.
Member Typedef Documentation
typedef struct MPEG1or2Demux::OutputDescriptor MPEG1or2Demux::OutputDescriptor_t [private]
Constructor & Destructor Documentation
MPEG1or2Demux::MPEG1or2Demux (UsageEnvironment & env, FramedSource * inputSource, Boolean reclaimWhenLastESDies) [private]
virtual MPEG1or2Demux::~MPEG1or2Demux () [private], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static void MPEG1or2Demux::continueReadProcessing (void * clientData, unsigned char * ptr, unsigned size, struct timeval presentationTime) [static], [private]
void MPEG1or2Demux::continueReadProcessing () [private]
static MPEG1or2Demux* MPEG1or2Demux::createNew (UsageEnvironment & env, FramedSource * inputSource, Boolean reclaimWhenLastESDies = False) [static]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
void MPEG1or2Demux::flushInput ()
void MPEG1or2Demux::getNextFrame (u_int8_t streamIdTag, unsigned char * to, unsigned maxSize, FramedSource::afterGettingFunc * afterGettingFunc, void * afterGettingClientData, FramedSource::onCloseFunc * onCloseFunc, void * onCloseClientData)
static void MPEG1or2Demux::handleClosure (void * clientData) [static]
FramedSource* MPEG1or2Demux::inputSource () const [inline]
Definition at line 64 of file MPEG1or2Demux.hh.
References fInputSource.
{ return fInputSource; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
SCR& MPEG1or2Demux::lastSeenSCR () [inline]
Definition at line 76 of file MPEG1or2Demux.hh.
References fLastSeenSCR.
{ return fLastSeenSCR; }
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
unsigned char MPEG1or2Demux::mpegVersion () const [inline]
Definition at line 78 of file MPEG1or2Demux.hh.
References fMPEGversion.
{ return fMPEGversion; }
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
MPEG1or2DemuxedElementaryStream* MPEG1or2Demux::newAudioStream ()
MPEG1or2DemuxedElementaryStream* MPEG1or2Demux::newElementaryStream (u_int8_t streamIdTag)
MPEG1or2DemuxedElementaryStream* MPEG1or2Demux::newRawPESStream ()
MPEG1or2DemuxedElementaryStream* MPEG1or2Demux::newVideoStream ()
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
void MPEG1or2Demux::noteElementaryStreamDeletion (MPEG1or2DemuxedElementaryStream * es) [private]
void MPEG1or2Demux::registerReadInterest (u_int8_t streamIdTag, unsigned char * to, unsigned maxSize, FramedSource::afterGettingFunc * afterGettingFunc, void * afterGettingClientData, FramedSource::onCloseFunc * onCloseFunc, void * onCloseClientData) [private]
void MPEG1or2Demux::stopGettingFrames (u_int8_t streamIdTag)
Boolean MPEG1or2Demux::useSavedData (u_int8_t streamIdTag, unsigned char * to, unsigned maxSize, FramedSource::afterGettingFunc * afterGettingFunc, void * afterGettingClientData) [private]
Friends And Related Function Documentation
friend class MPEG1or2DemuxedElementaryStream [friend]
Definition at line 106 of file MPEG1or2Demux.hh.
friend class MPEGProgramStreamParser [friend]
Definition at line 147 of file MPEG1or2Demux.hh.
Field Documentation
Boolean MPEG1or2Demux::fHaveUndeliveredData [private]
Definition at line 143 of file MPEG1or2Demux.hh.
FramedSource* MPEG1or2Demux::fInputSource [private]
Definition at line 110 of file MPEG1or2Demux.hh.
Referenced by inputSource().
SCR MPEG1or2Demux::fLastSeenSCR [private]
Definition at line 111 of file MPEG1or2Demux.hh.
Referenced by lastSeenSCR().
unsigned char MPEG1or2Demux::fMPEGversion [private]
Definition at line 112 of file MPEG1or2Demux.hh.
Referenced by mpegVersion().
unsigned char MPEG1or2Demux::fNextAudioStreamNumber [private]
Definition at line 114 of file MPEG1or2Demux.hh.
unsigned char MPEG1or2Demux::fNextVideoStreamNumber [private]
Definition at line 115 of file MPEG1or2Demux.hh.
unsigned MPEG1or2Demux::fNumOutstandingESs [private]
Definition at line 117 of file MPEG1or2Demux.hh.
unsigned MPEG1or2Demux::fNumPendingReads [private]
Definition at line 142 of file MPEG1or2Demux.hh.
OutputDescriptor_t MPEG1or2Demux::fOutput[256] [private]
Definition at line 140 of file MPEG1or2Demux.hh.
class MPEGProgramStreamParser* MPEG1or2Demux::fParser [private]
Definition at line 146 of file MPEG1or2Demux.hh.
Boolean MPEG1or2Demux::fReclaimWhenLastESDies [private]
Definition at line 116 of file MPEG1or2Demux.hh.
The documentation for this class was generated from the following file:
liveMedia/include/MPEG1or2Demux.hh