MatroskaDemux Class Reference
#include <MatroskaFile.hh>
Public Member Functions
FramedSource * newDemuxedTrack ()
FramedSource * newDemuxedTrack (unsigned &resultTrackNumber)
FramedSource * newDemuxedTrackByTrackNumber (unsigned trackNumber)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
class MatroskaDemuxedTrack * lookupDemuxedTrack (unsigned trackNumber)
MatroskaDemux (MatroskaFile &ourFile)
virtual ~MatroskaDemux ()
TaskToken & nextTask ()
Private Member Functions
void removeTrack (unsigned trackNumber)
void continueReading ()
void seekToTime (double &seekNPT)
void handleEndOfFile ()
Static Private Member Functions
static void handleEndOfFile (void *clientData)
Private Attributes
MatroskaFile & fOurFile
class MatroskaFileParser * fOurParser
HashTable * fDemuxedTracksTable
u_int8_t fNextTrackTypeToCheck
Friends
class MatroskaFile
class MatroskaFileParser
class MatroskaDemuxedTrack
Detailed Description
Definition at line 138 of file MatroskaFile.hh.
Constructor & Destructor Documentation
MatroskaDemux::MatroskaDemux (MatroskaFile & ourFile) [protected]
virtual MatroskaDemux::~MatroskaDemux () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
void MatroskaDemux::continueReading () [private]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
static void MatroskaDemux::handleEndOfFile (void * clientData) [static], [private]
void MatroskaDemux::handleEndOfFile () [private]
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
class MatroskaDemuxedTrack* MatroskaDemux::lookupDemuxedTrack (unsigned trackNumber) [protected]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
FramedSource* MatroskaDemux::newDemuxedTrack ()
FramedSource* MatroskaDemux::newDemuxedTrack (unsigned & resultTrackNumber)
FramedSource* MatroskaDemux::newDemuxedTrackByTrackNumber (unsigned trackNumber)
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
void MatroskaDemux::removeTrack (unsigned trackNumber) [private]
void MatroskaDemux::seekToTime (double & seekNPT) [private]
Friends And Related Function Documentation
friend class MatroskaDemuxedTrack [friend]
Definition at line 164 of file MatroskaFile.hh.
friend class MatroskaFile [friend]
Definition at line 156 of file MatroskaFile.hh.
friend class MatroskaFileParser [friend]
Definition at line 157 of file MatroskaFile.hh.
Field Documentation
HashTable* MatroskaDemux::fDemuxedTracksTable [private]
Definition at line 175 of file MatroskaFile.hh.
u_int8_t MatroskaDemux::fNextTrackTypeToCheck [private]
Definition at line 178 of file MatroskaFile.hh.
MatroskaFile& MatroskaDemux::fOurFile [private]
Definition at line 173 of file MatroskaFile.hh.
class MatroskaFileParser* MatroskaDemux::fOurParser [private]
Definition at line 174 of file MatroskaFile.hh.
The documentation for this class was generated from the following file:
liveMedia/include/MatroskaFile.hh