ProxyServerMediaSession Class Reference
#include <ProxyServerMediaSession.hh>
Public Member Functions
virtual ~ProxyServerMediaSession ()
char const * url () const
Boolean describeCompletedSuccessfully () const
char * generateSDPDescription ()
char const * streamName () const
Boolean addSubsession (ServerMediaSubsession *subsession)
unsigned numSubsessions () const
void testScaleFactor (float &scale)
float duration () const
virtual void noteLiveness ()
unsigned referenceCount () const
void incrementReferenceCount ()
void decrementReferenceCount ()
Boolean & deleteWhenUnreferenced ()
void deleteAllSubsessions ()
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
Static Public Member Functions
static ProxyServerMediaSession * createNew (UsageEnvironment &env, GenericMediaServer *ourMediaServer, char const *inputStreamURL, char const *streamName=NULL, char const *username=NULL, char const *password=NULL, portNumBits tunnelOverHTTPPortNum=0, int verbosityLevel=0, int socketNumToServer=-1, MediaTranscodingTable *transcodingTable=NULL)
static ServerMediaSession * createNew (UsageEnvironment &env, char const *streamName=NULL, char const *info=NULL, char const *description=NULL, Boolean isSSM=False, char const *miscSDPLines=NULL)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, ServerMediaSession *&resultSession)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Data Fields
char describeCompletedFlag
Protected Member Functions
ProxyServerMediaSession (UsageEnvironment &env, GenericMediaServer *ourMediaServer, char const *inputStreamURL, char const *streamName, char const *username, char const *password, portNumBits tunnelOverHTTPPortNum, int verbosityLevel, int socketNumToServer, MediaTranscodingTable *transcodingTable, createNewProxyRTSPClientFunc *ourCreateNewProxyRTSPClientFunc=defaultCreateNewProxyRTSPClientFunc, portNumBits initialPortNum=6970, Boolean multiplexRTCPWithRTP=False)
virtual Groupsock * createGroupsock (struct in_addr const &addr, Port port)
virtual RTCPInstance * createRTCP (Groupsock *RTCPgs, unsigned totSessionBW, unsigned char const *cname, RTPSink *sink)
virtual Boolean allowProxyingForSubsession (MediaSubsession const &mss)
TaskToken & nextTask ()
Protected Attributes
GenericMediaServer * fOurMediaServer
ProxyRTSPClient * fProxyRTSPClient
MediaSession * fClientMediaSession
Private Member Functions
void continueAfterDESCRIBE (char const *sdpDescription)
void resetDESCRIBEState ()
Private Attributes
int fVerbosityLevel
class PresentationTimeSessionNormalizer * fPresentationTimeSessionNormalizer
createNewProxyRTSPClientFunc * fCreateNewProxyRTSPClientFunc
MediaTranscodingTable * fTranscodingTable
portNumBits fInitialPortNum
Boolean fMultiplexRTCPWithRTP
Friends
class ProxyRTSPClient
class ProxyServerMediaSubsession
Detailed Description
Definition at line 100 of file ProxyServerMediaSession.hh.
Constructor & Destructor Documentation
virtual ProxyServerMediaSession::~ProxyServerMediaSession () [virtual]
[ProxyServerMediaSession(UsageEnvironment &env, GenericMediaServer *ourMediaServer, char const *inputStreamURL, char const *streamName, char const *username, char const *password, portNumBits tunnelOverHTTPPortNum, int verbosityLevel, int socketNumToServer, MediaTranscodingTable *transcodingTable, createNewProxyRTSPClientFunc *ourCreateNewProxyRTSPClientFunc=defaultCreateNewProxyRTSPClientFunc, portNumBits initialPortNum=6970, Boolean multiplexRTCPWithRTP=False)]ProxyServerMediaSession::ProxyServerMediaSession (UsageEnvironment & env, GenericMediaServer * ourMediaServer, char const * inputStreamURL, char const * streamName, char const * username, char const * password, portNumBits tunnelOverHTTPPortNum, int verbosityLevel, int socketNumToServer, MediaTranscodingTable * transcodingTable, createNewProxyRTSPClientFunc * ourCreateNewProxyRTSPClientFunc = defaultCreateNewProxyRTSPClientFunc, portNumBits initialPortNum = 6970, Boolean multiplexRTCPWithRTP = False) [protected]
Member Function Documentation
Boolean ServerMediaSession::addSubsession (ServerMediaSubsession * subsession) [inherited]
virtual Boolean ProxyServerMediaSession::allowProxyingForSubsession (MediaSubsession const & mss) [protected], [virtual]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
void ProxyServerMediaSession::continueAfterDESCRIBE (char const * sdpDescription) [private]
virtual Groupsock* ProxyServerMediaSession::createGroupsock (struct in_addr const & addr, Port port) [protected], [virtual]
static ServerMediaSession* ServerMediaSession::createNew (UsageEnvironment & env, char const * streamName = NULL, char const * info = NULL, char const * description = NULL, Boolean isSSM = False, char const * miscSDPLines = NULL) [static], [inherited]
static ProxyServerMediaSession* ProxyServerMediaSession::createNew (UsageEnvironment & env, GenericMediaServer * ourMediaServer, char const * inputStreamURL, char const * streamName = NULL, char const * username = NULL, char const * password = NULL, portNumBits tunnelOverHTTPPortNum = 0, int verbosityLevel = 0, int socketNumToServer = -1, MediaTranscodingTable * transcodingTable = NULL) [static]
virtual RTCPInstance* ProxyServerMediaSession::createRTCP (Groupsock * RTCPgs, unsigned totSessionBW, unsigned char const * cname, RTPSink * sink) [protected], [virtual]
void ServerMediaSession::decrementReferenceCount () [inline], [inherited]
Definition at line 67 of file ServerMediaSession.hh.
References ServerMediaSession::fReferenceCount.
{ if (fReferenceCount > 0) --fReferenceCount; }
void ServerMediaSession::deleteAllSubsessions () [inherited]
Boolean& ServerMediaSession::deleteWhenUnreferenced () [inline], [inherited]
Definition at line 68 of file ServerMediaSession.hh.
References ServerMediaSession::fDeleteWhenUnreferenced.
{ return fDeleteWhenUnreferenced; }
Boolean ProxyServerMediaSession::describeCompletedSuccessfully () const [inline]
Definition at line 124 of file ProxyServerMediaSession.hh.
References fClientMediaSession, and NULL.
{ return fClientMediaSession != NULL; }
float ServerMediaSession::duration () const [inherited]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
char* ServerMediaSession::generateSDPDescription () [inherited]
void ServerMediaSession::incrementReferenceCount () [inline], [inherited]
Definition at line 66 of file ServerMediaSession.hh.
References ServerMediaSession::fReferenceCount.
{ ++fReferenceCount; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean ServerMediaSession::lookupByName (UsageEnvironment & env, char const * mediumName, ServerMediaSession *& resultSession) [static], [inherited]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
virtual void ServerMediaSession::noteLiveness () [virtual], [inherited]
unsigned ServerMediaSession::numSubsessions () const [inline], [inherited]
Definition at line 52 of file ServerMediaSession.hh.
References ServerMediaSession::fSubsessionCounter.
{ return fSubsessionCounter; }
unsigned ServerMediaSession::referenceCount () const [inline], [inherited]
Definition at line 65 of file ServerMediaSession.hh.
References ServerMediaSession::fReferenceCount.
{ return fReferenceCount; }
void ProxyServerMediaSession::resetDESCRIBEState () [private]
char const* ServerMediaSession::streamName () const [inline], [inherited]
Definition at line 49 of file ServerMediaSession.hh.
References ServerMediaSession::fStreamName.
{ return fStreamName; }
void ServerMediaSession::testScaleFactor (float & scale) [inherited]
char const* ProxyServerMediaSession::url () const
Friends And Related Function Documentation
friend class ProxyRTSPClient [friend]
Definition at line 163 of file ProxyServerMediaSession.hh.
friend class ProxyServerMediaSubsession [friend]
Definition at line 164 of file ProxyServerMediaSession.hh.
Field Documentation
char ProxyServerMediaSession::describeCompletedFlag
Definition at line 121 of file ProxyServerMediaSession.hh.
MediaSession* ProxyServerMediaSession::fClientMediaSession [protected]
Definition at line 160 of file ProxyServerMediaSession.hh.
Referenced by describeCompletedSuccessfully().
createNewProxyRTSPClientFunc* ProxyServerMediaSession::fCreateNewProxyRTSPClientFunc [private]
Definition at line 171 of file ProxyServerMediaSession.hh.
portNumBits ProxyServerMediaSession::fInitialPortNum [private]
Definition at line 173 of file ProxyServerMediaSession.hh.
Boolean ProxyServerMediaSession::fMultiplexRTCPWithRTP [private]
Definition at line 174 of file ProxyServerMediaSession.hh.
GenericMediaServer* ProxyServerMediaSession::fOurMediaServer [protected]
Definition at line 158 of file ProxyServerMediaSession.hh.
class PresentationTimeSessionNormalizer* ProxyServerMediaSession::fPresentationTimeSessionNormalizer [private]
Definition at line 170 of file ProxyServerMediaSession.hh.
ProxyRTSPClient* ProxyServerMediaSession::fProxyRTSPClient [protected]
Definition at line 159 of file ProxyServerMediaSession.hh.
MediaTranscodingTable* ProxyServerMediaSession::fTranscodingTable [private]
Definition at line 172 of file ProxyServerMediaSession.hh.
int ProxyServerMediaSession::fVerbosityLevel [private]
Definition at line 169 of file ProxyServerMediaSession.hh.
The documentation for this class was generated from the following file:
liveMedia/include/ProxyServerMediaSession.hh