OggFileSink Class Reference
#include <OggFileSink.hh>
Public Types
typedef void(afterPlayingFunc) (void *clientData)
Public Member Functions
Boolean startPlaying (MediaSource &source, afterPlayingFunc *afterFunc, void *afterClientData)
virtual void stopPlaying ()
virtual Boolean isRTPSink () const
FramedSource * source () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static OggFileSink * createNew (UsageEnvironment &env, char const *fileName, unsigned samplingFrequency=0, char const *configStr=NULL, unsigned bufferSize=100000, Boolean oneFilePerFrame=False)
static FileSink * createNew (UsageEnvironment &env, char const *fileName, unsigned bufferSize=20000, Boolean oneFilePerFrame=False)
static Boolean lookupByName (UsageEnvironment &env, char const *sinkName, MediaSink *&resultSink)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
OggFileSink (UsageEnvironment &env, FILE *fid, unsigned samplingFrequency, char const *configStr, unsigned bufferSize, char const *perFrameFileNamePrefix)
virtual ~OggFileSink ()
virtual Boolean continuePlaying ()
virtual void addData (unsigned char const *data, unsigned dataSize, struct timeval presentationTime)
virtual void afterGettingFrame (unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime)
virtual Boolean sourceIsCompatibleWithUs (MediaSource &source)
void onSourceClosure ()
TaskToken & nextTask ()
Static Protected Member Functions
static void afterGettingFrame (void *clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds)
static void onSourceClosure (void *clientData)
Protected Attributes
FILE * fOutFid
unsigned char * fBuffer
unsigned fBufferSize
char * fPerFrameFileNamePrefix
char * fPerFrameFileNameBuffer
struct timeval fPrevPresentationTime
unsigned fSamePresentationTimeCounter
FramedSource * fSource
Private Member Functions
void ourOnSourceClosure ()
Static Private Member Functions
static void ourOnSourceClosure (void *clientData)
Private Attributes
unsigned fSamplingFrequency
char const * fConfigStr
Boolean fHaveWrittenFirstFrame
Boolean fHaveSeenEOF
struct timeval fFirstPresentationTime
int64_t fGranulePosition
int64_t fGranulePositionAdjustment
u_int32_t fPageSequenceNumber
u_int8_t fPageHeaderBytes [27]
Boolean fIsTheora
u_int64_t fGranuleIncrementPerFrame
unsigned char * fAltBuffer
unsigned fAltFrameSize
unsigned fAltNumTruncatedBytes
struct timeval fAltPresentationTime
Detailed Description
Definition at line 28 of file OggFileSink.hh.
Member Typedef Documentation
typedef void(MediaSink::afterPlayingFunc) (void *clientData) [inherited]
Definition at line 33 of file MediaSink.hh.
Constructor & Destructor Documentation
OggFileSink::OggFileSink (UsageEnvironment & env, FILE * fid, unsigned samplingFrequency, char const * configStr, unsigned bufferSize, char const * perFrameFileNamePrefix) [protected]
virtual OggFileSink::~OggFileSink () [protected], [virtual]
Member Function Documentation
virtual void OggFileSink::addData (unsigned char const * data, unsigned dataSize, struct timeval presentationTime) [protected], [virtual]
Reimplemented from FileSink .
virtual void OggFileSink::afterGettingFrame (unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime) [protected], [virtual]
Reimplemented from FileSink .
static void FileSink::afterGettingFrame (void * clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds) [static], [protected], [inherited]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
virtual Boolean OggFileSink::continuePlaying () [protected], [virtual]
Reimplemented from FileSink .
static OggFileSink* OggFileSink::createNew (UsageEnvironment & env, char const * fileName, unsigned samplingFrequency = 0, char const * configStr = NULL, unsigned bufferSize = 100000, Boolean oneFilePerFrame = False) [static]
static FileSink* FileSink::createNew (UsageEnvironment & env, char const * fileName, unsigned bufferSize = 20000, Boolean oneFilePerFrame = False) [static], [inherited]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean MediaSink::isRTPSink () const [virtual], [inherited]
Reimplemented in RTPSink .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean MediaSink::lookupByName (UsageEnvironment & env, char const * sinkName, MediaSink *& resultSink) [static], [inherited]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
static void MediaSink::onSourceClosure (void * clientData) [static], [protected], [inherited]
void MediaSink::onSourceClosure () [protected], [inherited]
static void OggFileSink::ourOnSourceClosure (void * clientData) [static], [private]
void OggFileSink::ourOnSourceClosure () [private]
FramedSource* MediaSink::source () const [inline], [inherited]
Definition at line 42 of file MediaSink.hh.
References MediaSink::fSource.
{return fSource;}
virtual Boolean MediaSink::sourceIsCompatibleWithUs (MediaSource & source) [protected], [virtual], [inherited]
Reimplemented in H265VideoRTPSink , H264VideoRTPSink , AMRAudioRTPSink , MPEG4ESVideoRTPSink , DVVideoRTPSink , AMRAudioFileSink , JPEGVideoRTPSink , and MPEG1or2VideoRTPSink .
Boolean MediaSink::startPlaying (MediaSource & source, afterPlayingFunc * afterFunc, void * afterClientData) [inherited]
virtual void MediaSink::stopPlaying () [virtual], [inherited]
Reimplemented in MultiFramedRTPSink .
Field Documentation
unsigned char* OggFileSink::fAltBuffer [private]
Definition at line 74 of file OggFileSink.hh.
unsigned OggFileSink::fAltFrameSize [private]
Definition at line 75 of file OggFileSink.hh.
unsigned OggFileSink::fAltNumTruncatedBytes [private]
Definition at line 75 of file OggFileSink.hh.
struct timeval OggFileSink::fAltPresentationTime [private]
Definition at line 76 of file OggFileSink.hh.
unsigned char* FileSink::fBuffer [protected], [inherited]
Definition at line 63 of file FileSink.hh.
unsigned FileSink::fBufferSize [protected], [inherited]
Definition at line 64 of file FileSink.hh.
char const* OggFileSink::fConfigStr [private]
Definition at line 59 of file OggFileSink.hh.
struct timeval OggFileSink::fFirstPresentationTime [private]
Definition at line 61 of file OggFileSink.hh.
u_int64_t OggFileSink::fGranuleIncrementPerFrame [private]
Definition at line 70 of file OggFileSink.hh.
int64_t OggFileSink::fGranulePosition [private]
Definition at line 62 of file OggFileSink.hh.
int64_t OggFileSink::fGranulePositionAdjustment [private]
Definition at line 63 of file OggFileSink.hh.
Boolean OggFileSink::fHaveSeenEOF [private]
Definition at line 60 of file OggFileSink.hh.
Boolean OggFileSink::fHaveWrittenFirstFrame [private]
Definition at line 60 of file OggFileSink.hh.
Boolean OggFileSink::fIsTheora [private]
Definition at line 69 of file OggFileSink.hh.
FILE* FileSink::fOutFid [protected], [inherited]
Definition at line 62 of file FileSink.hh.
u_int8_t OggFileSink::fPageHeaderBytes[27] [private]
Definition at line 65 of file OggFileSink.hh.
u_int32_t OggFileSink::fPageSequenceNumber [private]
Definition at line 64 of file OggFileSink.hh.
char* FileSink::fPerFrameFileNameBuffer [protected], [inherited]
Definition at line 66 of file FileSink.hh.
char* FileSink::fPerFrameFileNamePrefix [protected], [inherited]
Definition at line 65 of file FileSink.hh.
struct timeval FileSink::fPrevPresentationTime [protected], [inherited]
Definition at line 67 of file FileSink.hh.
unsigned FileSink::fSamePresentationTimeCounter [protected], [inherited]
Definition at line 68 of file FileSink.hh.
unsigned OggFileSink::fSamplingFrequency [private]
Definition at line 58 of file OggFileSink.hh.
FramedSource* MediaSink::fSource [protected], [inherited]
Definition at line 58 of file MediaSink.hh.
Referenced by MediaSink::source().
The documentation for this class was generated from the following file:
liveMedia/include/OggFileSink.hh