OggFileParser Class Reference
#include <OggFileParser.hh>
Public Member Functions
OggFileParser (OggFile &ourFile, FramedSource *inputSource, FramedSource::onCloseFunc *onEndFunc, void *onEndClientData, OggDemux *ourDemux=NULL)
virtual ~OggFileParser ()
void continueParsing ()
virtual void flushInput ()
Static Public Member Functions
static void continueParsing (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime)
Protected Types
typedef void(clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime)
Protected Member Functions
void saveParserState ()
virtual void restoreSavedParserState ()
u_int32_t get4Bytes ()
u_int32_t test4Bytes ()
u_int16_t get2Bytes ()
u_int8_t get1Byte ()
u_int8_t test1Byte ()
void getBytes (u_int8_t *to, unsigned numBytes)
void testBytes (u_int8_t *to, unsigned numBytes)
void skipBytes (unsigned numBytes)
void skipBits (unsigned numBits)
unsigned getBits (unsigned numBits)
unsigned curOffset () const
unsigned & totNumValidBytes ()
Boolean haveSeenEOF () const
unsigned bankSize () const
Private Member Functions
Boolean needHeaders ()
Boolean parse ()
Boolean parseStartOfFile ()
u_int8_t parseInitialPage ()
void parseAndDeliverPages ()
Boolean parseAndDeliverPage ()
Boolean deliverPacketWithinPage ()
void parseStartOfPage (u_int8_t &header_type_flag, u_int32_t &bitstream_serial_number)
Boolean validateHeader (OggTrack *track, u_int8_t const *p, unsigned headerSize)
Private Attributes
OggFile & fOurFile
FramedSource * fInputSource
FramedSource::onCloseFunc * fOnEndFunc
void * fOnEndClientData
OggDemux * fOurDemux
OggParseState fCurrentParseState
unsigned fNumUnfulfilledTracks
PacketSizeTable * fPacketSizeTable
u_int32_t fCurrentTrackNumber
u_int8_t * fSavedPacket
Detailed Description
Definition at line 50 of file OggFileParser.hh.
Member Typedef Documentation
typedef void(StreamParser::clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime) [protected], [inherited]
Definition at line 33 of file StreamParser.hh.
Constructor & Destructor Documentation
OggFileParser::OggFileParser (OggFile & ourFile, FramedSource * inputSource, FramedSource::onCloseFunc * onEndFunc, void * onEndClientData, OggDemux * ourDemux = NULL)
virtual OggFileParser::~OggFileParser () [virtual]
Member Function Documentation
unsigned StreamParser::bankSize () const [protected], [inherited]
static void OggFileParser::continueParsing (void * clientData, unsigned char * ptr, unsigned size, struct timeval presentationTime) [static]
void OggFileParser::continueParsing ()
unsigned StreamParser::curOffset () const [inline], [protected], [inherited]
Definition at line 100 of file StreamParser.hh.
References StreamParser::fCurParserIndex.
{ return fCurParserIndex; }
Boolean OggFileParser::deliverPacketWithinPage () [private]
virtual void StreamParser::flushInput () [virtual], [inherited]
u_int8_t StreamParser::get1Byte () [inline], [protected], [inherited]
Definition at line 72 of file StreamParser.hh.
References StreamParser::curBank(), StreamParser::ensureValidBytes(), StreamParser::fCurParserIndex, and StreamParser::fRemainingUnparsedBits.
Referenced by MPEGVideoStreamParser::saveToNextCode(), and MPEGVideoStreamParser::skipToNextCode().
                      { // byte-aligned
    ensureValidBytes(1);
    fRemainingUnparsedBits = 0;
    return curBank()[fCurParserIndex++];
  }
u_int16_t StreamParser::get2Bytes () [inline], [protected], [inherited]
Definition at line 60 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::nextToParse().
                        {
    ensureValidBytes(2);
    unsigned char const* ptr = nextToParse();
    u_int16_t result = (ptr[0]<<8)|ptr[1];
    fCurParserIndex += 2;
    fRemainingUnparsedBits = 0;
    return result;
  }
u_int32_t StreamParser::get4Bytes () [inline], [protected], [inherited]
Definition at line 46 of file StreamParser.hh.
References StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::test4Bytes().
Referenced by MPEGVideoStreamParser::saveToNextCode(), and MPEGVideoStreamParser::skipToNextCode().
                        { // byte-aligned; returned in big-endian order
    u_int32_t result = test4Bytes();
    fCurParserIndex += 4;
    fRemainingUnparsedBits = 0;
    return result;
  }
unsigned StreamParser::getBits (unsigned numBits) [protected], [inherited]
void StreamParser::getBytes (u_int8_t * to, unsigned numBytes) [inline], [protected], [inherited]
Definition at line 82 of file StreamParser.hh.
References StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::testBytes().
                                                 {
    testBytes(to, numBytes);
    fCurParserIndex += numBytes;
    fRemainingUnparsedBits = 0;
  }
Boolean StreamParser::haveSeenEOF () const [inline], [protected], [inherited]
Definition at line 104 of file StreamParser.hh.
References StreamParser::fHaveSeenEOF.
{ return fHaveSeenEOF; }
Boolean OggFileParser::needHeaders () [inline], [private]
Definition at line 62 of file OggFileParser.hh.
References fNumUnfulfilledTracks.
{ return fNumUnfulfilledTracks > 0; }
Boolean OggFileParser::parse () [private]
Boolean OggFileParser::parseAndDeliverPage () [private]
void OggFileParser::parseAndDeliverPages () [private]
u_int8_t OggFileParser::parseInitialPage () [private]
Boolean OggFileParser::parseStartOfFile () [private]
void OggFileParser::parseStartOfPage (u_int8_t & header_type_flag, u_int32_t & bitstream_serial_number) [private]
virtual void StreamParser::restoreSavedParserState () [protected], [virtual], [inherited]
Reimplemented in MPEGVideoStreamParser , H263plusVideoStreamParser , and MatroskaFileParser .
void StreamParser::saveParserState () [protected], [inherited]
Referenced by MPEGVideoStreamParser::setParseState().
void StreamParser::skipBits (unsigned numBits) [protected], [inherited]
void StreamParser::skipBytes (unsigned numBytes) [inline], [protected], [inherited]
Definition at line 91 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::fCurParserIndex.
                                    {
    ensureValidBytes(numBytes);
    fCurParserIndex += numBytes;
  }
u_int8_t StreamParser::test1Byte () [inline], [protected], [inherited]
Definition at line 77 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
                       { // as above, but doesn't advance ptr
    ensureValidBytes(1);
    return nextToParse()[0];
  }
u_int32_t StreamParser::test4Bytes () [inline], [protected], [inherited]
Definition at line 53 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
Referenced by StreamParser::get4Bytes().
                         { // as above, but doesn't advance ptr
    ensureValidBytes(4);
    unsigned char const* ptr = nextToParse();
    return (ptr[0]<<24)|(ptr[1]<<16)|(ptr[2]<<8)|ptr[3];
  }
void StreamParser::testBytes (u_int8_t * to, unsigned numBytes) [inline], [protected], [inherited]
Definition at line 87 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
Referenced by StreamParser::getBytes().
                                                  { // as above, but doesn't advance ptr
    ensureValidBytes(numBytes);
    memmove(to, nextToParse(), numBytes);
  }
unsigned& StreamParser::totNumValidBytes () [inline], [protected], [inherited]
Definition at line 102 of file StreamParser.hh.
References StreamParser::fTotNumValidBytes.
{ return fTotNumValidBytes; }
Boolean OggFileParser::validateHeader (OggTrack * track, u_int8_t const * p, unsigned headerSize) [private]
Field Documentation
OggParseState OggFileParser::fCurrentParseState [private]
Definition at line 83 of file OggFileParser.hh.
u_int32_t OggFileParser::fCurrentTrackNumber [private]
Definition at line 87 of file OggFileParser.hh.
FramedSource* OggFileParser::fInputSource [private]
Definition at line 79 of file OggFileParser.hh.
unsigned OggFileParser::fNumUnfulfilledTracks [private]
Definition at line 85 of file OggFileParser.hh.
Referenced by needHeaders().
void* OggFileParser::fOnEndClientData [private]
Definition at line 81 of file OggFileParser.hh.
FramedSource::onCloseFunc* OggFileParser::fOnEndFunc [private]
Definition at line 80 of file OggFileParser.hh.
OggDemux* OggFileParser::fOurDemux [private]
Definition at line 82 of file OggFileParser.hh.
OggFile& OggFileParser::fOurFile [private]
Definition at line 78 of file OggFileParser.hh.
PacketSizeTable* OggFileParser::fPacketSizeTable [private]
Definition at line 86 of file OggFileParser.hh.
u_int8_t* OggFileParser::fSavedPacket [private]
Definition at line 88 of file OggFileParser.hh.
The documentation for this class was generated from the following file:
liveMedia/OggFileParser.hh