TCPStreamSink Class Reference
#include <TCPStreamSink.hh>
Public Types
typedef void(afterPlayingFunc) (void *clientData)
Public Member Functions
Boolean startPlaying (MediaSource &source, afterPlayingFunc *afterFunc, void *afterClientData)
virtual void stopPlaying ()
virtual Boolean isRTPSink () const
FramedSource * source () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static TCPStreamSink * createNew (UsageEnvironment &env, int socketNum)
static Boolean lookupByName (UsageEnvironment &env, char const *sinkName, MediaSink *&resultSink)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TCPStreamSink (UsageEnvironment &env, int socketNum)
virtual ~TCPStreamSink ()
virtual Boolean continuePlaying ()
virtual Boolean sourceIsCompatibleWithUs (MediaSource &source)
void onSourceClosure ()
TaskToken & nextTask ()
Static Protected Member Functions
static void onSourceClosure (void *clientData)
Protected Attributes
FramedSource * fSource
Private Member Functions
void processBuffer ()
void socketWritableHandler1 ()
void afterGettingFrame (unsigned frameSize, unsigned numTruncatedBytes)
void ourOnSourceClosure1 ()
unsigned numUnwrittenBytes () const
unsigned freeBufferSpace () const
Static Private Member Functions
static void socketWritableHandler (void *clientData, int mask)
static void afterGettingFrame (void *clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval, unsigned)
static void ourOnSourceClosure (void *clientData)
Private Attributes
unsigned char fBuffer [TCP_STREAM_SINK_BUFFER_SIZE]
unsigned fUnwrittenBytesStart
unsigned fUnwrittenBytesEnd
Boolean fInputSourceIsOpen
Boolean fOutputSocketIsWritable
int fOutputSocketNum
Detailed Description
Definition at line 30 of file TCPStreamSink.hh.
Member Typedef Documentation
typedef void(MediaSink::afterPlayingFunc) (void *clientData) [inherited]
Definition at line 33 of file MediaSink.hh.
Constructor & Destructor Documentation
TCPStreamSink::TCPStreamSink (UsageEnvironment & env, int socketNum) [protected]
virtual TCPStreamSink::~TCPStreamSink () [protected], [virtual]
Member Function Documentation
static void TCPStreamSink::afterGettingFrame (void * clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval , unsigned) [static], [private]
void TCPStreamSink::afterGettingFrame (unsigned frameSize, unsigned numTruncatedBytes) [private]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
virtual Boolean TCPStreamSink::continuePlaying () [protected], [virtual]
Implements MediaSink .
static TCPStreamSink* TCPStreamSink::createNew (UsageEnvironment & env, int socketNum) [static]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
unsigned TCPStreamSink::freeBufferSpace () const [inline], [private]
Definition at line 58 of file TCPStreamSink.hh.
References fUnwrittenBytesEnd, and TCP_STREAM_SINK_BUFFER_SIZE.
{ return TCP_STREAM_SINK_BUFFER_SIZE - fUnwrittenBytesEnd; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean MediaSink::isRTPSink () const [virtual], [inherited]
Reimplemented in RTPSink .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean MediaSink::lookupByName (UsageEnvironment & env, char const * sinkName, MediaSink *& resultSink) [static], [inherited]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
unsigned TCPStreamSink::numUnwrittenBytes () const [inline], [private]
Definition at line 57 of file TCPStreamSink.hh.
References fUnwrittenBytesEnd, and fUnwrittenBytesStart.
{ return fUnwrittenBytesEnd - fUnwrittenBytesStart; }
static void MediaSink::onSourceClosure (void * clientData) [static], [protected], [inherited]
void MediaSink::onSourceClosure () [protected], [inherited]
static void TCPStreamSink::ourOnSourceClosure (void * clientData) [static], [private]
void TCPStreamSink::ourOnSourceClosure1 () [private]
void TCPStreamSink::processBuffer () [private]
static void TCPStreamSink::socketWritableHandler (void * clientData, int mask) [static], [private]
void TCPStreamSink::socketWritableHandler1 () [private]
FramedSource* MediaSink::source () const [inline], [inherited]
Definition at line 42 of file MediaSink.hh.
References MediaSink::fSource.
{return fSource;}
virtual Boolean MediaSink::sourceIsCompatibleWithUs (MediaSource & source) [protected], [virtual], [inherited]
Reimplemented in H265VideoRTPSink , H264VideoRTPSink , AMRAudioRTPSink , MPEG4ESVideoRTPSink , DVVideoRTPSink , AMRAudioFileSink , JPEGVideoRTPSink , and MPEG1or2VideoRTPSink .
Boolean MediaSink::startPlaying (MediaSource & source, afterPlayingFunc * afterFunc, void * afterClientData) [inherited]
virtual void MediaSink::stopPlaying () [virtual], [inherited]
Reimplemented in MultiFramedRTPSink .
Field Documentation
unsigned char TCPStreamSink::fBuffer[TCP_STREAM_SINK_BUFFER_SIZE] [private]
Definition at line 61 of file TCPStreamSink.hh.
Boolean TCPStreamSink::fInputSourceIsOpen [private]
Definition at line 63 of file TCPStreamSink.hh.
Boolean TCPStreamSink::fOutputSocketIsWritable [private]
Definition at line 63 of file TCPStreamSink.hh.
int TCPStreamSink::fOutputSocketNum [private]
Definition at line 64 of file TCPStreamSink.hh.
FramedSource* MediaSink::fSource [protected], [inherited]
Definition at line 58 of file MediaSink.hh.
Referenced by MediaSink::source().
unsigned TCPStreamSink::fUnwrittenBytesEnd [private]
Definition at line 62 of file TCPStreamSink.hh.
Referenced by freeBufferSpace(), and numUnwrittenBytes().
unsigned TCPStreamSink::fUnwrittenBytesStart [private]
Definition at line 62 of file TCPStreamSink.hh.
Referenced by numUnwrittenBytes().
The documentation for this class was generated from the following file:
liveMedia/include/TCPStreamSink.hh