MediaSink Class Reference
#include <MediaSink.hh>
Public Types
typedef void(afterPlayingFunc) (void *clientData)
Public Member Functions
Boolean startPlaying (MediaSource &source, afterPlayingFunc *afterFunc, void *afterClientData)
virtual void stopPlaying ()
virtual Boolean isRTPSink () const
FramedSource * source () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *sinkName, MediaSink *&resultSink)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
MediaSink (UsageEnvironment &env)
virtual ~MediaSink ()
virtual Boolean sourceIsCompatibleWithUs (MediaSource &source)
virtual Boolean continuePlaying ()=0
void onSourceClosure ()
TaskToken & nextTask ()
Static Protected Member Functions
static void onSourceClosure (void *clientData)
Protected Attributes
FramedSource * fSource
Private Member Functions
virtual Boolean isSink () const
Private Attributes
afterPlayingFunc * fAfterFunc
void * fAfterClientData
Detailed Description
Definition at line 28 of file MediaSink.hh.
Member Typedef Documentation
typedef void(MediaSink::afterPlayingFunc) (void *clientData)
Definition at line 33 of file MediaSink.hh.
Constructor & Destructor Documentation
MediaSink::MediaSink (UsageEnvironment & env) [protected]
virtual MediaSink::~MediaSink () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
virtual Boolean MediaSink::continuePlaying () [protected], [pure virtual]
Implemented in MultiFramedRTPSink , FileSink , OggFileSink , T140TextRTPSink , H264or5VideoRTPSink , TCPStreamSink , and BasicUDPSink .
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean MediaSink::isRTPSink () const [virtual]
Reimplemented in RTPSink .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean MediaSink::isSink () const [private], [virtual]
Reimplemented from Medium .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean MediaSink::lookupByName (UsageEnvironment & env, char const * sinkName, MediaSink *& resultSink) [static]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
static void MediaSink::onSourceClosure (void * clientData) [static], [protected]
void MediaSink::onSourceClosure () [protected]
FramedSource* MediaSink::source () const [inline]
Definition at line 42 of file MediaSink.hh.
References fSource.
{return fSource;}
virtual Boolean MediaSink::sourceIsCompatibleWithUs (MediaSource & source) [protected], [virtual]
Reimplemented in H265VideoRTPSink , H264VideoRTPSink , AMRAudioRTPSink , MPEG4ESVideoRTPSink , DVVideoRTPSink , AMRAudioFileSink , JPEGVideoRTPSink , and MPEG1or2VideoRTPSink .
Boolean MediaSink::startPlaying (MediaSource & source, afterPlayingFunc * afterFunc, void * afterClientData)
virtual void MediaSink::stopPlaying () [virtual]
Reimplemented in MultiFramedRTPSink .
Field Documentation
void* MediaSink::fAfterClientData [private]
Definition at line 67 of file MediaSink.hh.
afterPlayingFunc* MediaSink::fAfterFunc [private]
Definition at line 66 of file MediaSink.hh.
FramedSource* MediaSink::fSource [protected]
Definition at line 58 of file MediaSink.hh.
Referenced by source().
The documentation for this class was generated from the following file:
liveMedia/include/MediaSink.hh