MPEGVideoStreamParser Class Reference
#include <MPEGVideoStreamParser.hh>
Public Member Functions
MPEGVideoStreamParser (MPEGVideoStreamFramer *usingSource, FramedSource *inputSource)
virtual ~MPEGVideoStreamParser ()
void registerReadInterest (unsigned char *to, unsigned maxSize)
virtual unsigned parse ()=0
unsigned numTruncatedBytes () const
virtual void flushInput ()
Protected Types
typedef void(clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime)
Protected Member Functions
void setParseState ()
void saveByte (u_int8_t byte)
void save4Bytes (u_int32_t word)
void saveToNextCode (u_int32_t &curWord)
void skipToNextCode (u_int32_t &curWord)
unsigned curFrameSize ()
void saveParserState ()
u_int32_t get4Bytes ()
u_int32_t test4Bytes ()
u_int16_t get2Bytes ()
u_int8_t get1Byte ()
u_int8_t test1Byte ()
void getBytes (u_int8_t *to, unsigned numBytes)
void testBytes (u_int8_t *to, unsigned numBytes)
void skipBytes (unsigned numBytes)
void skipBits (unsigned numBits)
unsigned getBits (unsigned numBits)
unsigned curOffset () const
unsigned & totNumValidBytes ()
Boolean haveSeenEOF () const
unsigned bankSize () const
Protected Attributes
MPEGVideoStreamFramer * fUsingSource
unsigned char * fStartOfFrame
unsigned char * fTo
unsigned char * fLimit
unsigned fNumTruncatedBytes
unsigned char * fSavedTo
unsigned fSavedNumTruncatedBytes
Private Member Functions
virtual void restoreSavedParserState ()
Detailed Description
Definition at line 33 of file MPEGVideoStreamParser.hh.
Member Typedef Documentation
typedef void(StreamParser::clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime) [protected], [inherited]
Definition at line 33 of file StreamParser.hh.
Constructor & Destructor Documentation
MPEGVideoStreamParser::MPEGVideoStreamParser (MPEGVideoStreamFramer * usingSource, FramedSource * inputSource)
virtual MPEGVideoStreamParser::~MPEGVideoStreamParser () [virtual]
Member Function Documentation
unsigned StreamParser::bankSize () const [protected], [inherited]
unsigned MPEGVideoStreamParser::curFrameSize () [inline], [protected]
Definition at line 114 of file MPEGVideoStreamParser.hh.
References fStartOfFrame.
{ return fTo - fStartOfFrame; }
unsigned StreamParser::curOffset () const [inline], [protected], [inherited]
Definition at line 100 of file StreamParser.hh.
References StreamParser::fCurParserIndex.
{ return fCurParserIndex; }
virtual void StreamParser::flushInput () [virtual], [inherited]
u_int8_t StreamParser::get1Byte () [inline], [protected], [inherited]
Definition at line 72 of file StreamParser.hh.
References StreamParser::curBank(), StreamParser::ensureValidBytes(), StreamParser::fCurParserIndex, and StreamParser::fRemainingUnparsedBits.
Referenced by saveToNextCode(), and skipToNextCode().
                      { // byte-aligned
    ensureValidBytes(1);
    fRemainingUnparsedBits = 0;
    return curBank()[fCurParserIndex++];
  }
u_int16_t StreamParser::get2Bytes () [inline], [protected], [inherited]
Definition at line 60 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::nextToParse().
                        {
    ensureValidBytes(2);
    unsigned char const* ptr = nextToParse();
    u_int16_t result = (ptr[0]<<8)|ptr[1];
    fCurParserIndex += 2;
    fRemainingUnparsedBits = 0;
    return result;
  }
u_int32_t StreamParser::get4Bytes () [inline], [protected], [inherited]
Definition at line 46 of file StreamParser.hh.
References StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::test4Bytes().
Referenced by saveToNextCode(), and skipToNextCode().
                        { // byte-aligned; returned in big-endian order
    u_int32_t result = test4Bytes();
    fCurParserIndex += 4;
    fRemainingUnparsedBits = 0;
    return result;
  }
unsigned StreamParser::getBits (unsigned numBits) [protected], [inherited]
void StreamParser::getBytes (u_int8_t * to, unsigned numBytes) [inline], [protected], [inherited]
Definition at line 82 of file StreamParser.hh.
References StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::testBytes().
                                                 {
    testBytes(to, numBytes);
    fCurParserIndex += numBytes;
    fRemainingUnparsedBits = 0;
  }
Boolean StreamParser::haveSeenEOF () const [inline], [protected], [inherited]
Definition at line 104 of file StreamParser.hh.
References StreamParser::fHaveSeenEOF.
{ return fHaveSeenEOF; }
unsigned MPEGVideoStreamParser::numTruncatedBytes () const [inline]
Definition at line 45 of file MPEGVideoStreamParser.hh.
References fNumTruncatedBytes.
{ return fNumTruncatedBytes; }
virtual unsigned MPEGVideoStreamParser::parse () [pure virtual]
void MPEGVideoStreamParser::registerReadInterest (unsigned char * to, unsigned maxSize)
virtual void MPEGVideoStreamParser::restoreSavedParserState () [private], [virtual]
Reimplemented from StreamParser .
void MPEGVideoStreamParser::save4Bytes (u_int32_t word) [inline], [protected]
Definition at line 64 of file MPEGVideoStreamParser.hh.
References fLimit, fNumTruncatedBytes, and fTo.
Referenced by saveToNextCode().
                                  {
    if (fTo+4 > fLimit) { // there's no space left
      fNumTruncatedBytes += 4;
      return;
    }
    *fTo++ = word>>24; *fTo++ = word>>16; *fTo++ = word>>8; *fTo++ = word;
  }
void MPEGVideoStreamParser::saveByte (u_int8_t byte) [inline], [protected]
Definition at line 55 of file MPEGVideoStreamParser.hh.
References fLimit, fNumTruncatedBytes, and fTo.
Referenced by saveToNextCode().
                               {
    if (fTo >= fLimit) { // there's no space left
      ++fNumTruncatedBytes;
      return;
    }
    *fTo++ = byte;
  }
void StreamParser::saveParserState () [protected], [inherited]
Referenced by setParseState().
void MPEGVideoStreamParser::saveToNextCode (u_int32_t & curWord) [inline], [protected]
Definition at line 74 of file MPEGVideoStreamParser.hh.
References StreamParser::get1Byte(), StreamParser::get4Bytes(), save4Bytes(), and saveByte().
                                          {
    saveByte(curWord>>24);
    curWord = (curWord<<8)|get1Byte();
    while ((curWord&0xFFFFFF00) != 0x00000100) {
      if ((unsigned)(curWord&0xFF) > 1) {
        // a sync word definitely doesn't begin anywhere in "curWord"
        save4Bytes(curWord);
        curWord = get4Bytes();
      } else {
        // a sync word might begin in "curWord", although not at its start
        saveByte(curWord>>24);
        unsigned char newByte = get1Byte();
        curWord = (curWord<<8)|newByte;
      }
    }
  }
void MPEGVideoStreamParser::setParseState () [inline], [protected]
Definition at line 48 of file MPEGVideoStreamParser.hh.
References fNumTruncatedBytes, fSavedNumTruncatedBytes, fSavedTo, fTo, and StreamParser::saveParserState().
                       {
    fSavedTo = fTo;
    fSavedNumTruncatedBytes = fNumTruncatedBytes;
    saveParserState();
  }
void StreamParser::skipBits (unsigned numBits) [protected], [inherited]
void StreamParser::skipBytes (unsigned numBytes) [inline], [protected], [inherited]
Definition at line 91 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::fCurParserIndex.
                                    {
    ensureValidBytes(numBytes);
    fCurParserIndex += numBytes;
  }
void MPEGVideoStreamParser::skipToNextCode (u_int32_t & curWord) [inline], [protected]
Definition at line 92 of file MPEGVideoStreamParser.hh.
References StreamParser::get1Byte(), and StreamParser::get4Bytes().
                                          {
    curWord = (curWord<<8)|get1Byte();
    while ((curWord&0xFFFFFF00) != 0x00000100) {
      if ((unsigned)(curWord&0xFF) > 1) {
        // a sync word definitely doesn't begin anywhere in "curWord"
        curWord = get4Bytes();
      } else {
        // a sync word might begin in "curWord", although not at its start
        unsigned char newByte = get1Byte();
        curWord = (curWord<<8)|newByte;
      }
    }
  }
u_int8_t StreamParser::test1Byte () [inline], [protected], [inherited]
Definition at line 77 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
                       { // as above, but doesn't advance ptr
    ensureValidBytes(1);
    return nextToParse()[0];
  }
u_int32_t StreamParser::test4Bytes () [inline], [protected], [inherited]
Definition at line 53 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
Referenced by StreamParser::get4Bytes().
                         { // as above, but doesn't advance ptr
    ensureValidBytes(4);
    unsigned char const* ptr = nextToParse();
    return (ptr[0]<<24)|(ptr[1]<<16)|(ptr[2]<<8)|ptr[3];
  }
void StreamParser::testBytes (u_int8_t * to, unsigned numBytes) [inline], [protected], [inherited]
Definition at line 87 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
Referenced by StreamParser::getBytes().
                                                  { // as above, but doesn't advance ptr
    ensureValidBytes(numBytes);
    memmove(to, nextToParse(), numBytes);
  }
unsigned& StreamParser::totNumValidBytes () [inline], [protected], [inherited]
Definition at line 102 of file StreamParser.hh.
References StreamParser::fTotNumValidBytes.
{ return fTotNumValidBytes; }
Field Documentation
unsigned char* MPEGVideoStreamParser::fLimit [protected]
Definition at line 112 of file MPEGVideoStreamParser.hh.
Referenced by save4Bytes(), and saveByte().
unsigned MPEGVideoStreamParser::fNumTruncatedBytes [protected]
Definition at line 113 of file MPEGVideoStreamParser.hh.
Referenced by numTruncatedBytes(), save4Bytes(), saveByte(), and setParseState().
unsigned MPEGVideoStreamParser::fSavedNumTruncatedBytes [protected]
Definition at line 116 of file MPEGVideoStreamParser.hh.
Referenced by setParseState().
unsigned char* MPEGVideoStreamParser::fSavedTo [protected]
Definition at line 115 of file MPEGVideoStreamParser.hh.
Referenced by setParseState().
unsigned char* MPEGVideoStreamParser::fStartOfFrame [protected]
Definition at line 110 of file MPEGVideoStreamParser.hh.
Referenced by curFrameSize().
unsigned char* MPEGVideoStreamParser::fTo [protected]
Definition at line 111 of file MPEGVideoStreamParser.hh.
Referenced by save4Bytes(), saveByte(), and setParseState().
MPEGVideoStreamFramer* MPEGVideoStreamParser::fUsingSource [protected]
Definition at line 107 of file MPEGVideoStreamParser.hh.
The documentation for this class was generated from the following file:
liveMedia/MPEGVideoStreamParser.hh