OnDemandServerMediaSubsession Class Reference
#include <OnDemandServerMediaSubsession.hh>
Public Member Functions
void multiplexRTCPWithRTP ()
void setRTCPAppPacketHandler (RTCPAppHandlerFunc *handler, void *clientData)
void sendRTCPAppPacket (u_int8_t subtype, char const *name, u_int8_t *appDependentData, unsigned appDependentDataSize)
unsigned trackNumber () const
char const * trackId ()
virtual void testScaleFactor (float &scale)
virtual float duration () const
virtual void getAbsoluteTimeRange (char *&absStartTime, char *&absEndTime) const
void setServerAddressAndPortForSDP (netAddressBits addressBits, portNumBits portBits)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
OnDemandServerMediaSubsession (UsageEnvironment &env, Boolean reuseFirstSource, portNumBits initialPortNum=6970, Boolean multiplexRTCPWithRTP=False)
virtual ~OnDemandServerMediaSubsession ()
virtual char const * sdpLines ()
virtual void getStreamParameters (unsigned clientSessionId, netAddressBits clientAddress, Port const &clientRTPPort, Port const &clientRTCPPort, int tcpSocketNum, unsigned char rtpChannelId, unsigned char rtcpChannelId, netAddressBits &destinationAddress, u_int8_t &destinationTTL, Boolean &isMulticast, Port &serverRTPPort, Port &serverRTCPPort, void *&streamToken)
virtual void startStream (unsigned clientSessionId, void *streamToken, TaskFunc *rtcpRRHandler, void *rtcpRRHandlerClientData, unsigned short &rtpSeqNum, unsigned &rtpTimestamp, ServerRequestAlternativeByteHandler *serverRequestAlternativeByteHandler, void *serverRequestAlternativeByteHandlerClientData)
virtual void pauseStream (unsigned clientSessionId, void *streamToken)
virtual void seekStream (unsigned clientSessionId, void *streamToken, double &seekNPT, double streamDuration, u_int64_t &numBytes)
virtual void seekStream (unsigned clientSessionId, void *streamToken, char *&absStart, char *&absEnd)
virtual void nullSeekStream (unsigned clientSessionId, void *streamToken, double streamEndTime, u_int64_t &numBytes)
virtual void setStreamScale (unsigned clientSessionId, void *streamToken, float scale)
virtual float getCurrentNPT (void *streamToken)
virtual FramedSource * getStreamSource (void *streamToken)
virtual void getRTPSinkandRTCP (void *streamToken, RTPSink const *&rtpSink, RTCPInstance const *&rtcp)
virtual void deleteStream (unsigned clientSessionId, void *&streamToken)
virtual char const * getAuxSDPLine (RTPSink *rtpSink, FramedSource *inputSource)
virtual void seekStreamSource (FramedSource *inputSource, double &seekNPT, double streamDuration, u_int64_t &numBytes)
virtual void seekStreamSource (FramedSource *inputSource, char *&absStart, char *&absEnd)
virtual void setStreamSourceScale (FramedSource *inputSource, float scale)
virtual void setStreamSourceDuration (FramedSource *inputSource, double streamDuration, u_int64_t &numBytes)
virtual void closeStreamSource (FramedSource *inputSource)
virtual FramedSource * createNewStreamSource (unsigned clientSessionId, unsigned &estBitrate)=0
virtual RTPSink * createNewRTPSink (Groupsock *rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic, FramedSource *inputSource)=0
virtual Groupsock * createGroupsock (struct in_addr const &addr, Port port)
virtual RTCPInstance * createRTCP (Groupsock *RTCPgs, unsigned totSessionBW, unsigned char const *cname, RTPSink *sink)
char const * rangeSDPLine () const
TaskToken & nextTask ()
Protected Attributes
char * fSDPLines
HashTable * fDestinationsHashTable
ServerMediaSession * fParentSession
netAddressBits fServerAddressForSDP
portNumBits fPortNumForSDP
Private Member Functions
void setSDPLinesFromRTPSink (RTPSink *rtpSink, FramedSource *inputSource, unsigned estBitrate)
Private Attributes
Boolean fReuseFirstSource
portNumBits fInitialPortNum
Boolean fMultiplexRTCPWithRTP
void * fLastStreamToken
char fCNAME [100]
RTCPAppHandlerFunc * fAppHandlerTask
void * fAppHandlerClientData
Friends
class StreamState
Detailed Description
Definition at line 38 of file OnDemandServerMediaSubsession.hh.
Constructor & Destructor Documentation
OnDemandServerMediaSubsession::OnDemandServerMediaSubsession (UsageEnvironment & env, Boolean reuseFirstSource, portNumBits initialPortNum = 6970, Boolean multiplexRTCPWithRTP = False) [protected]
virtual OnDemandServerMediaSubsession::~OnDemandServerMediaSubsession () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
virtual void OnDemandServerMediaSubsession::closeStreamSource (FramedSource * inputSource) [protected], [virtual]
virtual Groupsock* OnDemandServerMediaSubsession::createGroupsock (struct in_addr const & addr, Port port) [protected], [virtual]
virtual RTPSink* OnDemandServerMediaSubsession::createNewRTPSink (Groupsock * rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic, FramedSource * inputSource) [protected], [pure virtual]
Implemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , H264VideoFileServerMediaSubsession , H265VideoFileServerMediaSubsession , MPEG1or2DemuxedServerMediaSubsession , MPEG4VideoFileServerMediaSubsession , MPEG1or2VideoFileServerMediaSubsession , WAVAudioFileServerMediaSubsession , MatroskaFileServerMediaSubsession , MPEG2TransportUDPServerMediaSubsession , OggFileServerMediaSubsession , DVVideoFileServerMediaSubsession , AC3AudioFileServerMediaSubsession , ADTSAudioFileServerMediaSubsession , AMRAudioFileServerMediaSubsession , and H263plusVideoFileServerMediaSubsession .
virtual FramedSource* OnDemandServerMediaSubsession::createNewStreamSource (unsigned clientSessionId, unsigned & estBitrate) [protected], [pure virtual]
Implemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , H264VideoFileServerMediaSubsession , H265VideoFileServerMediaSubsession , MPEG1or2DemuxedServerMediaSubsession , MPEG4VideoFileServerMediaSubsession , MP3AudioMatroskaFileServerMediaSubsession , MPEG1or2VideoFileServerMediaSubsession , WAVAudioFileServerMediaSubsession , MatroskaFileServerMediaSubsession , DVVideoFileServerMediaSubsession , MPEG2TransportUDPServerMediaSubsession , OggFileServerMediaSubsession , AC3AudioFileServerMediaSubsession , ADTSAudioFileServerMediaSubsession , AMRAudioFileServerMediaSubsession , and H263plusVideoFileServerMediaSubsession .
virtual RTCPInstance* OnDemandServerMediaSubsession::createRTCP (Groupsock * RTCPgs, unsigned totSessionBW, unsigned char const * cname, RTPSink * sink) [protected], [virtual]
virtual void OnDemandServerMediaSubsession::deleteStream (unsigned clientSessionId, void *& streamToken) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
Reimplemented in MPEG2TransportFileServerMediaSubsession .
virtual float ServerMediaSubsession::duration () const [virtual], [inherited]
Reimplemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , MPEG1or2DemuxedServerMediaSubsession , WAVAudioFileServerMediaSubsession , DVVideoFileServerMediaSubsession , and MatroskaFileServerMediaSubsession .
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual void ServerMediaSubsession::getAbsoluteTimeRange (char *& absStartTime, char *& absEndTime) const [virtual], [inherited]
virtual char const* OnDemandServerMediaSubsession::getAuxSDPLine (RTPSink * rtpSink, FramedSource * inputSource) [protected], [virtual]
Reimplemented in H264VideoFileServerMediaSubsession , H265VideoFileServerMediaSubsession , MPEG4VideoFileServerMediaSubsession , and DVVideoFileServerMediaSubsession .
virtual float OnDemandServerMediaSubsession::getCurrentNPT (void * streamToken) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::getRTPSinkandRTCP (void * streamToken, RTPSink const *& rtpSink, RTCPInstance const *& rtcp) [protected], [virtual]
Implements ServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::getStreamParameters (unsigned clientSessionId, netAddressBits clientAddress, Port const & clientRTPPort, Port const & clientRTCPPort, int tcpSocketNum, unsigned char rtpChannelId, unsigned char rtcpChannelId, netAddressBits & destinationAddress, u_int8_t & destinationTTL, Boolean & isMulticast, Port & serverRTPPort, Port & serverRTCPPort, void *& streamToken) [protected], [virtual]
Implements ServerMediaSubsession .
virtual FramedSource* OnDemandServerMediaSubsession::getStreamSource (void * streamToken) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
void OnDemandServerMediaSubsession::multiplexRTCPWithRTP () [inline]
Definition at line 109 of file OnDemandServerMediaSubsession.hh.
References fMultiplexRTCPWithRTP, and True.
{ fMultiplexRTCPWithRTP = True; }
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
virtual void OnDemandServerMediaSubsession::nullSeekStream (unsigned clientSessionId, void * streamToken, double streamEndTime, u_int64_t & numBytes) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::pauseStream (unsigned clientSessionId, void * streamToken) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
Reimplemented in MPEG2TransportFileServerMediaSubsession .
char const* ServerMediaSubsession::rangeSDPLine () const [protected], [inherited]
virtual char const* OnDemandServerMediaSubsession::sdpLines () [protected], [virtual]
Implements ServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::seekStream (unsigned clientSessionId, void * streamToken, double & seekNPT, double streamDuration, u_int64_t & numBytes) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
Reimplemented in MPEG2TransportFileServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::seekStream (unsigned clientSessionId, void * streamToken, char *& absStart, char *& absEnd) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::seekStreamSource (FramedSource * inputSource, double & seekNPT, double streamDuration, u_int64_t & numBytes) [protected], [virtual]
Reimplemented in MP3AudioFileServerMediaSubsession , MPEG1or2DemuxedServerMediaSubsession , MP3AudioMatroskaFileServerMediaSubsession , WAVAudioFileServerMediaSubsession , MatroskaFileServerMediaSubsession , and DVVideoFileServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::seekStreamSource (FramedSource * inputSource, char *& absStart, char *& absEnd) [protected], [virtual]
void OnDemandServerMediaSubsession::sendRTCPAppPacket (u_int8_t subtype, char const * name, u_int8_t * appDependentData, unsigned appDependentDataSize)
void OnDemandServerMediaSubsession::setRTCPAppPacketHandler (RTCPAppHandlerFunc * handler, void * clientData)
void OnDemandServerMediaSubsession::setSDPLinesFromRTPSink (RTPSink * rtpSink, FramedSource * inputSource, unsigned estBitrate) [private]
void ServerMediaSubsession::setServerAddressAndPortForSDP (netAddressBits addressBits, portNumBits portBits) [inherited]
virtual void OnDemandServerMediaSubsession::setStreamScale (unsigned clientSessionId, void * streamToken, float scale) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
Reimplemented in MPEG2TransportFileServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::setStreamSourceDuration (FramedSource * inputSource, double streamDuration, u_int64_t & numBytes) [protected], [virtual]
Reimplemented in WAVAudioFileServerMediaSubsession , and DVVideoFileServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::setStreamSourceScale (FramedSource * inputSource, float scale) [protected], [virtual]
Reimplemented in MP3AudioFileServerMediaSubsession , and WAVAudioFileServerMediaSubsession .
virtual void OnDemandServerMediaSubsession::startStream (unsigned clientSessionId, void * streamToken, TaskFunc * rtcpRRHandler, void * rtcpRRHandlerClientData, unsigned short & rtpSeqNum, unsigned & rtpTimestamp, ServerRequestAlternativeByteHandler * serverRequestAlternativeByteHandler, void * serverRequestAlternativeByteHandlerClientData) [protected], [virtual]
Implements ServerMediaSubsession .
Reimplemented in MPEG2TransportFileServerMediaSubsession .
virtual void ServerMediaSubsession::testScaleFactor (float & scale) [virtual], [inherited]
Reimplemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , and WAVAudioFileServerMediaSubsession .
char const* ServerMediaSubsession::trackId () [inherited]
unsigned ServerMediaSubsession::trackNumber () const [inline], [inherited]
Definition at line 122 of file ServerMediaSession.hh.
References ServerMediaSubsession::fTrackNumber.
{ return fTrackNumber; }
Friends And Related Function Documentation
friend class StreamState [friend]
Definition at line 145 of file OnDemandServerMediaSubsession.hh.
Field Documentation
void* OnDemandServerMediaSubsession::fAppHandlerClientData [private]
Definition at line 144 of file OnDemandServerMediaSubsession.hh.
RTCPAppHandlerFunc* OnDemandServerMediaSubsession::fAppHandlerTask [private]
Definition at line 143 of file OnDemandServerMediaSubsession.hh.
char OnDemandServerMediaSubsession::fCNAME[100] [private]
Definition at line 142 of file OnDemandServerMediaSubsession.hh.
HashTable* OnDemandServerMediaSubsession::fDestinationsHashTable [protected]
Definition at line 135 of file OnDemandServerMediaSubsession.hh.
portNumBits OnDemandServerMediaSubsession::fInitialPortNum [private]
Definition at line 139 of file OnDemandServerMediaSubsession.hh.
void* OnDemandServerMediaSubsession::fLastStreamToken [private]
Definition at line 141 of file OnDemandServerMediaSubsession.hh.
Boolean OnDemandServerMediaSubsession::fMultiplexRTCPWithRTP [private]
Definition at line 140 of file OnDemandServerMediaSubsession.hh.
Referenced by multiplexRTCPWithRTP().
ServerMediaSession* ServerMediaSubsession::fParentSession [protected], [inherited]
Definition at line 190 of file ServerMediaSession.hh.
portNumBits ServerMediaSubsession::fPortNumForSDP [protected], [inherited]
Definition at line 192 of file ServerMediaSession.hh.
Boolean OnDemandServerMediaSubsession::fReuseFirstSource [private]
Definition at line 138 of file OnDemandServerMediaSubsession.hh.
char* OnDemandServerMediaSubsession::fSDPLines [protected]
Definition at line 134 of file OnDemandServerMediaSubsession.hh.
netAddressBits ServerMediaSubsession::fServerAddressForSDP [protected], [inherited]
Definition at line 191 of file ServerMediaSession.hh.
The documentation for this class was generated from the following file:
liveMedia/include/OnDemandServerMediaSubsession.hh