GenericMediaServer Class Reference
#include <GenericMediaServer.hh>
Data Structures
class ClientConnection
class ClientSession
class ServerMediaSessionIterator
Public Member Functions
void addServerMediaSession (ServerMediaSession *serverMediaSession)
virtual ServerMediaSession * lookupServerMediaSession (char const *streamName, Boolean isFirstLookupInSession=True)
void removeServerMediaSession (ServerMediaSession *serverMediaSession)
void removeServerMediaSession (char const *streamName)
void closeAllClientSessionsForServerMediaSession (ServerMediaSession *serverMediaSession)
void closeAllClientSessionsForServerMediaSession (char const *streamName)
void deleteServerMediaSession (ServerMediaSession *serverMediaSession)
void deleteServerMediaSession (char const *streamName)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
GenericMediaServer (UsageEnvironment &env, int ourSocket, Port ourPort, unsigned reclamationSeconds)
virtual ~GenericMediaServer ()
void cleanup ()
void incomingConnectionHandler ()
void incomingConnectionHandlerOnSocket (int serverSocket)
virtual ClientConnection * createNewClientConnection (int clientSocket, struct sockaddr_in clientAddr)=0
virtual ClientSession * createNewClientSession (u_int32_t sessionId)=0
ClientSession * createNewClientSessionWithId ()
ClientSession * lookupClientSession (u_int32_t sessionId)
ClientSession * lookupClientSession (char const *sessionIdStr)
TaskToken & nextTask ()
Static Protected Member Functions
static int setUpOurSocket (UsageEnvironment &env, Port &ourPort)
static void incomingConnectionHandler (void *, int)
Protected Attributes
int fServerSocket
Port fServerPort
unsigned fReclamationSeconds
Private Attributes
HashTable * fServerMediaSessions
HashTable * fClientConnections
HashTable * fClientSessions
Friends
class ClientConnection
class ClientSession
class ServerMediaSessionIterator
Detailed Description
Definition at line 39 of file GenericMediaServer.hh.
Constructor & Destructor Documentation
GenericMediaServer::GenericMediaServer (UsageEnvironment & env, int ourSocket, Port ourPort, unsigned reclamationSeconds) [protected]
virtual GenericMediaServer::~GenericMediaServer () [protected], [virtual]
Member Function Documentation
void GenericMediaServer::addServerMediaSession (ServerMediaSession * serverMediaSession)
void GenericMediaServer::cleanup () [protected]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
void GenericMediaServer::closeAllClientSessionsForServerMediaSession (ServerMediaSession * serverMediaSession)
void GenericMediaServer::closeAllClientSessionsForServerMediaSession (char const * streamName)
virtual ClientConnection* GenericMediaServer::createNewClientConnection (int clientSocket, struct sockaddr_in clientAddr) [protected], [pure virtual]
Implemented in RTSPServer , and RTSPServerSupportingHTTPStreaming .
virtual ClientSession* GenericMediaServer::createNewClientSession (u_int32_t sessionId) [protected], [pure virtual]
Implemented in RTSPServer .
ClientSession* GenericMediaServer::createNewClientSessionWithId () [protected]
void GenericMediaServer::deleteServerMediaSession (ServerMediaSession * serverMediaSession)
void GenericMediaServer::deleteServerMediaSession (char const * streamName)
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
static void GenericMediaServer::incomingConnectionHandler (void * , int) [static], [protected]
void GenericMediaServer::incomingConnectionHandler () [protected]
void GenericMediaServer::incomingConnectionHandlerOnSocket (int serverSocket) [protected]
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
ClientSession* GenericMediaServer::lookupClientSession (u_int32_t sessionId) [protected]
ClientSession* GenericMediaServer::lookupClientSession (char const * sessionIdStr) [protected]
virtual ServerMediaSession* GenericMediaServer::lookupServerMediaSession (char const * streamName, Boolean isFirstLookupInSession = True) [virtual]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
void GenericMediaServer::removeServerMediaSession (ServerMediaSession * serverMediaSession)
void GenericMediaServer::removeServerMediaSession (char const * streamName)
static int GenericMediaServer::setUpOurSocket (UsageEnvironment & env, Port & ourPort) [static], [protected]
Friends And Related Function Documentation
friend class ClientConnection [friend]
Definition at line 153 of file GenericMediaServer.hh.
friend class ClientSession [friend]
Definition at line 154 of file GenericMediaServer.hh.
friend class ServerMediaSessionIterator [friend]
Definition at line 155 of file GenericMediaServer.hh.
Field Documentation
HashTable* GenericMediaServer::fClientConnections [private]
Definition at line 162 of file GenericMediaServer.hh.
HashTable* GenericMediaServer::fClientSessions [private]
Definition at line 163 of file GenericMediaServer.hh.
unsigned GenericMediaServer::fReclamationSeconds [protected]
Definition at line 158 of file GenericMediaServer.hh.
HashTable* GenericMediaServer::fServerMediaSessions [private]
Definition at line 161 of file GenericMediaServer.hh.
Port GenericMediaServer::fServerPort [protected]
Definition at line 157 of file GenericMediaServer.hh.
Referenced by HandlerServerForREGISTERCommand::serverPortNum().
int GenericMediaServer::fServerSocket [protected]
Definition at line 156 of file GenericMediaServer.hh.
The documentation for this class was generated from the following file:
liveMedia/include/GenericMediaServer.hh