QuickTimeFileSink Class Reference
#include <QuickTimeFileSink.hh>
Public Types
typedef void(afterPlayingFunc) (void *clientData)
Public Member Functions
Boolean startPlaying (afterPlayingFunc *afterFunc, void *afterClientData)
unsigned numActiveSubsessions () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static QuickTimeFileSink * createNew (UsageEnvironment &env, MediaSession &inputSession, char const *outputFileName, unsigned bufferSize=20000, unsigned short movieWidth=240, unsigned short movieHeight=180, unsigned movieFPS=15, Boolean packetLossCompensate=False, Boolean syncStreams=False, Boolean generateHintTracks=False, Boolean generateMP4Format=False)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
QuickTimeFileSink (UsageEnvironment &env, MediaSession &inputSession, char const *outputFileName, unsigned bufferSize, unsigned short movieWidth, unsigned short movieHeight, unsigned movieFPS, Boolean packetLossCompensate, Boolean syncStreams, Boolean generateHintTracks, Boolean generateMP4Format)
virtual ~QuickTimeFileSink ()
virtual void noteRecordedFrame (MediaSubsession &inputSubsession, unsigned packetDataSize, struct timeval const &presentationTime)
TaskToken & nextTask ()
Private Member Functions
Boolean continuePlaying ()
void onSourceClosure1 ()
void completeOutputFile ()
unsigned addWord64 (u_int64_t word)
unsigned addWord (unsigned word)
unsigned addHalfWord (unsigned short halfWord)
unsigned addByte (unsigned char byte)
unsigned addZeroWords (unsigned numWords)
unsigned add4ByteString (char const *str)
unsigned addArbitraryString (char const *str, Boolean oneByteLength=True)
unsigned addAtomHeader (char const *atomName)
unsigned addAtomHeader64 (char const *atomName)
void setWord (int64_t filePosn, unsigned size)
void setWord64 (int64_t filePosn, u_int64_t size)
unsigned movieTimeScale () const
_atom (ftyp)
_atom (moov)
_atom (mvhd)
_atom (iods)
_atom (trak)
_atom (tkhd)
_atom (edts)
_atom (elst)
_atom (tref)
_atom (hint)
_atom (mdia)
_atom (mdhd)
_atom (hdlr)
_atom (minf)
_atom (smhd)
_atom (vmhd)
_atom (gmhd)
_atom (gmin)
unsigned addAtom_hdlr2 ()
_atom (dinf)
_atom (dref)
_atom (alis)
_atom (stbl)
_atom (stsd)
unsigned addAtom_genericMedia ()
unsigned addAtom_soundMediaGeneral ()
_atom (ulaw)
_atom (alaw)
_atom (Qclp)
_atom (wave)
_atom (frma)
_atom (Fclp)
_atom (Hclp)
_atom (mp4a)
_atom (esds)
_atom (srcq)
_atom (h263)
_atom (avc1)
_atom (avcC)
_atom (mp4v)
_atom (rtp)
_atom (tims)
_atom (stts)
_atom (stss)
_atom (stsc)
_atom (stsz)
_atom (co64)
_atom (udta)
_atom (name)
_atom (hnti)
_atom (sdp)
_atom (hinf)
_atom (totl)
_atom (npck)
_atom (tpay)
_atom (trpy)
_atom (nump)
_atom (tpyl)
_atom (dmed)
_atom (dimm)
_atom (drep)
_atom (tmin)
_atom (tmax)
_atom (pmax)
_atom (dmax)
_atom (payt)
unsigned addAtom_dummy ()
Static Private Member Functions
static void afterGettingFrame (void *clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds)
static void onSourceClosure (void *clientData)
static void onRTCPBye (void *clientData)
Private Attributes
MediaSession & fInputSession
FILE * fOutFid
unsigned fBufferSize
Boolean fPacketLossCompensate
Boolean fSyncStreams
Boolean fGenerateMP4Format
struct timeval fNewestSyncTime fFirstDataTime
Boolean fAreCurrentlyBeingPlayed
afterPlayingFunc * fAfterFunc
void * fAfterClientData
unsigned fAppleCreationTime
unsigned fLargestRTPtimestampFrequency
unsigned fNumSubsessions
unsigned fNumSyncedSubsessions
struct timeval fStartTime
Boolean fHaveCompletedOutputFile
unsigned short fMovieWidth
unsigned short fMovieHeight
unsigned fMovieFPS
int64_t fMDATposition
int64_t fMVHD_durationPosn
unsigned fMaxTrackDurationM
class SubsessionIOState * fCurrentIOState
Friends
class SubsessionIOState
Detailed Description
Definition at line 28 of file QuickTimeFileSink.hh.
Member Typedef Documentation
typedef void(QuickTimeFileSink::afterPlayingFunc) (void *clientData)
Definition at line 42 of file QuickTimeFileSink.hh.
Constructor & Destructor Documentation
QuickTimeFileSink::QuickTimeFileSink (UsageEnvironment & env, MediaSession & inputSession, char const * outputFileName, unsigned bufferSize, unsigned short movieWidth, unsigned short movieHeight, unsigned movieFPS, Boolean packetLossCompensate, Boolean syncStreams, Boolean generateHintTracks, Boolean generateMP4Format) [protected]
virtual QuickTimeFileSink::~QuickTimeFileSink () [protected], [virtual]
Member Function Documentation
QuickTimeFileSink::_atom (ftyp) [private]
QuickTimeFileSink::_atom (moov) [private]
QuickTimeFileSink::_atom (mvhd) [private]
QuickTimeFileSink::_atom (iods) [private]
QuickTimeFileSink::_atom (trak) [private]
QuickTimeFileSink::_atom (tkhd) [private]
QuickTimeFileSink::_atom (edts) [private]
QuickTimeFileSink::_atom (elst) [private]
QuickTimeFileSink::_atom (tref) [private]
QuickTimeFileSink::_atom (hint) [private]
QuickTimeFileSink::_atom (mdia) [private]
QuickTimeFileSink::_atom (mdhd) [private]
QuickTimeFileSink::_atom (hdlr) [private]
QuickTimeFileSink::_atom (minf) [private]
QuickTimeFileSink::_atom (smhd) [private]
QuickTimeFileSink::_atom (vmhd) [private]
QuickTimeFileSink::_atom (gmhd) [private]
QuickTimeFileSink::_atom (gmin) [private]
QuickTimeFileSink::_atom (dinf) [private]
QuickTimeFileSink::_atom (dref) [private]
QuickTimeFileSink::_atom (alis) [private]
QuickTimeFileSink::_atom (stbl) [private]
QuickTimeFileSink::_atom (stsd) [private]
QuickTimeFileSink::_atom (ulaw) [private]
QuickTimeFileSink::_atom (alaw) [private]
QuickTimeFileSink::_atom (Qclp) [private]
QuickTimeFileSink::_atom (wave) [private]
QuickTimeFileSink::_atom (frma) [private]
QuickTimeFileSink::_atom (Fclp) [private]
QuickTimeFileSink::_atom (Hclp) [private]
QuickTimeFileSink::_atom (mp4a) [private]
QuickTimeFileSink::_atom (esds) [private]
QuickTimeFileSink::_atom (srcq) [private]
QuickTimeFileSink::_atom (h263) [private]
QuickTimeFileSink::_atom (avc1) [private]
QuickTimeFileSink::_atom (avcC) [private]
QuickTimeFileSink::_atom (mp4v) [private]
QuickTimeFileSink::_atom (rtp) [private]
QuickTimeFileSink::_atom (tims) [private]
QuickTimeFileSink::_atom (stts) [private]
QuickTimeFileSink::_atom (stss) [private]
QuickTimeFileSink::_atom (stsc) [private]
QuickTimeFileSink::_atom (stsz) [private]
QuickTimeFileSink::_atom (co64) [private]
QuickTimeFileSink::_atom (udta) [private]
QuickTimeFileSink::_atom (name) [private]
QuickTimeFileSink::_atom (hnti) [private]
QuickTimeFileSink::_atom (sdp) [private]
QuickTimeFileSink::_atom (hinf) [private]
QuickTimeFileSink::_atom (totl) [private]
QuickTimeFileSink::_atom (npck) [private]
QuickTimeFileSink::_atom (tpay) [private]
QuickTimeFileSink::_atom (trpy) [private]
QuickTimeFileSink::_atom (nump) [private]
QuickTimeFileSink::_atom (tpyl) [private]
QuickTimeFileSink::_atom (dmed) [private]
QuickTimeFileSink::_atom (dimm) [private]
QuickTimeFileSink::_atom (drep) [private]
QuickTimeFileSink::_atom (tmin) [private]
QuickTimeFileSink::_atom (tmax) [private]
QuickTimeFileSink::_atom (pmax) [private]
QuickTimeFileSink::_atom (dmax) [private]
QuickTimeFileSink::_atom (payt) [private]
unsigned QuickTimeFileSink::add4ByteString (char const * str) [private]
unsigned QuickTimeFileSink::addArbitraryString (char const * str, Boolean oneByteLength = True) [private]
unsigned QuickTimeFileSink::addAtom_dummy () [private]
unsigned QuickTimeFileSink::addAtom_genericMedia () [private]
unsigned QuickTimeFileSink::addAtom_hdlr2 () [private]
unsigned QuickTimeFileSink::addAtom_soundMediaGeneral () [private]
unsigned QuickTimeFileSink::addAtomHeader (char const * atomName) [private]
unsigned QuickTimeFileSink::addAtomHeader64 (char const * atomName) [private]
unsigned QuickTimeFileSink::addByte (unsigned char byte) [inline], [private]
Definition at line 95 of file QuickTimeFileSink.hh.
                                       {
    putc(byte, fOutFid);
    return 1;
  }
unsigned QuickTimeFileSink::addHalfWord (unsigned short halfWord) [private]
unsigned QuickTimeFileSink::addWord (unsigned word) [private]
unsigned QuickTimeFileSink::addWord64 (u_int64_t word) [private]
unsigned QuickTimeFileSink::addZeroWords (unsigned numWords) [private]
static void QuickTimeFileSink::afterGettingFrame (void * clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds) [static], [private]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
void QuickTimeFileSink::completeOutputFile () [private]
Boolean QuickTimeFileSink::continuePlaying () [private]
static QuickTimeFileSink* QuickTimeFileSink::createNew (UsageEnvironment & env, MediaSession & inputSession, char const * outputFileName, unsigned bufferSize = 20000, unsigned short movieWidth = 240, unsigned short movieHeight = 180, unsigned movieFPS = 15, Boolean packetLossCompensate = False, Boolean syncStreams = False, Boolean generateHintTracks = False, Boolean generateMP4Format = False) [static]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
unsigned QuickTimeFileSink::movieTimeScale () const [inline], [private]
Definition at line 109 of file QuickTimeFileSink.hh.
References fLargestRTPtimestampFrequency.
{return fLargestRTPtimestampFrequency;}
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
virtual void QuickTimeFileSink::noteRecordedFrame (MediaSubsession & inputSubsession, unsigned packetDataSize, struct timeval const & presentationTime) [protected], [virtual]
unsigned QuickTimeFileSink::numActiveSubsessions () const [inline]
Definition at line 46 of file QuickTimeFileSink.hh.
References fNumSubsessions.
{ return fNumSubsessions; }
static void QuickTimeFileSink::onRTCPBye (void * clientData) [static], [private]
static void QuickTimeFileSink::onSourceClosure (void * clientData) [static], [private]
void QuickTimeFileSink::onSourceClosure1 () [private]
void QuickTimeFileSink::setWord (int64_t filePosn, unsigned size) [private]
void QuickTimeFileSink::setWord64 (int64_t filePosn, u_int64_t size) [private]
Boolean QuickTimeFileSink::startPlaying (afterPlayingFunc * afterFunc, void * afterClientData)
Friends And Related Function Documentation
friend class SubsessionIOState [friend]
Definition at line 73 of file QuickTimeFileSink.hh.
Field Documentation
void* QuickTimeFileSink::fAfterClientData [private]
Definition at line 82 of file QuickTimeFileSink.hh.
afterPlayingFunc* QuickTimeFileSink::fAfterFunc [private]
Definition at line 81 of file QuickTimeFileSink.hh.
unsigned QuickTimeFileSink::fAppleCreationTime [private]
Definition at line 83 of file QuickTimeFileSink.hh.
Boolean QuickTimeFileSink::fAreCurrentlyBeingPlayed [private]
Definition at line 80 of file QuickTimeFileSink.hh.
unsigned QuickTimeFileSink::fBufferSize [private]
Definition at line 76 of file QuickTimeFileSink.hh.
class SubsessionIOState* QuickTimeFileSink::fCurrentIOState [private]
Definition at line 189 of file QuickTimeFileSink.hh.
struct timeval fNewestSyncTime QuickTimeFileSink::fFirstDataTime [private]
Definition at line 79 of file QuickTimeFileSink.hh.
Boolean QuickTimeFileSink::fGenerateMP4Format [private]
Definition at line 78 of file QuickTimeFileSink.hh.
Boolean QuickTimeFileSink::fHaveCompletedOutputFile [private]
Definition at line 87 of file QuickTimeFileSink.hh.
MediaSession& QuickTimeFileSink::fInputSession [private]
Definition at line 74 of file QuickTimeFileSink.hh.
unsigned QuickTimeFileSink::fLargestRTPtimestampFrequency [private]
Definition at line 84 of file QuickTimeFileSink.hh.
Referenced by movieTimeScale().
unsigned QuickTimeFileSink::fMaxTrackDurationM [private]
Definition at line 188 of file QuickTimeFileSink.hh.
int64_t QuickTimeFileSink::fMDATposition [private]
Definition at line 186 of file QuickTimeFileSink.hh.
unsigned QuickTimeFileSink::fMovieFPS [private]
Definition at line 185 of file QuickTimeFileSink.hh.
unsigned short QuickTimeFileSink::fMovieHeight [private]
Definition at line 184 of file QuickTimeFileSink.hh.
unsigned short QuickTimeFileSink::fMovieWidth [private]
Definition at line 184 of file QuickTimeFileSink.hh.
int64_t QuickTimeFileSink::fMVHD_durationPosn [private]
Definition at line 187 of file QuickTimeFileSink.hh.
unsigned QuickTimeFileSink::fNumSubsessions [private]
Definition at line 85 of file QuickTimeFileSink.hh.
Referenced by numActiveSubsessions().
unsigned QuickTimeFileSink::fNumSyncedSubsessions [private]
Definition at line 85 of file QuickTimeFileSink.hh.
FILE* QuickTimeFileSink::fOutFid [private]
Definition at line 75 of file QuickTimeFileSink.hh.
Boolean QuickTimeFileSink::fPacketLossCompensate [private]
Definition at line 77 of file QuickTimeFileSink.hh.
struct timeval QuickTimeFileSink::fStartTime [private]
Definition at line 86 of file QuickTimeFileSink.hh.
Boolean QuickTimeFileSink::fSyncStreams [private]
Definition at line 78 of file QuickTimeFileSink.hh.
The documentation for this class was generated from the following file:
liveMedia/include/QuickTimeFileSink.hh