SIPClient Class Reference
#include <SIPClient.hh>
Public Member Functions
void setProxyServer (unsigned proxyServerAddress, portNumBits proxyServerPortNum)
void setClientStartPortNum (portNumBits clientStartPortNum)
char * invite (char const *url, Authenticator *authenticator=NULL)
char * inviteWithPassword (char const *url, char const *username, char const *password)
Boolean sendACK ()
Boolean sendBYE ()
char const * getInviteSdpReply () const
void setUserAgentString (char const *userAgentName)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static SIPClient * createNew (UsageEnvironment &env, unsigned char desiredAudioRTPPayloadFormat, char const *mimeSubtype=NULL, int verbosityLevel=0, char const *applicationName=NULL)
static Boolean parseSIPURL (UsageEnvironment &env, char const *url, NetAddress &address, portNumBits &portNum)
static Boolean parseSIPURLUsernamePassword (char const *url, char *&username, char *&password)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
virtual ~SIPClient ()
TaskToken & nextTask ()
Private Member Functions
SIPClient (UsageEnvironment &env, unsigned char desiredAudioRTPPayloadFormat, char const *mimeSubtype, int verbosityLevel, char const *applicationName)
void reset ()
char * invite1 (Authenticator *authenticator)
Boolean processURL (char const *url)
Boolean sendINVITE ()
void doInviteStateMachine (unsigned responseCode)
void doInviteStateTerminated (unsigned responseCode)
char * createAuthenticatorString (Authenticator const *authenticator, char const *cmd, char const *url)
Boolean sendRequest (char const *requestString, unsigned requestLength)
unsigned getResponseCode ()
unsigned getResponse (char *&responseBuffer, unsigned responseBufferSize)
Boolean parseResponseCode (char const *line, unsigned &responseCode)
Static Private Member Functions
static void inviteResponseHandler (void *clientData, int mask)
static void timerAHandler (void *clientData)
static void timerBHandler (void *clientData)
static void timerDHandler (void *clientData)
Private Attributes
TaskToken fTimerA
TaskToken fTimerB
TaskToken fTimerD
unsigned const fT1
unsigned fTimerALen
unsigned fTimerACount
unsigned char fDesiredAudioRTPPayloadFormat
char * fMIMESubtype
unsigned fMIMESubtypeSize
int fVerbosityLevel
unsigned fCSeq
char const * fApplicationName
unsigned fApplicationNameSize
char const * fOurAddressStr
unsigned fOurAddressStrSize
portNumBits fOurPortNum
Groupsock * fOurSocket
char * fUserAgentHeaderStr
unsigned fUserAgentHeaderStrLen
char const * fURL
unsigned fURLSize
struct in_addr fServerAddress
portNumBits fServerPortNum
portNumBits fClientStartPortNum
unsigned fCallId
unsigned fFromTag
char const * fToTagStr
unsigned fToTagStrSize
Authenticator fValidAuthenticator
char const * fUserName
unsigned fUserNameSize
char * fInviteSDPDescription
char * fInviteSDPDescriptionReturned
char * fInviteCmd
unsigned fInviteCmdSize
Authenticator * fWorkingAuthenticator
inviteClientState fInviteClientState
char fEventLoopStopFlag
Detailed Description
Definition at line 37 of file SIPClient.hh.
Constructor & Destructor Documentation
virtual SIPClient::~SIPClient () [protected], [virtual]
SIPClient::SIPClient (UsageEnvironment & env, unsigned char desiredAudioRTPPayloadFormat, char const * mimeSubtype, int verbosityLevel, char const * applicationName) [private]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
char* SIPClient::createAuthenticatorString (Authenticator const * authenticator, char const * cmd, char const * url) [private]
static SIPClient* SIPClient::createNew (UsageEnvironment & env, unsigned char desiredAudioRTPPayloadFormat, char const * mimeSubtype = NULL, int verbosityLevel = 0, char const * applicationName = NULL) [static]
void SIPClient::doInviteStateMachine (unsigned responseCode) [private]
void SIPClient::doInviteStateTerminated (unsigned responseCode) [private]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
char const* SIPClient::getInviteSdpReply () const [inline]
Definition at line 70 of file SIPClient.hh.
References fInviteSDPDescriptionReturned.
{ return fInviteSDPDescriptionReturned; }
unsigned SIPClient::getResponse (char *& responseBuffer, unsigned responseBufferSize) [private]
unsigned SIPClient::getResponseCode () [private]
char* SIPClient::invite (char const * url, Authenticator * authenticator = NULL)
char* SIPClient::invite1 (Authenticator * authenticator) [private]
static void SIPClient::inviteResponseHandler (void * clientData, int mask) [static], [private]
char* SIPClient::inviteWithPassword (char const * url, char const * username, char const * password)
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
Boolean SIPClient::parseResponseCode (char const * line, unsigned & responseCode) [private]
static Boolean SIPClient::parseSIPURL (UsageEnvironment & env, char const * url, NetAddress & address, portNumBits & portNum) [static]
static Boolean SIPClient::parseSIPURLUsernamePassword (char const * url, char *& username, char *& password) [static]
Boolean SIPClient::processURL (char const * url) [private]
void SIPClient::reset () [private]
Boolean SIPClient::sendACK ()
Boolean SIPClient::sendBYE ()
Boolean SIPClient::sendINVITE () [private]
Boolean SIPClient::sendRequest (char const * requestString, unsigned requestLength) [private]
void SIPClient::setClientStartPortNum (portNumBits clientStartPortNum) [inline]
Definition at line 48 of file SIPClient.hh.
References fClientStartPortNum.
                                                             {
    fClientStartPortNum = clientStartPortNum;
  }
void SIPClient::setProxyServer (unsigned proxyServerAddress, portNumBits proxyServerPortNum)
void SIPClient::setUserAgentString (char const * userAgentName)
static void SIPClient::timerAHandler (void * clientData) [static], [private]
static void SIPClient::timerBHandler (void * clientData) [static], [private]
static void SIPClient::timerDHandler (void * clientData) [static], [private]
Field Documentation
char const* SIPClient::fApplicationName [private]
Definition at line 118 of file SIPClient.hh.
unsigned SIPClient::fApplicationNameSize [private]
Definition at line 119 of file SIPClient.hh.
unsigned SIPClient::fCallId [private]
Definition at line 133 of file SIPClient.hh.
portNumBits SIPClient::fClientStartPortNum [private]
Definition at line 132 of file SIPClient.hh.
Referenced by setClientStartPortNum().
unsigned SIPClient::fCSeq [private]
Definition at line 117 of file SIPClient.hh.
unsigned char SIPClient::fDesiredAudioRTPPayloadFormat [private]
Definition at line 113 of file SIPClient.hh.
char SIPClient::fEventLoopStopFlag [private]
Definition at line 146 of file SIPClient.hh.
unsigned SIPClient::fFromTag [private]
Definition at line 133 of file SIPClient.hh.
inviteClientState SIPClient::fInviteClientState [private]
Definition at line 145 of file SIPClient.hh.
char* SIPClient::fInviteCmd [private]
Definition at line 142 of file SIPClient.hh.
unsigned SIPClient::fInviteCmdSize [private]
Definition at line 143 of file SIPClient.hh.
char* SIPClient::fInviteSDPDescription [private]
Definition at line 140 of file SIPClient.hh.
char* SIPClient::fInviteSDPDescriptionReturned [private]
Definition at line 141 of file SIPClient.hh.
Referenced by getInviteSdpReply().
char* SIPClient::fMIMESubtype [private]
Definition at line 114 of file SIPClient.hh.
unsigned SIPClient::fMIMESubtypeSize [private]
Definition at line 115 of file SIPClient.hh.
char const* SIPClient::fOurAddressStr [private]
Definition at line 120 of file SIPClient.hh.
unsigned SIPClient::fOurAddressStrSize [private]
Definition at line 121 of file SIPClient.hh.
portNumBits SIPClient::fOurPortNum [private]
Definition at line 122 of file SIPClient.hh.
Groupsock* SIPClient::fOurSocket [private]
Definition at line 123 of file SIPClient.hh.
struct in_addr SIPClient::fServerAddress [private]
Definition at line 130 of file SIPClient.hh.
portNumBits SIPClient::fServerPortNum [private]
Definition at line 131 of file SIPClient.hh.
unsigned const SIPClient::fT1 [private]
Definition at line 99 of file SIPClient.hh.
TaskToken SIPClient::fTimerA [private]
Definition at line 95 of file SIPClient.hh.
unsigned SIPClient::fTimerACount [private]
Definition at line 101 of file SIPClient.hh.
unsigned SIPClient::fTimerALen [private]
Definition at line 100 of file SIPClient.hh.
TaskToken SIPClient::fTimerB [private]
Definition at line 95 of file SIPClient.hh.
TaskToken SIPClient::fTimerD [private]
Definition at line 95 of file SIPClient.hh.
char const* SIPClient::fToTagStr [private]
Definition at line 134 of file SIPClient.hh.
unsigned SIPClient::fToTagStrSize [private]
Definition at line 135 of file SIPClient.hh.
char const* SIPClient::fURL [private]
Definition at line 128 of file SIPClient.hh.
unsigned SIPClient::fURLSize [private]
Definition at line 129 of file SIPClient.hh.
char* SIPClient::fUserAgentHeaderStr [private]
Definition at line 124 of file SIPClient.hh.
unsigned SIPClient::fUserAgentHeaderStrLen [private]
Definition at line 125 of file SIPClient.hh.
char const* SIPClient::fUserName [private]
Definition at line 137 of file SIPClient.hh.
unsigned SIPClient::fUserNameSize [private]
Definition at line 138 of file SIPClient.hh.
Authenticator SIPClient::fValidAuthenticator [private]
Definition at line 136 of file SIPClient.hh.
int SIPClient::fVerbosityLevel [private]
Definition at line 116 of file SIPClient.hh.
Authenticator* SIPClient::fWorkingAuthenticator [private]
Definition at line 144 of file SIPClient.hh.
The documentation for this class was generated from the following file:
liveMedia/include/SIPClient.hh