TaskScheduler Class Reference
#include <UsageEnvironment.hh>
Public Types
typedef void BackgroundHandlerProc(void *clientData, int mask)
Public Member Functions
virtual ~TaskScheduler ()
virtual TaskToken scheduleDelayedTask (int64_t microseconds, TaskFunc *proc, void *clientData)=0
virtual void unscheduleDelayedTask (TaskToken &prevTask)=0
virtual void rescheduleDelayedTask (TaskToken &task, int64_t microseconds, TaskFunc *proc, void *clientData)
virtual void setBackgroundHandling (int socketNum, int conditionSet, BackgroundHandlerProc *handlerProc, void *clientData)=0
void disableBackgroundHandling (int socketNum)
virtual void moveSocketHandling (int oldSocketNum, int newSocketNum)=0
virtual void doEventLoop (char volatile *watchVariable=NULL)=0
virtual EventTriggerId createEventTrigger (TaskFunc *eventHandlerProc)=0
virtual void deleteEventTrigger (EventTriggerId eventTriggerId)=0
virtual void triggerEvent (EventTriggerId eventTriggerId, void *clientData=NULL)=0
void turnOnBackgroundReadHandling (int socketNum, BackgroundHandlerProc *handlerProc, void *clientData)
void turnOffBackgroundReadHandling (int socketNum)
virtual void internalError ()
Protected Member Functions
TaskScheduler ()
Detailed Description
Definition at line 106 of file UsageEnvironment.hh.
Member Typedef Documentation
typedef void TaskScheduler::BackgroundHandlerProc(void *clientData, int mask)
Definition at line 132 of file UsageEnvironment.hh.
Constructor & Destructor Documentation
virtual TaskScheduler::~TaskScheduler () [virtual]
TaskScheduler::TaskScheduler () [protected]
Member Function Documentation
virtual EventTriggerId TaskScheduler::createEventTrigger (TaskFunc * eventHandlerProc) [pure virtual]
Implemented in BasicTaskScheduler0 .
virtual void TaskScheduler::deleteEventTrigger (EventTriggerId eventTriggerId) [pure virtual]
Implemented in BasicTaskScheduler0 .
void TaskScheduler::disableBackgroundHandling (int socketNum) [inline]
Definition at line 139 of file UsageEnvironment.hh.
References NULL, and setBackgroundHandling().
Referenced by turnOffBackgroundReadHandling().
{ setBackgroundHandling(socketNum, 0, NULL, NULL); }
virtual void TaskScheduler::doEventLoop (char volatile * watchVariable = NULL) [pure virtual]
Implemented in BasicTaskScheduler0 .
virtual void TaskScheduler::internalError () [virtual]
virtual void TaskScheduler::moveSocketHandling (int oldSocketNum, int newSocketNum) [pure virtual]
Implemented in BasicTaskScheduler .
virtual void TaskScheduler::rescheduleDelayedTask (TaskToken & task, int64_t microseconds, TaskFunc * proc, void * clientData) [virtual]
virtual TaskToken TaskScheduler::scheduleDelayedTask (int64_t microseconds, TaskFunc * proc, void * clientData) [pure virtual]
Implemented in BasicTaskScheduler0 .
virtual void TaskScheduler::setBackgroundHandling (int socketNum, int conditionSet, BackgroundHandlerProc * handlerProc, void * clientData) [pure virtual]
Implemented in BasicTaskScheduler .
Referenced by disableBackgroundHandling(), and turnOnBackgroundReadHandling().
virtual void TaskScheduler::triggerEvent (EventTriggerId eventTriggerId, void * clientData = NULL) [pure virtual]
Implemented in BasicTaskScheduler0 .
void TaskScheduler::turnOffBackgroundReadHandling (int socketNum) [inline]
Definition at line 164 of file UsageEnvironment.hh.
References disableBackgroundHandling().
{ disableBackgroundHandling(socketNum); }
void TaskScheduler::turnOnBackgroundReadHandling (int socketNum, BackgroundHandlerProc * handlerProc, void * clientData) [inline]
Definition at line 161 of file UsageEnvironment.hh.
References setBackgroundHandling(), and SOCKET_READABLE.
                                                                                                         {
    setBackgroundHandling(socketNum, SOCKET_READABLE, handlerProc, clientData);
  }
virtual void TaskScheduler::unscheduleDelayedTask (TaskToken & prevTask) [pure virtual]
Implemented in BasicTaskScheduler0 .
The documentation for this class was generated from the following file:
UsageEnvironment/include/UsageEnvironment.hh