MediaTranscodingTable Class Reference
#include <MediaTranscodingTable.hh>
Public Member Functions
virtual FramedFilter * lookupTranscoder (MediaSubsession &, char *&outputCodecName)
virtual Boolean weWillTranscode (char const *, char const *)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
MediaTranscodingTable (UsageEnvironment &env)
virtual ~MediaTranscodingTable ()
TaskToken & nextTask ()
Detailed Description
Definition at line 34 of file MediaTranscodingTable.hh.
Constructor & Destructor Documentation
MediaTranscodingTable::MediaTranscodingTable (UsageEnvironment & env) [inline], [protected]
Definition at line 59 of file MediaTranscodingTable.hh.
    : Medium(env) {
  }
virtual MediaTranscodingTable::~MediaTranscodingTable () [inline], [protected], [virtual]
Definition at line 62 of file MediaTranscodingTable.hh.
                                   {
  }
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
virtual FramedFilter* MediaTranscodingTable::lookupTranscoder (MediaSubsession & , char *& outputCodecName) [inline], [virtual]
Definition at line 37 of file MediaTranscodingTable.hh.
References NULL.
                                            {
    // Default implementation: Return NULL (indicating: no transcoding).
    // You would reimplement this virtual function in a subclass to return a new 'transcoding'
    // "FramedFilter" (subclass) object for each ("mediumName","codecName") that you wish to
    // transcode (or return NULL for no transcoding).
    // (Note that "inputCodecDescription" must have a non-NULL "readSource()"; this is used
    // as the input to the new "FramedFilter" (subclass) object.)
    outputCodecName = NULL;
    return NULL;
  }
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
virtual Boolean MediaTranscodingTable::weWillTranscode (char const * , char const *) [inline], [virtual]
Definition at line 49 of file MediaTranscodingTable.hh.
References False.
                                                                {
    // Default implementation: Return False.
    // You would reimplement this in a subclass - returning True for each
    // <mediumName>/<codecName> for which you'll do transcoding.
    // Note: Unlike "lookupTranscoder()", this function does not actually create any 'transcoding'
    // filter objects. (It may be called before "MediaSubsession::initiate()".)
    return False;
  }
The documentation for this class was generated from the following file:
liveMedia/include/MediaTranscodingTable.hh