H263plusVideoStreamParser Class Reference
#include <H263plusVideoStreamParser.hh>
Public Member Functions
H263plusVideoStreamParser (class H263plusVideoStreamFramer *usingSource, FramedSource *inputSource)
virtual ~H263plusVideoStreamParser ()
void registerReadInterest (unsigned char *to, unsigned maxSize)
unsigned parse (u_int64_t &currentDuration)
unsigned numTruncatedBytes () const
virtual void flushInput ()
Protected Types
typedef void(clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime)
Protected Member Functions
void setParseState ()
void saveParserState ()
u_int32_t get4Bytes ()
u_int32_t test4Bytes ()
u_int16_t get2Bytes ()
u_int8_t get1Byte ()
u_int8_t test1Byte ()
void getBytes (u_int8_t *to, unsigned numBytes)
void testBytes (u_int8_t *to, unsigned numBytes)
void skipBytes (unsigned numBytes)
void skipBits (unsigned numBits)
unsigned getBits (unsigned numBits)
unsigned curOffset () const
unsigned & totNumValidBytes ()
Boolean haveSeenEOF () const
unsigned bankSize () const
Protected Attributes
class H263plusVideoStreamFramer * fUsingSource
unsigned char * fTo
unsigned fMaxSize
unsigned char * fStartOfFrame
unsigned char * fSavedTo
unsigned char * fLimit
unsigned fNumTruncatedBytes
unsigned fSavedNumTruncatedBytes
Private Member Functions
int parseH263Frame ()
bool ParseShortHeader (u_int8_t *headerBuffer, H263INFO *outputInfoStruct)
void GetMaxBitrate (MaxBitrate_CTX *ctx, u_int32_t frameSize, u_int8_t frameTRDiff)
u_int64_t CalculateDuration (u_int8_t trDiff)
bool GetWidthAndHeight (u_int8_t fmt, u_int16_t *width, u_int16_t *height)
u_int8_t GetTRDifference (u_int8_t nextTR, u_int8_t currentTR)
virtual void restoreSavedParserState ()
Private Attributes
H263INFO fNextInfo
H263INFO fCurrentInfo
MaxBitrate_CTX fMaxBitrateCtx
char fStates [3][256]
u_int8_t fNextHeader [H263_REQUIRE_HEADER_SIZE_BYTES]
u_int32_t fnextTR
u_int64_t fcurrentPT
Detailed Description
Definition at line 71 of file H263plusVideoStreamParser.hh.
Member Typedef Documentation
typedef void(StreamParser::clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime) [protected], [inherited]
Definition at line 33 of file StreamParser.hh.
Constructor & Destructor Documentation
H263plusVideoStreamParser::H263plusVideoStreamParser (class H263plusVideoStreamFramer * usingSource, FramedSource * inputSource)
virtual H263plusVideoStreamParser::~H263plusVideoStreamParser () [virtual]
Member Function Documentation
unsigned StreamParser::bankSize () const [protected], [inherited]
u_int64_t H263plusVideoStreamParser::CalculateDuration (u_int8_t trDiff) [private]
unsigned StreamParser::curOffset () const [inline], [protected], [inherited]
Definition at line 100 of file StreamParser.hh.
References StreamParser::fCurParserIndex.
{ return fCurParserIndex; }
virtual void StreamParser::flushInput () [virtual], [inherited]
u_int8_t StreamParser::get1Byte () [inline], [protected], [inherited]
Definition at line 72 of file StreamParser.hh.
References StreamParser::curBank(), StreamParser::ensureValidBytes(), StreamParser::fCurParserIndex, and StreamParser::fRemainingUnparsedBits.
Referenced by MPEGVideoStreamParser::saveToNextCode(), and MPEGVideoStreamParser::skipToNextCode().
                      { // byte-aligned
    ensureValidBytes(1);
    fRemainingUnparsedBits = 0;
    return curBank()[fCurParserIndex++];
  }
u_int16_t StreamParser::get2Bytes () [inline], [protected], [inherited]
Definition at line 60 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::nextToParse().
                        {
    ensureValidBytes(2);
    unsigned char const* ptr = nextToParse();
    u_int16_t result = (ptr[0]<<8)|ptr[1];
    fCurParserIndex += 2;
    fRemainingUnparsedBits = 0;
    return result;
  }
u_int32_t StreamParser::get4Bytes () [inline], [protected], [inherited]
Definition at line 46 of file StreamParser.hh.
References StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::test4Bytes().
Referenced by MPEGVideoStreamParser::saveToNextCode(), and MPEGVideoStreamParser::skipToNextCode().
                        { // byte-aligned; returned in big-endian order
    u_int32_t result = test4Bytes();
    fCurParserIndex += 4;
    fRemainingUnparsedBits = 0;
    return result;
  }
unsigned StreamParser::getBits (unsigned numBits) [protected], [inherited]
void StreamParser::getBytes (u_int8_t * to, unsigned numBytes) [inline], [protected], [inherited]
Definition at line 82 of file StreamParser.hh.
References StreamParser::fCurParserIndex, StreamParser::fRemainingUnparsedBits, and StreamParser::testBytes().
                                                 {
    testBytes(to, numBytes);
    fCurParserIndex += numBytes;
    fRemainingUnparsedBits = 0;
  }
void H263plusVideoStreamParser::GetMaxBitrate (MaxBitrate_CTX * ctx, u_int32_t frameSize, u_int8_t frameTRDiff) [private]
u_int8_t H263plusVideoStreamParser::GetTRDifference (u_int8_t nextTR, u_int8_t currentTR) [private]
bool H263plusVideoStreamParser::GetWidthAndHeight (u_int8_t fmt, u_int16_t * width, u_int16_t * height) [private]
Boolean StreamParser::haveSeenEOF () const [inline], [protected], [inherited]
Definition at line 104 of file StreamParser.hh.
References StreamParser::fHaveSeenEOF.
{ return fHaveSeenEOF; }
unsigned H263plusVideoStreamParser::numTruncatedBytes () const [inline]
Definition at line 82 of file H263plusVideoStreamParser.hh.
References fNumTruncatedBytes.
{ return fNumTruncatedBytes; } // The number of truncated bytes (if any)
unsigned H263plusVideoStreamParser::parse (u_int64_t & currentDuration)
int H263plusVideoStreamParser::parseH263Frame () [private]
bool H263plusVideoStreamParser::ParseShortHeader (u_int8_t * headerBuffer, H263INFO * outputInfoStruct) [private]
void H263plusVideoStreamParser::registerReadInterest (unsigned char * to, unsigned maxSize)
virtual void H263plusVideoStreamParser::restoreSavedParserState () [private], [virtual]
Reimplemented from StreamParser .
void StreamParser::saveParserState () [protected], [inherited]
Referenced by MPEGVideoStreamParser::setParseState().
void H263plusVideoStreamParser::setParseState () [protected]
void StreamParser::skipBits (unsigned numBits) [protected], [inherited]
void StreamParser::skipBytes (unsigned numBytes) [inline], [protected], [inherited]
Definition at line 91 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::fCurParserIndex.
                                    {
    ensureValidBytes(numBytes);
    fCurParserIndex += numBytes;
  }
u_int8_t StreamParser::test1Byte () [inline], [protected], [inherited]
Definition at line 77 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
                       { // as above, but doesn't advance ptr
    ensureValidBytes(1);
    return nextToParse()[0];
  }
u_int32_t StreamParser::test4Bytes () [inline], [protected], [inherited]
Definition at line 53 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
Referenced by StreamParser::get4Bytes().
                         { // as above, but doesn't advance ptr
    ensureValidBytes(4);
    unsigned char const* ptr = nextToParse();
    return (ptr[0]<<24)|(ptr[1]<<16)|(ptr[2]<<8)|ptr[3];
  }
void StreamParser::testBytes (u_int8_t * to, unsigned numBytes) [inline], [protected], [inherited]
Definition at line 87 of file StreamParser.hh.
References StreamParser::ensureValidBytes(), and StreamParser::nextToParse().
Referenced by StreamParser::getBytes().
                                                  { // as above, but doesn't advance ptr
    ensureValidBytes(numBytes);
    memmove(to, nextToParse(), numBytes);
  }
unsigned& StreamParser::totNumValidBytes () [inline], [protected], [inherited]
Definition at line 102 of file StreamParser.hh.
References StreamParser::fTotNumValidBytes.
{ return fTotNumValidBytes; }
Field Documentation
H263INFO H263plusVideoStreamParser::fCurrentInfo [private]
Definition at line 117 of file H263plusVideoStreamParser.hh.
u_int64_t H263plusVideoStreamParser::fcurrentPT [private]
Definition at line 123 of file H263plusVideoStreamParser.hh.
unsigned char* H263plusVideoStreamParser::fLimit [protected]
Definition at line 111 of file H263plusVideoStreamParser.hh.
MaxBitrate_CTX H263plusVideoStreamParser::fMaxBitrateCtx [private]
Definition at line 118 of file H263plusVideoStreamParser.hh.
unsigned H263plusVideoStreamParser::fMaxSize [protected]
Definition at line 108 of file H263plusVideoStreamParser.hh.
u_int8_t H263plusVideoStreamParser::fNextHeader[H263_REQUIRE_HEADER_SIZE_BYTES] [private]
Definition at line 120 of file H263plusVideoStreamParser.hh.
H263INFO H263plusVideoStreamParser::fNextInfo [private]
Definition at line 116 of file H263plusVideoStreamParser.hh.
u_int32_t H263plusVideoStreamParser::fnextTR [private]
Definition at line 122 of file H263plusVideoStreamParser.hh.
unsigned H263plusVideoStreamParser::fNumTruncatedBytes [protected]
Definition at line 112 of file H263plusVideoStreamParser.hh.
Referenced by numTruncatedBytes().
unsigned H263plusVideoStreamParser::fSavedNumTruncatedBytes [protected]
Definition at line 113 of file H263plusVideoStreamParser.hh.
unsigned char* H263plusVideoStreamParser::fSavedTo [protected]
Definition at line 110 of file H263plusVideoStreamParser.hh.
unsigned char* H263plusVideoStreamParser::fStartOfFrame [protected]
Definition at line 109 of file H263plusVideoStreamParser.hh.
char H263plusVideoStreamParser::fStates[3][256] [private]
Definition at line 119 of file H263plusVideoStreamParser.hh.
unsigned char* H263plusVideoStreamParser::fTo [protected]
Definition at line 107 of file H263plusVideoStreamParser.hh.
class H263plusVideoStreamFramer* H263plusVideoStreamParser::fUsingSource [protected]
Definition at line 105 of file H263plusVideoStreamParser.hh.
The documentation for this class was generated from the following file:
liveMedia/H263plusVideoStreamParser.hh