StreamParser Class Reference
#include <StreamParser.hh>
Public Member Functions
virtual void flushInput ()
Protected Types
typedef void(clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime)
Protected Member Functions
StreamParser (FramedSource *inputSource, FramedSource::onCloseFunc *onInputCloseFunc, void *onInputCloseClientData, clientContinueFunc *clientContinueFunc, void *clientContinueClientData)
virtual ~StreamParser ()
void saveParserState ()
virtual void restoreSavedParserState ()
u_int32_t get4Bytes ()
u_int32_t test4Bytes ()
u_int16_t get2Bytes ()
u_int8_t get1Byte ()
u_int8_t test1Byte ()
void getBytes (u_int8_t *to, unsigned numBytes)
void testBytes (u_int8_t *to, unsigned numBytes)
void skipBytes (unsigned numBytes)
void skipBits (unsigned numBits)
unsigned getBits (unsigned numBits)
unsigned curOffset () const
unsigned & totNumValidBytes ()
Boolean haveSeenEOF () const
unsigned bankSize () const
Private Member Functions
unsigned char * curBank ()
unsigned char * nextToParse ()
unsigned char * lastParsed ()
void ensureValidBytes (unsigned numBytesNeeded)
void ensureValidBytes1 (unsigned numBytesNeeded)
void afterGettingBytes1 (unsigned numBytesRead, struct timeval presentationTime)
void onInputClosure1 ()
Static Private Member Functions
static void afterGettingBytes (void *clientData, unsigned numBytesRead, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds)
static void onInputClosure (void *clientData)
Private Attributes
FramedSource * fInputSource
FramedSource::onCloseFunc * fClientOnInputCloseFunc
void * fClientOnInputCloseClientData
clientContinueFunc * fClientContinueFunc
void * fClientContinueClientData
unsigned char * fBank [2]
unsigned char fCurBankNum
unsigned char * fCurBank
unsigned fSavedParserIndex
unsigned char fSavedRemainingUnparsedBits
unsigned fCurParserIndex
unsigned char fRemainingUnparsedBits
unsigned fTotNumValidBytes
Boolean fHaveSeenEOF
struct timeval fLastSeenPresentationTime
Detailed Description
Definition at line 28 of file StreamParser.hh.
Member Typedef Documentation
typedef void(StreamParser::clientContinueFunc) (void *clientData, unsigned char *ptr, unsigned size, struct timeval presentationTime) [protected]
Definition at line 33 of file StreamParser.hh.
Constructor & Destructor Documentation
StreamParser::StreamParser (FramedSource * inputSource, FramedSource::onCloseFunc * onInputCloseFunc, void * onInputCloseClientData, clientContinueFunc * clientContinueFunc, void * clientContinueClientData) [protected]
virtual StreamParser::~StreamParser () [protected], [virtual]
Member Function Documentation
static void StreamParser::afterGettingBytes (void * clientData, unsigned numBytesRead, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds) [static], [private]
void StreamParser::afterGettingBytes1 (unsigned numBytesRead, struct timeval presentationTime) [private]
unsigned StreamParser::bankSize () const [protected]
unsigned char* StreamParser::curBank () [inline], [private]
Definition at line 109 of file StreamParser.hh.
References fCurBank.
Referenced by get1Byte(), lastParsed(), and nextToParse().
{ return fCurBank; }
unsigned StreamParser::curOffset () const [inline], [protected]
Definition at line 100 of file StreamParser.hh.
References fCurParserIndex.
{ return fCurParserIndex; }
void StreamParser::ensureValidBytes (unsigned numBytesNeeded) [inline], [private]
Definition at line 114 of file StreamParser.hh.
References ensureValidBytes1(), fCurParserIndex, and fTotNumValidBytes.
Referenced by get1Byte(), get2Bytes(), skipBytes(), test1Byte(), test4Bytes(), and testBytes().
                                                 {
    // common case: inlined:
    if (fCurParserIndex + numBytesNeeded <= fTotNumValidBytes) return;
    ensureValidBytes1(numBytesNeeded);
  }
void StreamParser::ensureValidBytes1 (unsigned numBytesNeeded) [private]
Referenced by ensureValidBytes().
virtual void StreamParser::flushInput () [virtual]
u_int8_t StreamParser::get1Byte () [inline], [protected]
Definition at line 72 of file StreamParser.hh.
References curBank(), ensureValidBytes(), fCurParserIndex, and fRemainingUnparsedBits.
Referenced by MPEGVideoStreamParser::saveToNextCode(), and MPEGVideoStreamParser::skipToNextCode().
                      { // byte-aligned
    ensureValidBytes(1);
    fRemainingUnparsedBits = 0;
    return curBank()[fCurParserIndex++];
  }
u_int16_t StreamParser::get2Bytes () [inline], [protected]
Definition at line 60 of file StreamParser.hh.
References ensureValidBytes(), fCurParserIndex, fRemainingUnparsedBits, and nextToParse().
                        {
    ensureValidBytes(2);
    unsigned char const* ptr = nextToParse();
    u_int16_t result = (ptr[0]<<8)|ptr[1];
    fCurParserIndex += 2;
    fRemainingUnparsedBits = 0;
    return result;
  }
u_int32_t StreamParser::get4Bytes () [inline], [protected]
Definition at line 46 of file StreamParser.hh.
References fCurParserIndex, fRemainingUnparsedBits, and test4Bytes().
Referenced by MPEGVideoStreamParser::saveToNextCode(), and MPEGVideoStreamParser::skipToNextCode().
                        { // byte-aligned; returned in big-endian order
    u_int32_t result = test4Bytes();
    fCurParserIndex += 4;
    fRemainingUnparsedBits = 0;
    return result;
  }
unsigned StreamParser::getBits (unsigned numBits) [protected]
void StreamParser::getBytes (u_int8_t * to, unsigned numBytes) [inline], [protected]
Definition at line 82 of file StreamParser.hh.
References fCurParserIndex, fRemainingUnparsedBits, and testBytes().
                                                 {
    testBytes(to, numBytes);
    fCurParserIndex += numBytes;
    fRemainingUnparsedBits = 0;
  }
Boolean StreamParser::haveSeenEOF () const [inline], [protected]
Definition at line 104 of file StreamParser.hh.
References fHaveSeenEOF.
{ return fHaveSeenEOF; }
unsigned char* StreamParser::lastParsed () [inline], [private]
Definition at line 111 of file StreamParser.hh.
References curBank(), and fCurParserIndex.
{ return &curBank()[fCurParserIndex-1]; }
unsigned char* StreamParser::nextToParse () [inline], [private]
Definition at line 110 of file StreamParser.hh.
References curBank(), and fCurParserIndex.
Referenced by get2Bytes(), test1Byte(), test4Bytes(), and testBytes().
{ return &curBank()[fCurParserIndex]; }
static void StreamParser::onInputClosure (void * clientData) [static], [private]
void StreamParser::onInputClosure1 () [private]
virtual void StreamParser::restoreSavedParserState () [protected], [virtual]
Reimplemented in MPEGVideoStreamParser , H263plusVideoStreamParser , and MatroskaFileParser .
void StreamParser::saveParserState () [protected]
Referenced by MPEGVideoStreamParser::setParseState().
void StreamParser::skipBits (unsigned numBits) [protected]
void StreamParser::skipBytes (unsigned numBytes) [inline], [protected]
Definition at line 91 of file StreamParser.hh.
References ensureValidBytes(), and fCurParserIndex.
                                    {
    ensureValidBytes(numBytes);
    fCurParserIndex += numBytes;
  }
u_int8_t StreamParser::test1Byte () [inline], [protected]
Definition at line 77 of file StreamParser.hh.
References ensureValidBytes(), and nextToParse().
                       { // as above, but doesn't advance ptr
    ensureValidBytes(1);
    return nextToParse()[0];
  }
u_int32_t StreamParser::test4Bytes () [inline], [protected]
Definition at line 53 of file StreamParser.hh.
References ensureValidBytes(), and nextToParse().
Referenced by get4Bytes().
                         { // as above, but doesn't advance ptr
    ensureValidBytes(4);
    unsigned char const* ptr = nextToParse();
    return (ptr[0]<<24)|(ptr[1]<<16)|(ptr[2]<<8)|ptr[3];
  }
void StreamParser::testBytes (u_int8_t * to, unsigned numBytes) [inline], [protected]
Definition at line 87 of file StreamParser.hh.
References ensureValidBytes(), and nextToParse().
Referenced by getBytes().
                                                  { // as above, but doesn't advance ptr
    ensureValidBytes(numBytes);
    memmove(to, nextToParse(), numBytes);
  }
unsigned& StreamParser::totNumValidBytes () [inline], [protected]
Definition at line 102 of file StreamParser.hh.
References fTotNumValidBytes.
{ return fTotNumValidBytes; }
Field Documentation
unsigned char* StreamParser::fBank[2] [private]
Definition at line 139 of file StreamParser.hh.
void* StreamParser::fClientContinueClientData [private]
Definition at line 136 of file StreamParser.hh.
clientContinueFunc* StreamParser::fClientContinueFunc [private]
Definition at line 135 of file StreamParser.hh.
void* StreamParser::fClientOnInputCloseClientData [private]
Definition at line 134 of file StreamParser.hh.
FramedSource::onCloseFunc* StreamParser::fClientOnInputCloseFunc [private]
Definition at line 133 of file StreamParser.hh.
unsigned char* StreamParser::fCurBank [private]
Definition at line 141 of file StreamParser.hh.
Referenced by curBank().
unsigned char StreamParser::fCurBankNum [private]
Definition at line 140 of file StreamParser.hh.
unsigned StreamParser::fCurParserIndex [private]
Definition at line 148 of file StreamParser.hh.
Referenced by curOffset(), ensureValidBytes(), get1Byte(), get2Bytes(), get4Bytes(), getBytes(), lastParsed(), nextToParse(), and skipBytes().
Boolean StreamParser::fHaveSeenEOF [private]
Definition at line 155 of file StreamParser.hh.
Referenced by haveSeenEOF().
FramedSource* StreamParser::fInputSource [private]
Definition at line 132 of file StreamParser.hh.
struct timeval StreamParser::fLastSeenPresentationTime [private]
Definition at line 157 of file StreamParser.hh.
unsigned char StreamParser::fRemainingUnparsedBits [private]
Definition at line 149 of file StreamParser.hh.
Referenced by get1Byte(), get2Bytes(), get4Bytes(), and getBytes().
unsigned StreamParser::fSavedParserIndex [private]
Definition at line 144 of file StreamParser.hh.
unsigned char StreamParser::fSavedRemainingUnparsedBits [private]
Definition at line 145 of file StreamParser.hh.
unsigned StreamParser::fTotNumValidBytes [private]
Definition at line 152 of file StreamParser.hh.
Referenced by ensureValidBytes(), and totNumValidBytes().
The documentation for this class was generated from the following file:
liveMedia/StreamParser.hh