BitVector Class Reference
#include <BitVector.hh>
Public Member Functions
BitVector (unsigned char *baseBytePtr, unsigned baseBitOffset, unsigned totNumBits)
void setup (unsigned char *baseBytePtr, unsigned baseBitOffset, unsigned totNumBits)
void putBits (unsigned from, unsigned numBits)
void put1Bit (unsigned bit)
unsigned getBits (unsigned numBits)
unsigned get1Bit ()
Boolean get1BitBoolean ()
void skipBits (unsigned numBits)
unsigned curBitIndex () const
unsigned totNumBits () const
unsigned numBitsRemaining () const
unsigned get_expGolomb ()
Private Attributes
unsigned char * fBaseBytePtr
unsigned fBaseBitOffset
unsigned fTotNumBits
unsigned fCurBitIndex
Detailed Description
Definition at line 28 of file BitVector.hh.
Constructor & Destructor Documentation
BitVector::BitVector (unsigned char * baseBytePtr, unsigned baseBitOffset, unsigned totNumBits)
Member Function Documentation
unsigned BitVector::curBitIndex () const [inline]
Definition at line 47 of file BitVector.hh.
References fCurBitIndex.
{ return fCurBitIndex; }
unsigned BitVector::get1Bit ()
Referenced by MP3FrameParams::get1Bit(), and get1BitBoolean().
Boolean BitVector::get1BitBoolean () [inline]
Definition at line 43 of file BitVector.hh.
References get1Bit().
{ return get1Bit() != 0; }
unsigned BitVector::get_expGolomb ()
unsigned BitVector::getBits (unsigned numBits)
Referenced by MP3FrameParams::getBits().
unsigned BitVector::numBitsRemaining () const [inline]
Definition at line 49 of file BitVector.hh.
References fCurBitIndex, and fTotNumBits.
{ return fTotNumBits - fCurBitIndex; }
void BitVector::put1Bit (unsigned bit)
void BitVector::putBits (unsigned from, unsigned numBits)
void BitVector::setup (unsigned char * baseBytePtr, unsigned baseBitOffset, unsigned totNumBits)
Referenced by MP3FrameParams::setBytePointer().
void BitVector::skipBits (unsigned numBits)
unsigned BitVector::totNumBits () const [inline]
Definition at line 48 of file BitVector.hh.
References fTotNumBits.
{ return fTotNumBits; }
Field Documentation
unsigned BitVector::fBaseBitOffset [private]
Definition at line 56 of file BitVector.hh.
unsigned char* BitVector::fBaseBytePtr [private]
Definition at line 55 of file BitVector.hh.
unsigned BitVector::fCurBitIndex [private]
Definition at line 58 of file BitVector.hh.
Referenced by curBitIndex(), and numBitsRemaining().
unsigned BitVector::fTotNumBits [private]
Definition at line 57 of file BitVector.hh.
Referenced by numBitsRemaining(), and totNumBits().
The documentation for this class was generated from the following file:
liveMedia/include/BitVector.hh