SimpleRTPSink Class Reference
#include <SimpleRTPSink.hh>
Public Types
typedef void(onSendErrorFunc) (void *clientData)
typedef void(afterPlayingFunc) (void *clientData)
Public Member Functions
void setMBitOnNextPacket ()
void setPacketSizes (unsigned preferredPacketSize, unsigned maxPacketSize)
void setOnSendErrorFunc (onSendErrorFunc *onSendErrorFunc, void *onSendErrorFuncData)
virtual void stopPlaying ()
Groupsock const & groupsockBeingUsed () const
Groupsock & groupsockBeingUsed ()
unsigned char rtpPayloadType () const
unsigned rtpTimestampFrequency () const
void setRTPTimestampFrequency (unsigned freq)
char const * rtpPayloadFormatName () const
unsigned numChannels () const
virtual char * rtpmapLine () const
virtual char const * auxSDPLine ()
u_int16_t currentSeqNo () const
u_int32_t presetNextTimestamp ()
RTPTransmissionStatsDB & transmissionStatsDB () const
Boolean nextTimestampHasBeenPreset () const
Boolean & enableRTCPReports ()
void getTotalBitrate (unsigned &outNumBytes, double &outElapsedTime)
struct timeval const & creationTime () const
struct timeval const & initialPresentationTime () const
struct timeval const & mostRecentPresentationTime () const
void resetPresentationTimes ()
void setStreamSocket (int sockNum, unsigned char streamChannelId)
void addStreamSocket (int sockNum, unsigned char streamChannelId)
void removeStreamSocket (int sockNum, unsigned char streamChannelId)
unsigned & estimatedBitrate ()
u_int32_t SSRC () const
Boolean startPlaying (MediaSource &source, afterPlayingFunc *afterFunc, void *afterClientData)
FramedSource * source () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static SimpleRTPSink * createNew (UsageEnvironment &env, Groupsock *RTPgs, unsigned char rtpPayloadFormat, unsigned rtpTimestampFrequency, char const *sdpMediaTypeString, char const *rtpPayloadFormatName, unsigned numChannels=1, Boolean allowMultipleFramesPerPacket=True, Boolean doNormalMBitRule=True)
static Boolean lookupByName (UsageEnvironment &env, char const *sinkName, RTPSink *&resultSink)
static Boolean lookupByName (UsageEnvironment &env, char const *sinkName, MediaSink *&resultSink)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
SimpleRTPSink (UsageEnvironment &env, Groupsock *RTPgs, unsigned char rtpPayloadFormat, unsigned rtpTimestampFrequency, char const *sdpMediaTypeString, char const *rtpPayloadFormatName, unsigned numChannels, Boolean allowMultipleFramesPerPacket, Boolean doNormalMBitRule)
virtual ~SimpleRTPSink ()
virtual void doSpecialFrameHandling (unsigned fragmentationOffset, unsigned char *frameStart, unsigned numBytesInFrame, struct timeval framePresentationTime, unsigned numRemainingBytes)
virtual Boolean frameCanAppearAfterPacketStart (unsigned char const *frameStart, unsigned numBytesInFrame) const
virtual char const * sdpMediaType () const
virtual Boolean allowFragmentationAfterStart () const
virtual Boolean allowOtherFramesAfterLastFragment () const
virtual unsigned specialHeaderSize () const
virtual unsigned frameSpecificHeaderSize () const
virtual unsigned computeOverflowForNewFrame (unsigned newFrameSize) const
Boolean isFirstPacket () const
Boolean isFirstFrameInPacket () const
unsigned curFragmentationOffset () const
void setMarkerBit ()
void setTimestamp (struct timeval framePresentationTime)
void setSpecialHeaderWord (unsigned word, unsigned wordPosition=0)
void setSpecialHeaderBytes (unsigned char const *bytes, unsigned numBytes, unsigned bytePosition=0)
void setFrameSpecificHeaderWord (unsigned word, unsigned wordPosition=0)
void setFrameSpecificHeaderBytes (unsigned char const *bytes, unsigned numBytes, unsigned bytePosition=0)
void setFramePadding (unsigned numPaddingBytes)
unsigned numFramesUsedSoFar () const
unsigned ourMaxPacketSize () const
virtual Boolean continuePlaying ()
u_int32_t convertToRTPTimestamp (struct timeval tv)
unsigned packetCount () const
unsigned octetCount () const
virtual Boolean sourceIsCompatibleWithUs (MediaSource &source)
void onSourceClosure ()
TaskToken & nextTask ()
Static Protected Member Functions
static void onSourceClosure (void *clientData)
Protected Attributes
RTPInterface fRTPInterface
unsigned char fRTPPayloadType
unsigned fPacketCount
unsigned fOctetCount
unsigned fTotalOctetCount
struct timeval fTotalOctetCountStartTime fInitialPresentationTime fMostRecentPresentationTime
u_int32_t fCurrentTimestamp
u_int16_t fSeqNo
FramedSource * fSource
Private Attributes
char const * fSDPMediaTypeString
Boolean fAllowMultipleFramesPerPacket
Boolean fSetMBitOnLastFrames
Boolean fSetMBitOnNextPacket
Detailed Description
Definition at line 29 of file SimpleRTPSink.hh.
Member Typedef Documentation
typedef void(MediaSink::afterPlayingFunc) (void *clientData) [inherited]
Definition at line 33 of file MediaSink.hh.
typedef void(MultiFramedRTPSink::onSendErrorFunc) (void *clientData) [inherited]
Definition at line 33 of file MultiFramedRTPSink.hh.
Constructor & Destructor Documentation
SimpleRTPSink::SimpleRTPSink (UsageEnvironment & env, Groupsock * RTPgs, unsigned char rtpPayloadFormat, unsigned rtpTimestampFrequency, char const * sdpMediaTypeString, char const * rtpPayloadFormatName, unsigned numChannels, Boolean allowMultipleFramesPerPacket, Boolean doNormalMBitRule) [protected]
virtual SimpleRTPSink::~SimpleRTPSink () [protected], [virtual]
Member Function Documentation
void RTPSink::addStreamSocket (int sockNum, unsigned char streamChannelId) [inline], [inherited]
Definition at line 81 of file RTPSink.hh.
References RTPInterface::addStreamSocket(), and RTPSink::fRTPInterface.
                                                                   {
    fRTPInterface.addStreamSocket(sockNum, streamChannelId);
  }
virtual Boolean MultiFramedRTPSink::allowFragmentationAfterStart () const [protected], [virtual], [inherited]
Reimplemented in MPEG4ESVideoRTPSink , and MPEG1or2VideoRTPSink .
virtual Boolean MultiFramedRTPSink::allowOtherFramesAfterLastFragment () const [protected], [virtual], [inherited]
virtual char const* RTPSink::auxSDPLine () [virtual], [inherited]
Reimplemented in MPEG4GenericRTPSink , MPEG4LATMAudioRTPSink , MPEG4ESVideoRTPSink , AMRAudioRTPSink , VorbisAudioRTPSink , H265VideoRTPSink , TheoraVideoRTPSink , H264VideoRTPSink , and DVVideoRTPSink .
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
virtual unsigned MultiFramedRTPSink::computeOverflowForNewFrame (unsigned newFrameSize) const [protected], [virtual], [inherited]
Reimplemented in DVVideoRTPSink .
virtual Boolean MultiFramedRTPSink::continuePlaying () [protected], [virtual], [inherited]
Implements MediaSink .
Reimplemented in T140TextRTPSink , and H264or5VideoRTPSink .
u_int32_t RTPSink::convertToRTPTimestamp (struct timeval tv) [protected], [inherited]
static SimpleRTPSink* SimpleRTPSink::createNew (UsageEnvironment & env, Groupsock * RTPgs, unsigned char rtpPayloadFormat, unsigned rtpTimestampFrequency, char const * sdpMediaTypeString, char const * rtpPayloadFormatName, unsigned numChannels = 1, Boolean allowMultipleFramesPerPacket = True, Boolean doNormalMBitRule = True) [static]
struct timeval const& RTPSink::creationTime () const [inline], [inherited]
Definition at line 72 of file RTPSink.hh.
References RTPSink::fCreationTime.
{ return fCreationTime; }
unsigned MultiFramedRTPSink::curFragmentationOffset () const [inline], [protected], [inherited]
Definition at line 79 of file MultiFramedRTPSink.hh.
References MultiFramedRTPSink::fCurFragmentationOffset.
{ return fCurFragmentationOffset; }
u_int16_t RTPSink::currentSeqNo () const [inline], [inherited]
Definition at line 56 of file RTPSink.hh.
References RTPSink::fSeqNo.
{ return fSeqNo; }
virtual void SimpleRTPSink::doSpecialFrameHandling (unsigned fragmentationOffset, unsigned char * frameStart, unsigned numBytesInFrame, struct timeval framePresentationTime, unsigned numRemainingBytes) [protected], [virtual]
Reimplemented from MultiFramedRTPSink .
Boolean& RTPSink::enableRTCPReports () [inline], [inherited]
Definition at line 66 of file RTPSink.hh.
References RTPSink::fEnableRTCPReports.
{ return fEnableRTCPReports; }
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
unsigned& RTPSink::estimatedBitrate () [inline], [inherited]
Definition at line 87 of file RTPSink.hh.
References RTPSink::fEstimatedBitrate.
{ return fEstimatedBitrate; } // kbps; usually 0 (i.e., unset)
virtual Boolean SimpleRTPSink::frameCanAppearAfterPacketStart (unsigned char const * frameStart, unsigned numBytesInFrame) const [protected], [virtual]
Reimplemented from MultiFramedRTPSink .
virtual unsigned MultiFramedRTPSink::frameSpecificHeaderSize () const [protected], [virtual], [inherited]
Reimplemented in VorbisAudioRTPSink .
void RTPSink::getTotalBitrate (unsigned & outNumBytes, double & outElapsedTime) [inherited]
Groupsock const& RTPSink::groupsockBeingUsed () const [inline], [inherited]
Definition at line 39 of file RTPSink.hh.
References RTPSink::fRTPInterface, and RTPInterface::gs().
{ return *(fRTPInterface.gs()); }
Groupsock& RTPSink::groupsockBeingUsed () [inline], [inherited]
Definition at line 40 of file RTPSink.hh.
References RTPSink::fRTPInterface, and RTPInterface::gs().
{ return *(fRTPInterface.gs()); }
struct timeval const& RTPSink::initialPresentationTime () const [inline], [inherited]
Definition at line 73 of file RTPSink.hh.
{ return fInitialPresentationTime; }
Boolean MultiFramedRTPSink::isFirstFrameInPacket () const [inline], [protected], [inherited]
Definition at line 78 of file MultiFramedRTPSink.hh.
References MultiFramedRTPSink::fNumFramesUsedSoFar.
{ return fNumFramesUsedSoFar == 0; }
Boolean MultiFramedRTPSink::isFirstPacket () const [inline], [protected], [inherited]
Definition at line 77 of file MultiFramedRTPSink.hh.
References MultiFramedRTPSink::fIsFirstPacket.
{ return fIsFirstPacket; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean MediaSink::lookupByName (UsageEnvironment & env, char const * sinkName, MediaSink *& resultSink) [static], [inherited]
static Boolean RTPSink::lookupByName (UsageEnvironment & env, char const * sinkName, RTPSink *& resultSink) [static], [inherited]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
struct timeval const& RTPSink::mostRecentPresentationTime () const [inline], [inherited]
Definition at line 74 of file RTPSink.hh.
References RTPSink::fMostRecentPresentationTime.
{ return fMostRecentPresentationTime; }
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
Boolean RTPSink::nextTimestampHasBeenPreset () const [inline], [inherited]
Definition at line 65 of file RTPSink.hh.
References RTPSink::fNextTimestampHasBeenPreset.
{ return fNextTimestampHasBeenPreset; }
unsigned RTPSink::numChannels () const [inline], [inherited]
Definition at line 49 of file RTPSink.hh.
References RTPSink::fNumChannels.
{ return fNumChannels; }
unsigned MultiFramedRTPSink::numFramesUsedSoFar () const [inline], [protected], [inherited]
Definition at line 91 of file MultiFramedRTPSink.hh.
References MultiFramedRTPSink::fNumFramesUsedSoFar.
{ return fNumFramesUsedSoFar; }
unsigned RTPSink::octetCount () const [inline], [protected], [inherited]
Definition at line 107 of file RTPSink.hh.
References RTPSink::fOctetCount.
{return fOctetCount;}
static void MediaSink::onSourceClosure (void * clientData) [static], [protected], [inherited]
void MediaSink::onSourceClosure () [protected], [inherited]
unsigned MultiFramedRTPSink::ourMaxPacketSize () const [inline], [protected], [inherited]
Definition at line 92 of file MultiFramedRTPSink.hh.
References MultiFramedRTPSink::fOurMaxPacketSize.
{ return fOurMaxPacketSize; }
unsigned RTPSink::packetCount () const [inline], [protected], [inherited]
Definition at line 106 of file RTPSink.hh.
References RTPSink::fPacketCount.
{return fPacketCount;}
u_int32_t RTPSink::presetNextTimestamp () [inherited]
void RTPSink::removeStreamSocket (int sockNum, unsigned char streamChannelId) [inline], [inherited]
Definition at line 84 of file RTPSink.hh.
References RTPSink::fRTPInterface, and RTPInterface::removeStreamSocket().
                                                                      {
    fRTPInterface.removeStreamSocket(sockNum, streamChannelId);
  }
void RTPSink::resetPresentationTimes () [inherited]
virtual char* RTPSink::rtpmapLine () const [virtual], [inherited]
char const* RTPSink::rtpPayloadFormatName () const [inline], [inherited]
Definition at line 47 of file RTPSink.hh.
References RTPSink::fRTPPayloadFormatName.
{return fRTPPayloadFormatName;}
unsigned char RTPSink::rtpPayloadType () const [inline], [inherited]
Definition at line 42 of file RTPSink.hh.
References RTPSink::fRTPPayloadType.
{ return fRTPPayloadType; }
unsigned RTPSink::rtpTimestampFrequency () const [inline], [inherited]
Definition at line 43 of file RTPSink.hh.
References RTPSink::fTimestampFrequency.
{ return fTimestampFrequency; }
virtual char const* SimpleRTPSink::sdpMediaType () const [protected], [virtual]
Reimplemented from RTPSink .
void MultiFramedRTPSink::setFramePadding (unsigned numPaddingBytes) [protected], [inherited]
void MultiFramedRTPSink::setFrameSpecificHeaderBytes (unsigned char const * bytes, unsigned numBytes, unsigned bytePosition = 0) [protected], [inherited]
void MultiFramedRTPSink::setFrameSpecificHeaderWord (unsigned word, unsigned wordPosition = 0) [protected], [inherited]
void MultiFramedRTPSink::setMarkerBit () [protected], [inherited]
void SimpleRTPSink::setMBitOnNextPacket () [inline]
Definition at line 44 of file SimpleRTPSink.hh.
References fSetMBitOnNextPacket, and True.
{ fSetMBitOnNextPacket = True; } // hack for optionally setting the RTP 'M' bit from outside the class
void MultiFramedRTPSink::setOnSendErrorFunc (onSendErrorFunc * onSendErrorFunc, void * onSendErrorFuncData) [inline], [inherited]
Definition at line 34 of file MultiFramedRTPSink.hh.
References MultiFramedRTPSink::fOnSendErrorData, and MultiFramedRTPSink::fOnSendErrorFunc.
                                                                                       {
    // Can be used to set a callback function to be called if there's an error sending RTP packets on our
       socket.
    fOnSendErrorFunc = onSendErrorFunc;
    fOnSendErrorData = onSendErrorFuncData;
  }
void MultiFramedRTPSink::setPacketSizes (unsigned preferredPacketSize, unsigned maxPacketSize) [inherited]
void RTPSink::setRTPTimestampFrequency (unsigned freq) [inline], [inherited]
Definition at line 44 of file RTPSink.hh.
References RTPSink::fTimestampFrequency.
                                               {
    fTimestampFrequency = freq;
  }
void MultiFramedRTPSink::setSpecialHeaderBytes (unsigned char const * bytes, unsigned numBytes, unsigned bytePosition = 0) [protected], [inherited]
void MultiFramedRTPSink::setSpecialHeaderWord (unsigned word, unsigned wordPosition = 0) [protected], [inherited]
void RTPSink::setStreamSocket (int sockNum, unsigned char streamChannelId) [inline], [inherited]
Definition at line 78 of file RTPSink.hh.
References RTPSink::fRTPInterface, and RTPInterface::setStreamSocket().
                                                                   {
    fRTPInterface.setStreamSocket(sockNum, streamChannelId);
  }
void MultiFramedRTPSink::setTimestamp (struct timeval framePresentationTime) [protected], [inherited]
FramedSource* MediaSink::source () const [inline], [inherited]
Definition at line 42 of file MediaSink.hh.
References MediaSink::fSource.
{return fSource;}
virtual Boolean MediaSink::sourceIsCompatibleWithUs (MediaSource & source) [protected], [virtual], [inherited]
Reimplemented in H265VideoRTPSink , H264VideoRTPSink , AMRAudioRTPSink , MPEG4ESVideoRTPSink , DVVideoRTPSink , AMRAudioFileSink , JPEGVideoRTPSink , and MPEG1or2VideoRTPSink .
virtual unsigned MultiFramedRTPSink::specialHeaderSize () const [protected], [virtual], [inherited]
Reimplemented in VorbisAudioRTPSink , TheoraVideoRTPSink , AMRAudioRTPSink , MPEG4GenericRTPSink , AC3AudioRTPSink , H263plusVideoRTPSink , MPEG1or2VideoRTPSink , JPEGVideoRTPSink , MP3ADURTPSink , VP8VideoRTPSink , VP9VideoRTPSink , and MPEG1or2AudioRTPSink .
u_int32_t RTPSink::SSRC () const [inline], [inherited]
Definition at line 89 of file RTPSink.hh.
References RTPSink::fSSRC.
{return fSSRC;}
Boolean MediaSink::startPlaying (MediaSource & source, afterPlayingFunc * afterFunc, void * afterClientData) [inherited]
virtual void MultiFramedRTPSink::stopPlaying () [virtual], [inherited]
Reimplemented from MediaSink .
RTPTransmissionStatsDB& RTPSink::transmissionStatsDB () const [inline], [inherited]
Definition at line 61 of file RTPSink.hh.
References RTPSink::fTransmissionStatsDB.
                                                      {
    return *fTransmissionStatsDB;
  }
Field Documentation
Boolean SimpleRTPSink::fAllowMultipleFramesPerPacket [private]
Definition at line 72 of file SimpleRTPSink.hh.
u_int32_t RTPSink::fCurrentTimestamp [protected], [inherited]
Definition at line 114 of file RTPSink.hh.
struct timeval fTotalOctetCountStartTime fInitialPresentationTime RTPSink::fMostRecentPresentationTime [protected], [inherited]
Definition at line 113 of file RTPSink.hh.
Referenced by RTPSink::mostRecentPresentationTime().
unsigned RTPSink::fOctetCount [protected], [inherited]
Definition at line 112 of file RTPSink.hh.
Referenced by RTPSink::octetCount().
unsigned RTPSink::fPacketCount [protected], [inherited]
Definition at line 112 of file RTPSink.hh.
Referenced by RTPSink::packetCount().
RTPInterface RTPSink::fRTPInterface [protected], [inherited]
Definition at line 110 of file RTPSink.hh.
Referenced by RTPSink::addStreamSocket(), RTPSink::groupsockBeingUsed(), RTPSink::removeStreamSocket(), and RTPSink::setStreamSocket().
unsigned char RTPSink::fRTPPayloadType [protected], [inherited]
Definition at line 111 of file RTPSink.hh.
Referenced by RTPSink::rtpPayloadType().
char const* SimpleRTPSink::fSDPMediaTypeString [private]
Definition at line 71 of file SimpleRTPSink.hh.
u_int16_t RTPSink::fSeqNo [protected], [inherited]
Definition at line 115 of file RTPSink.hh.
Referenced by RTPSink::currentSeqNo().
Boolean SimpleRTPSink::fSetMBitOnLastFrames [private]
Definition at line 73 of file SimpleRTPSink.hh.
Boolean SimpleRTPSink::fSetMBitOnNextPacket [private]
Definition at line 73 of file SimpleRTPSink.hh.
Referenced by setMBitOnNextPacket().
FramedSource* MediaSink::fSource [protected], [inherited]
Definition at line 58 of file MediaSink.hh.
Referenced by MediaSink::source().
unsigned RTPSink::fTotalOctetCount [protected], [inherited]
Definition at line 112 of file RTPSink.hh.
The documentation for this class was generated from the following file:
liveMedia/include/SimpleRTPSink.hh