MatroskaFileServerDemux Class Reference
#include <MatroskaFileServerDemux.hh>
Public Types
typedef void(onCreationFunc) (MatroskaFileServerDemux *newDemux, void *clientData)
Public Member Functions
ServerMediaSubsession * newServerMediaSubsession ()
ServerMediaSubsession * newServerMediaSubsession (unsigned &resultTrackNumber)
ServerMediaSubsession * newServerMediaSubsessionByTrackNumber (unsigned trackNumber)
MatroskaFile * ourMatroskaFile ()
char const * fileName () const
float fileDuration () const
FramedSource * newDemuxedTrack (unsigned clientSessionId, unsigned trackNumber)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static void createNew (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData, char const *preferredLanguage=`eng`)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TaskToken & nextTask ()
Private Member Functions
MatroskaFileServerDemux (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData, char const *preferredLanguage)
virtual ~MatroskaFileServerDemux ()
void onMatroskaFileCreation (MatroskaFile *newFile)
Static Private Member Functions
static void onMatroskaFileCreation (MatroskaFile *newFile, void *clientData)
Private Attributes
char const * fFileName
onCreationFunc * fOnCreation
void * fOnCreationClientData
MatroskaFile * fOurMatroskaFile
u_int8_t fNextTrackTypeToCheck
unsigned fLastClientSessionId
MatroskaDemux * fLastCreatedDemux
Detailed Description
Definition at line 32 of file MatroskaFileServerDemux.hh.
Member Typedef Documentation
typedef void(MatroskaFileServerDemux::onCreationFunc) (MatroskaFileServerDemux *newDemux, void *clientData)
Definition at line 34 of file MatroskaFileServerDemux.hh.
Constructor & Destructor Documentation
MatroskaFileServerDemux::MatroskaFileServerDemux (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData, char const * preferredLanguage) [private]
virtual MatroskaFileServerDemux::~MatroskaFileServerDemux () [private], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static void MatroskaFileServerDemux::createNew (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData, char const * preferredLanguage = `eng`) [static]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
float MatroskaFileServerDemux::fileDuration () const [inline]
Definition at line 56 of file MatroskaFileServerDemux.hh.
References MatroskaFile::fileDuration(), and fOurMatroskaFile.
{ return fOurMatroskaFile->fileDuration(); }
char const* MatroskaFileServerDemux::fileName () const [inline]
Definition at line 55 of file MatroskaFileServerDemux.hh.
References fFileName.
{ return fFileName; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
FramedSource* MatroskaFileServerDemux::newDemuxedTrack (unsigned clientSessionId, unsigned trackNumber)
ServerMediaSubsession* MatroskaFileServerDemux::newServerMediaSubsession ()
ServerMediaSubsession* MatroskaFileServerDemux::newServerMediaSubsession (unsigned & resultTrackNumber)
ServerMediaSubsession* MatroskaFileServerDemux::newServerMediaSubsessionByTrackNumber (unsigned trackNumber)
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
static void MatroskaFileServerDemux::onMatroskaFileCreation (MatroskaFile * newFile, void * clientData) [static], [private]
void MatroskaFileServerDemux::onMatroskaFileCreation (MatroskaFile * newFile) [private]
MatroskaFile* MatroskaFileServerDemux::ourMatroskaFile () [inline]
Definition at line 54 of file MatroskaFileServerDemux.hh.
References fOurMatroskaFile.
{ return fOurMatroskaFile; }
Field Documentation
char const* MatroskaFileServerDemux::fFileName [private]
Definition at line 71 of file MatroskaFileServerDemux.hh.
Referenced by fileName().
unsigned MatroskaFileServerDemux::fLastClientSessionId [private]
Definition at line 80 of file MatroskaFileServerDemux.hh.
MatroskaDemux* MatroskaFileServerDemux::fLastCreatedDemux [private]
Definition at line 81 of file MatroskaFileServerDemux.hh.
u_int8_t MatroskaFileServerDemux::fNextTrackTypeToCheck [private]
Definition at line 77 of file MatroskaFileServerDemux.hh.
onCreationFunc* MatroskaFileServerDemux::fOnCreation [private]
Definition at line 72 of file MatroskaFileServerDemux.hh.
void* MatroskaFileServerDemux::fOnCreationClientData [private]
Definition at line 73 of file MatroskaFileServerDemux.hh.
MatroskaFile* MatroskaFileServerDemux::fOurMatroskaFile [private]
Definition at line 74 of file MatroskaFileServerDemux.hh.
Referenced by fileDuration(), and ourMatroskaFile().
The documentation for this class was generated from the following file:
liveMedia/include/MatroskaFileServerDemux.hh