MP3FrameParams Class Reference
#include <MP3Internals.hh>
Public Member Functions
MP3FrameParams ()
~MP3FrameParams ()
void setParamsFromHeader ()
void setBytePointer (unsigned char const *restOfFrame, unsigned totNumBytes)
void getSideInfo (MP3SideInfo &si)
unsigned getBits (unsigned numBits)
unsigned get1Bit ()
Data Fields
unsigned hdr
unsigned char frameBytes [MAX_MP3_FRAME_SIZE]
Boolean isMPEG2
unsigned layer
unsigned bitrate
unsigned samplingFreq
Boolean isStereo
Boolean isFreeFormat
unsigned frameSize
unsigned sideInfoSize
Boolean hasCRC
unsigned oldHdr
unsigned firstHdr
Private Member Functions
unsigned computeSideInfoSize ()
Private Attributes
BitVector bv
unsigned bitrateIndex
unsigned samplingFreqIndex
Boolean isMPEG2_5
Boolean padding
Boolean extension
unsigned mode
unsigned mode_ext
Boolean copyright
Boolean original
unsigned emphasis
unsigned stereo
Detailed Description
Definition at line 66 of file MP3Internals.hh.
Constructor & Destructor Documentation
MP3FrameParams::MP3FrameParams ()
MP3FrameParams::~MP3FrameParams ()
Member Function Documentation
unsigned MP3FrameParams::computeSideInfoSize () [private]
unsigned MP3FrameParams::get1Bit () [inline]
Definition at line 102 of file MP3Internals.hh.
References bv, and BitVector::get1Bit().
{ return bv.get1Bit(); }
unsigned MP3FrameParams::getBits (unsigned numBits) [inline]
Definition at line 101 of file MP3Internals.hh.
References bv, and BitVector::getBits().
{ return bv.getBits(numBits); }
void MP3FrameParams::getSideInfo (MP3SideInfo & si)
void MP3FrameParams::setBytePointer (unsigned char const * restOfFrame, unsigned totNumBytes) [inline]
Definition at line 89 of file MP3Internals.hh.
References bv, and BitVector::setup().
                                            {// called during setup
    bv.setup((unsigned char*)restOfFrame, 0, 8*totNumBytes);
  }
void MP3FrameParams::setParamsFromHeader ()
Field Documentation
unsigned MP3FrameParams::bitrate
Definition at line 81 of file MP3Internals.hh.
unsigned MP3FrameParams::bitrateIndex [private]
Definition at line 108 of file MP3Internals.hh.
BitVector MP3FrameParams::bv [private]
Definition at line 105 of file MP3Internals.hh.
Referenced by get1Bit(), getBits(), and setBytePointer().
Boolean MP3FrameParams::copyright [private]
Definition at line 115 of file MP3Internals.hh.
unsigned MP3FrameParams::emphasis [private]
Definition at line 117 of file MP3Internals.hh.
Boolean MP3FrameParams::extension [private]
Definition at line 112 of file MP3Internals.hh.
unsigned MP3FrameParams::firstHdr
Definition at line 95 of file MP3Internals.hh.
unsigned char MP3FrameParams::frameBytes[MAX_MP3_FRAME_SIZE]
Definition at line 75 of file MP3Internals.hh.
unsigned MP3FrameParams::frameSize
Definition at line 85 of file MP3Internals.hh.
Boolean MP3FrameParams::hasCRC
Definition at line 87 of file MP3Internals.hh.
unsigned MP3FrameParams::hdr
Definition at line 72 of file MP3Internals.hh.
Boolean MP3FrameParams::isFreeFormat
Definition at line 84 of file MP3Internals.hh.
Boolean MP3FrameParams::isMPEG2
Definition at line 79 of file MP3Internals.hh.
Boolean MP3FrameParams::isMPEG2_5 [private]
Definition at line 110 of file MP3Internals.hh.
Boolean MP3FrameParams::isStereo
Definition at line 83 of file MP3Internals.hh.
unsigned MP3FrameParams::layer
Definition at line 80 of file MP3Internals.hh.
unsigned MP3FrameParams::mode [private]
Definition at line 113 of file MP3Internals.hh.
unsigned MP3FrameParams::mode_ext [private]
Definition at line 114 of file MP3Internals.hh.
unsigned MP3FrameParams::oldHdr
Definition at line 95 of file MP3Internals.hh.
Boolean MP3FrameParams::original [private]
Definition at line 116 of file MP3Internals.hh.
Boolean MP3FrameParams::padding [private]
Definition at line 111 of file MP3Internals.hh.
unsigned MP3FrameParams::samplingFreq
Definition at line 82 of file MP3Internals.hh.
unsigned MP3FrameParams::samplingFreqIndex [private]
Definition at line 109 of file MP3Internals.hh.
unsigned MP3FrameParams::sideInfoSize
Definition at line 86 of file MP3Internals.hh.
unsigned MP3FrameParams::stereo [private]
Definition at line 118 of file MP3Internals.hh.
The documentation for this class was generated from the following file:
liveMedia/MP3Internals.hh