OggFileServerDemux Class Reference
#include <OggFileServerDemux.hh>
Public Types
typedef void(onCreationFunc) (OggFileServerDemux *newDemux, void *clientData)
Public Member Functions
ServerMediaSubsession * newServerMediaSubsession ()
ServerMediaSubsession * newServerMediaSubsession (u_int32_t &resultTrackNumber)
ServerMediaSubsession * newServerMediaSubsessionByTrackNumber (u_int32_t trackNumber)
OggFile * ourOggFile ()
char const * fileName () const
FramedSource * newDemuxedTrack (unsigned clientSessionId, u_int32_t trackNumber)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static void createNew (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TaskToken & nextTask ()
Private Member Functions
OggFileServerDemux (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData)
virtual ~OggFileServerDemux ()
void onOggFileCreation (OggFile *newFile)
Static Private Member Functions
static void onOggFileCreation (OggFile *newFile, void *clientData)
Private Attributes
char const * fFileName
onCreationFunc * fOnCreation
void * fOnCreationClientData
OggFile * fOurOggFile
OggTrackTableIterator * fIter
unsigned fLastClientSessionId
OggDemux * fLastCreatedDemux
Detailed Description
Definition at line 32 of file OggFileServerDemux.hh.
Member Typedef Documentation
typedef void(OggFileServerDemux::onCreationFunc) (OggFileServerDemux *newDemux, void *clientData)
Definition at line 34 of file OggFileServerDemux.hh.
Constructor & Destructor Documentation
OggFileServerDemux::OggFileServerDemux (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData) [private]
virtual OggFileServerDemux::~OggFileServerDemux () [private], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static void OggFileServerDemux::createNew (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData) [static]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
char const* OggFileServerDemux::fileName () const [inline]
Definition at line 54 of file OggFileServerDemux.hh.
References fFileName.
{ return fFileName; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
FramedSource* OggFileServerDemux::newDemuxedTrack (unsigned clientSessionId, u_int32_t trackNumber)
ServerMediaSubsession* OggFileServerDemux::newServerMediaSubsession ()
ServerMediaSubsession* OggFileServerDemux::newServerMediaSubsession (u_int32_t & resultTrackNumber)
ServerMediaSubsession* OggFileServerDemux::newServerMediaSubsessionByTrackNumber (u_int32_t trackNumber)
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
static void OggFileServerDemux::onOggFileCreation (OggFile * newFile, void * clientData) [static], [private]
void OggFileServerDemux::onOggFileCreation (OggFile * newFile) [private]
OggFile* OggFileServerDemux::ourOggFile () [inline]
Definition at line 53 of file OggFileServerDemux.hh.
References fOurOggFile.
{ return fOurOggFile; }
Field Documentation
char const* OggFileServerDemux::fFileName [private]
Definition at line 68 of file OggFileServerDemux.hh.
Referenced by fileName().
OggTrackTableIterator* OggFileServerDemux::fIter [private]
Definition at line 74 of file OggFileServerDemux.hh.
unsigned OggFileServerDemux::fLastClientSessionId [private]
Definition at line 77 of file OggFileServerDemux.hh.
OggDemux* OggFileServerDemux::fLastCreatedDemux [private]
Definition at line 78 of file OggFileServerDemux.hh.
onCreationFunc* OggFileServerDemux::fOnCreation [private]
Definition at line 69 of file OggFileServerDemux.hh.
void* OggFileServerDemux::fOnCreationClientData [private]
Definition at line 70 of file OggFileServerDemux.hh.
OggFile* OggFileServerDemux::fOurOggFile [private]
Definition at line 71 of file OggFileServerDemux.hh.
Referenced by ourOggFile().
The documentation for this class was generated from the following file:
liveMedia/include/OggFileServerDemux.hh