RTSPServer::RTSPClientSession Class Reference
#include <RTSPServer.hh>
Data Structures
struct streamState
Protected Member Functions
RTSPClientSession (RTSPServer &ourServer, u_int32_t sessionId)
virtual ~RTSPClientSession ()
virtual void handleCmd_SETUP (RTSPClientConnection *ourClientConnection, char const *urlPreSuffix, char const *urlSuffix, char const *fullRequestStr)
virtual void handleCmd_withinSession (RTSPClientConnection *ourClientConnection, char const *cmdName, char const *urlPreSuffix, char const *urlSuffix, char const *fullRequestStr)
virtual void handleCmd_TEARDOWN (RTSPClientConnection *ourClientConnection, ServerMediaSubsession *subsession)
virtual void handleCmd_PLAY (RTSPClientConnection *ourClientConnection, ServerMediaSubsession *subsession, char const *fullRequestStr)
virtual void handleCmd_PAUSE (RTSPClientConnection *ourClientConnection, ServerMediaSubsession *subsession)
virtual void handleCmd_GET_PARAMETER (RTSPClientConnection *ourClientConnection, ServerMediaSubsession *subsession, char const *fullRequestStr)
virtual void handleCmd_SET_PARAMETER (RTSPClientConnection *ourClientConnection, ServerMediaSubsession *subsession, char const *fullRequestStr)
void deleteStreamByTrack (unsigned trackNum)
void reclaimStreamStates ()
Boolean isMulticast () const
void setRTSPResponse (RTSPClientConnection *ourClientConnection, char const *responseStr)
void setRTSPResponse (RTSPClientConnection *ourClientConnection, char const *responseStr, u_int32_t sessionId)
void setRTSPResponse (RTSPClientConnection *ourClientConnection, char const *responseStr, char const *contentStr)
void setRTSPResponse (RTSPClientConnection *ourClientConnection, char const *responseStr, u_int32_t sessionId, char const *contentStr)
Boolean usesTCPTransport () const
UsageEnvironment & envir ()
void noteLiveness ()
Static Protected Member Functions
static void noteClientLiveness (ClientSession *clientSession)
static void livenessTimeoutTask (ClientSession *clientSession)
Protected Attributes
RTSPServer & fOurRTSPServer
Boolean fIsMulticast
Boolean fStreamAfterSETUP
unsigned char fTCPStreamIdCount
unsigned fNumStreamStates
struct RTSPServer::RTSPClientSession::streamState * fStreamStates
GenericMediaServer & fOurServer
u_int32_t fOurSessionId
ServerMediaSession * fOurServerMediaSession
TaskToken fLivenessCheckTask
Friends
class RTSPServer
class RTSPClientConnection
Detailed Description
Definition at line 220 of file RTSPServer.hh.
Constructor & Destructor Documentation
RTSPServer::RTSPClientSession::RTSPClientSession (RTSPServer & ourServer, u_int32_t sessionId) [protected]
virtual RTSPServer::RTSPClientSession::~RTSPClientSession () [protected], [virtual]
Member Function Documentation
void RTSPServer::RTSPClientSession::deleteStreamByTrack (unsigned trackNum) [protected]
UsageEnvironment& GenericMediaServer::ClientSession::envir () [inline], [protected], [inherited]
Definition at line 116 of file GenericMediaServer.hh.
References Medium::envir(), and GenericMediaServer::ClientSession::fOurServer.
{ return fOurServer.envir(); }
virtual void RTSPServer::RTSPClientSession::handleCmd_GET_PARAMETER (RTSPClientConnection * ourClientConnection, ServerMediaSubsession * subsession, char const * fullRequestStr) [protected], [virtual]
virtual void RTSPServer::RTSPClientSession::handleCmd_PAUSE (RTSPClientConnection * ourClientConnection, ServerMediaSubsession * subsession) [protected], [virtual]
virtual void RTSPServer::RTSPClientSession::handleCmd_PLAY (RTSPClientConnection * ourClientConnection, ServerMediaSubsession * subsession, char const * fullRequestStr) [protected], [virtual]
virtual void RTSPServer::RTSPClientSession::handleCmd_SET_PARAMETER (RTSPClientConnection * ourClientConnection, ServerMediaSubsession * subsession, char const * fullRequestStr) [protected], [virtual]
virtual void RTSPServer::RTSPClientSession::handleCmd_SETUP (RTSPClientConnection * ourClientConnection, char const * urlPreSuffix, char const * urlSuffix, char const * fullRequestStr) [protected], [virtual]
virtual void RTSPServer::RTSPClientSession::handleCmd_TEARDOWN (RTSPClientConnection * ourClientConnection, ServerMediaSubsession * subsession) [protected], [virtual]
virtual void RTSPServer::RTSPClientSession::handleCmd_withinSession (RTSPClientConnection * ourClientConnection, char const * cmdName, char const * urlPreSuffix, char const * urlSuffix, char const * fullRequestStr) [protected], [virtual]
Boolean RTSPServer::RTSPClientSession::isMulticast () const [inline], [protected]
Definition at line 247 of file RTSPServer.hh.
References fIsMulticast.
{ return fIsMulticast; }
static void GenericMediaServer::ClientSession::livenessTimeoutTask (ClientSession * clientSession) [static], [protected], [inherited]
static void GenericMediaServer::ClientSession::noteClientLiveness (ClientSession * clientSession) [static], [protected], [inherited]
void GenericMediaServer::ClientSession::noteLiveness () [protected], [inherited]
void RTSPServer::RTSPClientSession::reclaimStreamStates () [protected]
void RTSPServer::RTSPClientSession::setRTSPResponse (RTSPClientConnection * ourClientConnection, char const * responseStr) [inline], [protected]
Definition at line 250 of file RTSPServer.hh.
References RTSPServer::RTSPClientConnection::setRTSPResponse().
{ ourClientConnection->setRTSPResponse(responseStr); }
void RTSPServer::RTSPClientSession::setRTSPResponse (RTSPClientConnection * ourClientConnection, char const * responseStr, u_int32_t sessionId) [inline], [protected]
Definition at line 251 of file RTSPServer.hh.
References RTSPServer::RTSPClientConnection::setRTSPResponse().
{ ourClientConnection->setRTSPResponse(responseStr, sessionId); }
void RTSPServer::RTSPClientSession::setRTSPResponse (RTSPClientConnection * ourClientConnection, char const * responseStr, char const * contentStr) [inline], [protected]
Definition at line 252 of file RTSPServer.hh.
References RTSPServer::RTSPClientConnection::setRTSPResponse().
{ ourClientConnection->setRTSPResponse(responseStr, contentStr); }
void RTSPServer::RTSPClientSession::setRTSPResponse (RTSPClientConnection * ourClientConnection, char const * responseStr, u_int32_t sessionId, char const * contentStr) [inline], [protected]
Definition at line 253 of file RTSPServer.hh.
References RTSPServer::RTSPClientConnection::setRTSPResponse().
{ ourClientConnection->setRTSPResponse(responseStr, sessionId, contentStr); }
Boolean RTSPServer::RTSPClientSession::usesTCPTransport () const [inline], [protected]
Definition at line 259 of file RTSPServer.hh.
{ return fTCPStreamIdCount > 0; }
Friends And Related Function Documentation
friend class RTSPClientConnection [friend]
Definition at line 226 of file RTSPServer.hh.
friend class RTSPServer [friend]
Definition at line 225 of file RTSPServer.hh.
Field Documentation
Boolean RTSPServer::RTSPClientSession::fIsMulticast [protected]
Definition at line 257 of file RTSPServer.hh.
Referenced by isMulticast().
TaskToken GenericMediaServer::ClientSession::fLivenessCheckTask [protected], [inherited]
Definition at line 127 of file GenericMediaServer.hh.
unsigned RTSPServer::RTSPClientSession::fNumStreamStates [protected]
Definition at line 260 of file RTSPServer.hh.
RTSPServer& RTSPServer::RTSPClientSession::fOurRTSPServer [protected]
Definition at line 256 of file RTSPServer.hh.
GenericMediaServer& GenericMediaServer::ClientSession::fOurServer [protected], [inherited]
Definition at line 124 of file GenericMediaServer.hh.
Referenced by GenericMediaServer::ClientSession::envir().
ServerMediaSession* GenericMediaServer::ClientSession::fOurServerMediaSession [protected], [inherited]
Definition at line 126 of file GenericMediaServer.hh.
u_int32_t GenericMediaServer::ClientSession::fOurSessionId [protected], [inherited]
Definition at line 125 of file GenericMediaServer.hh.
Boolean RTSPServer::RTSPClientSession::fStreamAfterSETUP [protected]
Definition at line 257 of file RTSPServer.hh.
struct RTSPServer::RTSPClientSession::streamState * RTSPServer::RTSPClientSession::fStreamStates [protected]
unsigned char RTSPServer::RTSPClientSession::fTCPStreamIdCount [protected]
Definition at line 258 of file RTSPServer.hh.
The documentation for this class was generated from the following file:
liveMedia/include/RTSPServer.hh