RTSPServerSupportingHTTPStreaming Class Reference
#include <RTSPServerSupportingHTTPStreaming.hh>
Data Structures
class RTSPClientConnectionSupportingHTTPStreaming
Public Types
typedef void(responseHandlerForREGISTER) (RTSPServer *rtspServer, unsigned requestId, int resultCode, char *resultString)
typedef void(responseHandlerForDEREGISTER) (RTSPServer *rtspServer, unsigned requestId, int resultCode, char *resultString)
Public Member Functions
Boolean setHTTPPort (Port httpPort)
unsigned registerStream (ServerMediaSession *serverMediaSession, char const *remoteClientNameOrAddress, portNumBits remoteClientPortNum, responseHandlerForREGISTER *responseHandler, char const *username=NULL, char const *password=NULL, Boolean receiveOurStreamViaTCP=False, char const *proxyURLSuffix=NULL)
unsigned deregisterStream (ServerMediaSession *serverMediaSession, char const *remoteClientNameOrAddress, portNumBits remoteClientPortNum, responseHandlerForDEREGISTER *responseHandler, char const *username=NULL, char const *password=NULL, char const *proxyURLSuffix=NULL)
char * rtspURL (ServerMediaSession const *serverMediaSession, int clientSocket=-1) const
char * rtspURLPrefix (int clientSocket=-1) const
UserAuthenticationDatabase * setAuthenticationDatabase (UserAuthenticationDatabase *newDB)
void disableStreamingRTPOverTCP ()
Boolean setUpTunnelingOverHTTP (Port httpPort)
portNumBits httpServerPortNum () const
void addServerMediaSession (ServerMediaSession *serverMediaSession)
virtual ServerMediaSession * lookupServerMediaSession (char const *streamName, Boolean isFirstLookupInSession=True)
void removeServerMediaSession (ServerMediaSession *serverMediaSession)
void removeServerMediaSession (char const *streamName)
void closeAllClientSessionsForServerMediaSession (ServerMediaSession *serverMediaSession)
void closeAllClientSessionsForServerMediaSession (char const *streamName)
void deleteServerMediaSession (ServerMediaSession *serverMediaSession)
void deleteServerMediaSession (char const *streamName)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static RTSPServerSupportingHTTPStreaming * createNew (UsageEnvironment &env, Port rtspPort=554, UserAuthenticationDatabase *authDatabase=NULL, unsigned reclamationTestSeconds=65)
static Boolean lookupByName (UsageEnvironment &env, char const *name, RTSPServer *&resultServer)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
RTSPServerSupportingHTTPStreaming (UsageEnvironment &env, int ourSocket, Port ourPort, UserAuthenticationDatabase *authDatabase, unsigned reclamationTestSeconds)
virtual ~RTSPServerSupportingHTTPStreaming ()
virtual ClientConnection * createNewClientConnection (int clientSocket, struct sockaddr_in clientAddr)
virtual char const * allowedCommandNames ()
virtual Boolean weImplementREGISTER (char const *cmd, char const *proxyURLSuffix, char *&responseStr)
virtual void implementCmd_REGISTER (char const *cmd, char const *url, char const *urlSuffix, int socketToRemoteServer, Boolean deliverViaTCP, char const *proxyURLSuffix)
virtual UserAuthenticationDatabase * getAuthenticationDatabaseForCommand (char const *cmdName)
virtual Boolean specialClientAccessCheck (int clientSocket, struct sockaddr_in &clientAddr, char const *urlSuffix)
virtual Boolean specialClientUserAccessCheck (int clientSocket, struct sockaddr_in &clientAddr, char const *urlSuffix, char const *username)
virtual ClientSession * createNewClientSession (u_int32_t sessionId)
void cleanup ()
void incomingConnectionHandler ()
void incomingConnectionHandlerOnSocket (int serverSocket)
ClientSession * createNewClientSessionWithId ()
ClientSession * lookupClientSession (u_int32_t sessionId)
ClientSession * lookupClientSession (char const *sessionIdStr)
TaskToken & nextTask ()
Static Protected Member Functions
static int setUpOurSocket (UsageEnvironment &env, Port &ourPort)
static void incomingConnectionHandler (void *, int)
Protected Attributes
int fServerSocket
Port fServerPort
unsigned fReclamationSeconds
Detailed Description
Definition at line 34 of file RTSPServerSupportingHTTPStreaming.hh.
Member Typedef Documentation
typedef void(RTSPServer::responseHandlerForDEREGISTER) (RTSPServer *rtspServer, unsigned requestId, int resultCode, char *resultString) [inherited]
Definition at line 64 of file RTSPServer.hh.
typedef void(RTSPServer::responseHandlerForREGISTER) (RTSPServer *rtspServer, unsigned requestId, int resultCode, char *resultString) [inherited]
Definition at line 46 of file RTSPServer.hh.
Constructor & Destructor Documentation
RTSPServerSupportingHTTPStreaming::RTSPServerSupportingHTTPStreaming (UsageEnvironment & env, int ourSocket, Port ourPort, UserAuthenticationDatabase * authDatabase, unsigned reclamationTestSeconds) [protected]
virtual RTSPServerSupportingHTTPStreaming::~RTSPServerSupportingHTTPStreaming () [protected], [virtual]
Member Function Documentation
void GenericMediaServer::addServerMediaSession (ServerMediaSession * serverMediaSession) [inherited]
virtual char const* RTSPServer::allowedCommandNames () [protected], [virtual], [inherited]
Reimplemented in HandlerServerForREGISTERCommand , and RTSPServerWithREGISTERProxying .
void GenericMediaServer::cleanup () [protected], [inherited]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
void GenericMediaServer::closeAllClientSessionsForServerMediaSession (ServerMediaSession * serverMediaSession) [inherited]
void GenericMediaServer::closeAllClientSessionsForServerMediaSession (char const * streamName) [inherited]
static RTSPServerSupportingHTTPStreaming* RTSPServerSupportingHTTPStreaming::createNew (UsageEnvironment & env, Port rtspPort = 554, UserAuthenticationDatabase * authDatabase = NULL, unsigned reclamationTestSeconds = 65) [static]
virtual ClientConnection* RTSPServerSupportingHTTPStreaming::createNewClientConnection (int clientSocket, struct sockaddr_in clientAddr) [protected], [virtual]
Reimplemented from RTSPServer .
virtual ClientSession* RTSPServer::createNewClientSession (u_int32_t sessionId) [protected], [virtual], [inherited]
Implements GenericMediaServer .
ClientSession* GenericMediaServer::createNewClientSessionWithId () [protected], [inherited]
void GenericMediaServer::deleteServerMediaSession (ServerMediaSession * serverMediaSession) [inherited]
void GenericMediaServer::deleteServerMediaSession (char const * streamName) [inherited]
unsigned RTSPServer::deregisterStream (ServerMediaSession * serverMediaSession, char const * remoteClientNameOrAddress, portNumBits remoteClientPortNum, responseHandlerForDEREGISTER * responseHandler, char const * username = NULL, char const * password = NULL, char const * proxyURLSuffix = NULL) [inherited]
void RTSPServer::disableStreamingRTPOverTCP () [inline], [inherited]
Definition at line 88 of file RTSPServer.hh.
References RTSPServer::fAllowStreamingRTPOverTCP, and False.
                                    {
    fAllowStreamingRTPOverTCP = False;
  }
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual UserAuthenticationDatabase* RTSPServer::getAuthenticationDatabaseForCommand (char const * cmdName) [protected], [virtual], [inherited]
Reimplemented in RTSPServerWithREGISTERProxying .
portNumBits RTSPServer::httpServerPortNum () const [inherited]
virtual void RTSPServer::implementCmd_REGISTER (char const * cmd, char const * url, char const * urlSuffix, int socketToRemoteServer, Boolean deliverViaTCP, char const * proxyURLSuffix) [protected], [virtual], [inherited]
Reimplemented in HandlerServerForREGISTERCommand , and RTSPServerWithREGISTERProxying .
static void GenericMediaServer::incomingConnectionHandler (void * , int) [static], [protected], [inherited]
void GenericMediaServer::incomingConnectionHandler () [protected], [inherited]
void GenericMediaServer::incomingConnectionHandlerOnSocket (int serverSocket) [protected], [inherited]
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean RTSPServer::lookupByName (UsageEnvironment & env, char const * name, RTSPServer *& resultServer) [static], [inherited]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
ClientSession* GenericMediaServer::lookupClientSession (u_int32_t sessionId) [protected], [inherited]
ClientSession* GenericMediaServer::lookupClientSession (char const * sessionIdStr) [protected], [inherited]
virtual ServerMediaSession* GenericMediaServer::lookupServerMediaSession (char const * streamName, Boolean isFirstLookupInSession = True) [virtual], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
unsigned RTSPServer::registerStream (ServerMediaSession * serverMediaSession, char const * remoteClientNameOrAddress, portNumBits remoteClientPortNum, responseHandlerForREGISTER * responseHandler, char const * username = NULL, char const * password = NULL, Boolean receiveOurStreamViaTCP = False, char const * proxyURLSuffix = NULL) [inherited]
void GenericMediaServer::removeServerMediaSession (ServerMediaSession * serverMediaSession) [inherited]
void GenericMediaServer::removeServerMediaSession (char const * streamName) [inherited]
char* RTSPServer::rtspURL (ServerMediaSession const * serverMediaSession, int clientSocket = -1) const [inherited]
char* RTSPServer::rtspURLPrefix (int clientSocket = -1) const [inherited]
UserAuthenticationDatabase* RTSPServer::setAuthenticationDatabase (UserAuthenticationDatabase * newDB) [inherited]
Boolean RTSPServerSupportingHTTPStreaming::setHTTPPort (Port httpPort) [inline]
Definition at line 40 of file RTSPServerSupportingHTTPStreaming.hh.
References RTSPServer::setUpTunnelingOverHTTP().
{ return setUpTunnelingOverHTTP(httpPort); }
static int GenericMediaServer::setUpOurSocket (UsageEnvironment & env, Port & ourPort) [static], [protected], [inherited]
Boolean RTSPServer::setUpTunnelingOverHTTP (Port httpPort) [inherited]
Referenced by setHTTPPort().
virtual Boolean RTSPServer::specialClientAccessCheck (int clientSocket, struct sockaddr_in & clientAddr, char const * urlSuffix) [protected], [virtual], [inherited]
virtual Boolean RTSPServer::specialClientUserAccessCheck (int clientSocket, struct sockaddr_in & clientAddr, char const * urlSuffix, char const * username) [protected], [virtual], [inherited]
virtual Boolean RTSPServer::weImplementREGISTER (char const * cmd, char const * proxyURLSuffix, char *& responseStr) [protected], [virtual], [inherited]
Reimplemented in HandlerServerForREGISTERCommand , and RTSPServerWithREGISTERProxying .
Field Documentation
unsigned GenericMediaServer::fReclamationSeconds [protected], [inherited]
Definition at line 158 of file GenericMediaServer.hh.
Port GenericMediaServer::fServerPort [protected], [inherited]
Definition at line 157 of file GenericMediaServer.hh.
Referenced by HandlerServerForREGISTERCommand::serverPortNum().
int GenericMediaServer::fServerSocket [protected], [inherited]
Definition at line 156 of file GenericMediaServer.hh.
The documentation for this class was generated from the following file:
liveMedia/include/RTSPServerSupportingHTTPStreaming.hh