PassiveServerMediaSubsession Class Reference
#include <PassiveServerMediaSubsession.hh>
Public Member Functions
unsigned trackNumber () const
char const * trackId ()
virtual void pauseStream (unsigned clientSessionId, void *streamToken)
virtual void seekStream (unsigned clientSessionId, void *streamToken, double &seekNPT, double streamDuration, u_int64_t &numBytes)
virtual void seekStream (unsigned clientSessionId, void *streamToken, char *&absStart, char *&absEnd)
virtual void nullSeekStream (unsigned clientSessionId, void *streamToken, double streamEndTime, u_int64_t &numBytes)
virtual void setStreamScale (unsigned clientSessionId, void *streamToken, float scale)
virtual FramedSource * getStreamSource (void *streamToken)
virtual void testScaleFactor (float &scale)
virtual float duration () const
virtual void getAbsoluteTimeRange (char *&absStartTime, char *&absEndTime) const
void setServerAddressAndPortForSDP (netAddressBits addressBits, portNumBits portBits)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static PassiveServerMediaSubsession * createNew (RTPSink &rtpSink, RTCPInstance *rtcpInstance=NULL)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
PassiveServerMediaSubsession (RTPSink &rtpSink, RTCPInstance *rtcpInstance)
virtual ~PassiveServerMediaSubsession ()
virtual Boolean rtcpIsMuxed ()
virtual char const * sdpLines ()
virtual void getStreamParameters (unsigned clientSessionId, netAddressBits clientAddress, Port const &clientRTPPort, Port const &clientRTCPPort, int tcpSocketNum, unsigned char rtpChannelId, unsigned char rtcpChannelId, netAddressBits &destinationAddress, u_int8_t &destinationTTL, Boolean &isMulticast, Port &serverRTPPort, Port &serverRTCPPort, void *&streamToken)
virtual void startStream (unsigned clientSessionId, void *streamToken, TaskFunc *rtcpRRHandler, void *rtcpRRHandlerClientData, unsigned short &rtpSeqNum, unsigned &rtpTimestamp, ServerRequestAlternativeByteHandler *serverRequestAlternativeByteHandler, void *serverRequestAlternativeByteHandlerClientData)
virtual float getCurrentNPT (void *streamToken)
virtual void getRTPSinkandRTCP (void *streamToken, RTPSink const *&rtpSink, RTCPInstance const *&rtcp)
virtual void deleteStream (unsigned clientSessionId, void *&streamToken)
char const * rangeSDPLine () const
TaskToken & nextTask ()
Protected Attributes
char * fSDPLines
ServerMediaSession * fParentSession
netAddressBits fServerAddressForSDP
portNumBits fPortNumForSDP
Private Attributes
RTPSink & fRTPSink
RTCPInstance * fRTCPInstance
HashTable * fClientRTCPSourceRecords
Detailed Description
Definition at line 36 of file PassiveServerMediaSubsession.hh.
Constructor & Destructor Documentation
PassiveServerMediaSubsession::PassiveServerMediaSubsession (RTPSink & rtpSink, RTCPInstance * rtcpInstance) [protected]
virtual PassiveServerMediaSubsession::~PassiveServerMediaSubsession () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static PassiveServerMediaSubsession* PassiveServerMediaSubsession::createNew (RTPSink & rtpSink, RTCPInstance * rtcpInstance = NULL) [static]
virtual void PassiveServerMediaSubsession::deleteStream (unsigned clientSessionId, void *& streamToken) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
virtual float ServerMediaSubsession::duration () const [virtual], [inherited]
Reimplemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , MPEG1or2DemuxedServerMediaSubsession , WAVAudioFileServerMediaSubsession , DVVideoFileServerMediaSubsession , and MatroskaFileServerMediaSubsession .
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual void ServerMediaSubsession::getAbsoluteTimeRange (char *& absStartTime, char *& absEndTime) const [virtual], [inherited]
virtual float PassiveServerMediaSubsession::getCurrentNPT (void * streamToken) [protected], [virtual]
Reimplemented from ServerMediaSubsession .
virtual void PassiveServerMediaSubsession::getRTPSinkandRTCP (void * streamToken, RTPSink const *& rtpSink, RTCPInstance const *& rtcp) [protected], [virtual]
Implements ServerMediaSubsession .
virtual void PassiveServerMediaSubsession::getStreamParameters (unsigned clientSessionId, netAddressBits clientAddress, Port const & clientRTPPort, Port const & clientRTCPPort, int tcpSocketNum, unsigned char rtpChannelId, unsigned char rtcpChannelId, netAddressBits & destinationAddress, u_int8_t & destinationTTL, Boolean & isMulticast, Port & serverRTPPort, Port & serverRTCPPort, void *& streamToken) [protected], [virtual]
Implements ServerMediaSubsession .
virtual FramedSource* ServerMediaSubsession::getStreamSource (void * streamToken) [virtual], [inherited]
Reimplemented in OnDemandServerMediaSubsession .
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
virtual void ServerMediaSubsession::nullSeekStream (unsigned clientSessionId, void * streamToken, double streamEndTime, u_int64_t & numBytes) [virtual], [inherited]
Reimplemented in OnDemandServerMediaSubsession .
virtual void ServerMediaSubsession::pauseStream (unsigned clientSessionId, void * streamToken) [virtual], [inherited]
Reimplemented in MPEG2TransportFileServerMediaSubsession , and OnDemandServerMediaSubsession .
char const* ServerMediaSubsession::rangeSDPLine () const [protected], [inherited]
virtual Boolean PassiveServerMediaSubsession::rtcpIsMuxed () [protected], [virtual]
virtual char const* PassiveServerMediaSubsession::sdpLines () [protected], [virtual]
Implements ServerMediaSubsession .
virtual void ServerMediaSubsession::seekStream (unsigned clientSessionId, void * streamToken, double & seekNPT, double streamDuration, u_int64_t & numBytes) [virtual], [inherited]
Reimplemented in MPEG2TransportFileServerMediaSubsession , and OnDemandServerMediaSubsession .
virtual void ServerMediaSubsession::seekStream (unsigned clientSessionId, void * streamToken, char *& absStart, char *& absEnd) [virtual], [inherited]
Reimplemented in OnDemandServerMediaSubsession .
void ServerMediaSubsession::setServerAddressAndPortForSDP (netAddressBits addressBits, portNumBits portBits) [inherited]
virtual void ServerMediaSubsession::setStreamScale (unsigned clientSessionId, void * streamToken, float scale) [virtual], [inherited]
Reimplemented in MPEG2TransportFileServerMediaSubsession , and OnDemandServerMediaSubsession .
virtual void PassiveServerMediaSubsession::startStream (unsigned clientSessionId, void * streamToken, TaskFunc * rtcpRRHandler, void * rtcpRRHandlerClientData, unsigned short & rtpSeqNum, unsigned & rtpTimestamp, ServerRequestAlternativeByteHandler * serverRequestAlternativeByteHandler, void * serverRequestAlternativeByteHandlerClientData) [protected], [virtual]
Implements ServerMediaSubsession .
virtual void ServerMediaSubsession::testScaleFactor (float & scale) [virtual], [inherited]
Reimplemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , and WAVAudioFileServerMediaSubsession .
char const* ServerMediaSubsession::trackId () [inherited]
unsigned ServerMediaSubsession::trackNumber () const [inline], [inherited]
Definition at line 122 of file ServerMediaSession.hh.
References ServerMediaSubsession::fTrackNumber.
{ return fTrackNumber; }
Field Documentation
HashTable* PassiveServerMediaSubsession::fClientRTCPSourceRecords [private]
Definition at line 81 of file PassiveServerMediaSubsession.hh.
ServerMediaSession* ServerMediaSubsession::fParentSession [protected], [inherited]
Definition at line 190 of file ServerMediaSession.hh.
portNumBits ServerMediaSubsession::fPortNumForSDP [protected], [inherited]
Definition at line 192 of file ServerMediaSession.hh.
RTCPInstance* PassiveServerMediaSubsession::fRTCPInstance [private]
Definition at line 80 of file PassiveServerMediaSubsession.hh.
RTPSink& PassiveServerMediaSubsession::fRTPSink [private]
Definition at line 79 of file PassiveServerMediaSubsession.hh.
char* PassiveServerMediaSubsession::fSDPLines [protected]
Definition at line 76 of file PassiveServerMediaSubsession.hh.
netAddressBits ServerMediaSubsession::fServerAddressForSDP [protected], [inherited]
Definition at line 191 of file ServerMediaSession.hh.
The documentation for this class was generated from the following file:
liveMedia/include/PassiveServerMediaSubsession.hh