StreamReplicator Class Reference
#include <StreamReplicator.hh>
Public Member Functions
FramedSource * createStreamReplica ()
unsigned numReplicas () const
FramedSource * inputSource () const
void detachInputSource ()
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static StreamReplicator * createNew (UsageEnvironment &env, FramedSource *inputSource, Boolean deleteWhenLastReplicaDies=True)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
StreamReplicator (UsageEnvironment &env, FramedSource *inputSource, Boolean deleteWhenLastReplicaDies)
virtual ~StreamReplicator ()
TaskToken & nextTask ()
Private Member Functions
void getNextFrame (StreamReplica *replica)
void deactivateStreamReplica (StreamReplica *replica)
void removeStreamReplica (StreamReplica *replica)
void afterGettingFrame (unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds)
void onSourceClosure ()
void deliverReceivedFrame ()
Static Private Member Functions
static void afterGettingFrame (void *clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds)
static void onSourceClosure (void *clientData)
Private Attributes
FramedSource * fInputSource
Boolean fDeleteWhenLastReplicaDies
Boolean fInputSourceHasClosed
unsigned fNumReplicas
unsigned fNumActiveReplicas
unsigned fNumDeliveriesMadeSoFar
int fFrameIndex
StreamReplica * fMasterReplica
StreamReplica * fReplicasAwaitingCurrentFrame
StreamReplica * fReplicasAwaitingNextFrame
Friends
class StreamReplica
Detailed Description
Definition at line 30 of file StreamReplicator.hh.
Constructor & Destructor Documentation
StreamReplicator::StreamReplicator (UsageEnvironment & env, FramedSource * inputSource, Boolean deleteWhenLastReplicaDies) [protected]
virtual StreamReplicator::~StreamReplicator () [protected], [virtual]
Member Function Documentation
static void StreamReplicator::afterGettingFrame (void * clientData, unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds) [static], [private]
void StreamReplicator::afterGettingFrame (unsigned frameSize, unsigned numTruncatedBytes, struct timeval presentationTime, unsigned durationInMicroseconds) [private]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static StreamReplicator* StreamReplicator::createNew (UsageEnvironment & env, FramedSource * inputSource, Boolean deleteWhenLastReplicaDies = True) [static]
FramedSource* StreamReplicator::createStreamReplica ()
void StreamReplicator::deactivateStreamReplica (StreamReplica * replica) [private]
void StreamReplicator::deliverReceivedFrame () [private]
void StreamReplicator::detachInputSource () [inline]
Definition at line 47 of file StreamReplicator.hh.
References fInputSource, and NULL.
{ fInputSource = NULL; }
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
void StreamReplicator::getNextFrame (StreamReplica * replica) [private]
FramedSource* StreamReplicator::inputSource () const [inline]
Definition at line 44 of file StreamReplicator.hh.
References fInputSource.
{ return fInputSource; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
unsigned StreamReplicator::numReplicas () const [inline]
Definition at line 42 of file StreamReplicator.hh.
References fNumReplicas.
{ return fNumReplicas; }
static void StreamReplicator::onSourceClosure (void * clientData) [static], [private]
void StreamReplicator::onSourceClosure () [private]
void StreamReplicator::removeStreamReplica (StreamReplica * replica) [private]
Friends And Related Function Documentation
friend class StreamReplica [friend]
Definition at line 56 of file StreamReplicator.hh.
Field Documentation
Boolean StreamReplicator::fDeleteWhenLastReplicaDies [private]
Definition at line 76 of file StreamReplicator.hh.
int StreamReplicator::fFrameIndex [private]
Definition at line 78 of file StreamReplicator.hh.
FramedSource* StreamReplicator::fInputSource [private]
Definition at line 75 of file StreamReplicator.hh.
Referenced by detachInputSource(), and inputSource().
Boolean StreamReplicator::fInputSourceHasClosed [private]
Definition at line 76 of file StreamReplicator.hh.
StreamReplica* StreamReplicator::fMasterReplica [private]
Definition at line 80 of file StreamReplicator.hh.
unsigned StreamReplicator::fNumActiveReplicas [private]
Definition at line 77 of file StreamReplicator.hh.
unsigned StreamReplicator::fNumDeliveriesMadeSoFar [private]
Definition at line 77 of file StreamReplicator.hh.
unsigned StreamReplicator::fNumReplicas [private]
Definition at line 77 of file StreamReplicator.hh.
Referenced by numReplicas().
StreamReplica* StreamReplicator::fReplicasAwaitingCurrentFrame [private]
Definition at line 81 of file StreamReplicator.hh.
StreamReplica* StreamReplicator::fReplicasAwaitingNextFrame [private]
Definition at line 82 of file StreamReplicator.hh.
The documentation for this class was generated from the following file:
liveMedia/include/StreamReplicator.hh