Timeval Class Reference
#include <DelayQueue.hh>
Public Member Functions
time_base_seconds seconds () const
time_base_seconds seconds ()
time_base_seconds useconds () const
time_base_seconds useconds ()
int operator>= (Timeval const &arg2) const
int operator<= (Timeval const &arg2) const
int operator< (Timeval const &arg2) const
int operator> (Timeval const &arg2) const
int operator== (Timeval const &arg2) const
int operator!= (Timeval const &arg2) const
void operator+= (class DelayInterval const &arg2)
void operator-= (class DelayInterval const &arg2)
Protected Member Functions
Timeval (time_base_seconds seconds, time_base_seconds useconds)
Private Member Functions
time_base_seconds & secs ()
time_base_seconds & usecs ()
Private Attributes
struct timeval fTv
Detailed Description
Definition at line 35 of file DelayQueue.hh.
Constructor & Destructor Documentation
Timeval::Timeval (time_base_seconds seconds, time_base_seconds useconds) [inline], [protected]
Definition at line 72 of file DelayQueue.hh.
References fTv, seconds(), and useconds().
                                                                 {
    fTv.tv_sec = seconds; fTv.tv_usec = useconds;
  }
Member Function Documentation
int Timeval::operator!= (Timeval const & arg2) const [inline]
Definition at line 63 of file DelayQueue.hh.
                                            {
    return !(*this == arg2);
  }
void Timeval::operator+= (class DelayInterval const & arg2)
void Timeval::operator-= (class DelayInterval const & arg2)
int Timeval::operator< (Timeval const & arg2) const [inline]
Definition at line 54 of file DelayQueue.hh.
                                           {
    return !(*this >= arg2);
  }
int Timeval::operator<= (Timeval const & arg2) const [inline]
Definition at line 51 of file DelayQueue.hh.
                                            {
    return arg2 >= *this;
  }
int Timeval::operator== (Timeval const & arg2) const [inline]
Definition at line 60 of file DelayQueue.hh.
                                            {
    return *this >= arg2 && arg2 >= *this;
  }
int Timeval::operator> (Timeval const & arg2) const [inline]
Definition at line 57 of file DelayQueue.hh.
                                           {
    return arg2 < *this;
  }
int Timeval::operator>= (Timeval const & arg2) const
time_base_seconds Timeval::seconds () const [inline]
Definition at line 37 of file DelayQueue.hh.
References fTv.
Referenced by Timeval().
                                    {
    return fTv.tv_sec;
  }
time_base_seconds Timeval::seconds () [inline]
Definition at line 40 of file DelayQueue.hh.
References fTv.
                              {
    return fTv.tv_sec;
  }
time_base_seconds& Timeval::secs () [inline], [private]
Definition at line 77 of file DelayQueue.hh.
References fTv.
                            {
    return (time_base_seconds&)fTv.tv_sec;
  }
time_base_seconds Timeval::useconds () const [inline]
Definition at line 43 of file DelayQueue.hh.
References fTv.
Referenced by Timeval().
                                     {
    return fTv.tv_usec;
  }
time_base_seconds Timeval::useconds () [inline]
Definition at line 46 of file DelayQueue.hh.
References fTv.
                               {
    return fTv.tv_usec;
  }
time_base_seconds& Timeval::usecs () [inline], [private]
Definition at line 80 of file DelayQueue.hh.
References fTv.
                             {
    return (time_base_seconds&)fTv.tv_usec;
  }
Field Documentation
struct timeval Timeval::fTv [private]
Definition at line 84 of file DelayQueue.hh.
Referenced by seconds(), secs(), Timeval(), useconds(), and usecs().
The documentation for this class was generated from the following file:
BasicUsageEnvironment/include/DelayQueue.hh