BasicTaskScheduler0 Class Reference
#include <BasicUsageEnvironment0.hh>
Public Types
typedef void BackgroundHandlerProc(void *clientData, int mask)
Public Member Functions
virtual ~BasicTaskScheduler0 ()
virtual void SingleStep (unsigned maxDelayTime=0)=0
virtual TaskToken scheduleDelayedTask (int64_t microseconds, TaskFunc *proc, void *clientData)
virtual void unscheduleDelayedTask (TaskToken &prevTask)
virtual void doEventLoop (char volatile *watchVariable)
virtual EventTriggerId createEventTrigger (TaskFunc *eventHandlerProc)
virtual void deleteEventTrigger (EventTriggerId eventTriggerId)
virtual void triggerEvent (EventTriggerId eventTriggerId, void *clientData=NULL)
virtual void rescheduleDelayedTask (TaskToken &task, int64_t microseconds, TaskFunc *proc, void *clientData)
virtual void setBackgroundHandling (int socketNum, int conditionSet, BackgroundHandlerProc *handlerProc, void *clientData)=0
void disableBackgroundHandling (int socketNum)
virtual void moveSocketHandling (int oldSocketNum, int newSocketNum)=0
void turnOnBackgroundReadHandling (int socketNum, BackgroundHandlerProc *handlerProc, void *clientData)
void turnOffBackgroundReadHandling (int socketNum)
virtual void internalError ()
Protected Member Functions
BasicTaskScheduler0 ()
Protected Attributes
DelayQueue fDelayQueue
HandlerSet * fHandlers
int fLastHandledSocketNum
EventTriggerId volatile fTriggersAwaitingHandling
EventTriggerId fLastUsedTriggerMask
TaskFunc * fTriggeredEventHandlers [MAX_NUM_EVENT_TRIGGERS]
void * fTriggeredEventClientDatas [MAX_NUM_EVENT_TRIGGERS]
unsigned fLastUsedTriggerNum
Detailed Description
Definition at line 74 of file BasicUsageEnvironment0.hh.
Member Typedef Documentation
typedef void TaskScheduler::BackgroundHandlerProc(void *clientData, int mask) [inherited]
Definition at line 132 of file UsageEnvironment.hh.
Constructor & Destructor Documentation
virtual BasicTaskScheduler0::~BasicTaskScheduler0 () [virtual]
BasicTaskScheduler0::BasicTaskScheduler0 () [protected]
Member Function Documentation
virtual EventTriggerId BasicTaskScheduler0::createEventTrigger (TaskFunc * eventHandlerProc) [virtual]
Implements TaskScheduler .
virtual void BasicTaskScheduler0::deleteEventTrigger (EventTriggerId eventTriggerId) [virtual]
Implements TaskScheduler .
void TaskScheduler::disableBackgroundHandling (int socketNum) [inline], [inherited]
Definition at line 139 of file UsageEnvironment.hh.
References NULL, and TaskScheduler::setBackgroundHandling().
Referenced by TaskScheduler::turnOffBackgroundReadHandling().
{ setBackgroundHandling(socketNum, 0, NULL, NULL); }
virtual void BasicTaskScheduler0::doEventLoop (char volatile * watchVariable) [virtual]
Implements TaskScheduler .
virtual void TaskScheduler::internalError () [virtual], [inherited]
virtual void TaskScheduler::moveSocketHandling (int oldSocketNum, int newSocketNum) [pure virtual], [inherited]
Implemented in BasicTaskScheduler .
virtual void TaskScheduler::rescheduleDelayedTask (TaskToken & task, int64_t microseconds, TaskFunc * proc, void * clientData) [virtual], [inherited]
virtual TaskToken BasicTaskScheduler0::scheduleDelayedTask (int64_t microseconds, TaskFunc * proc, void * clientData) [virtual]
Implements TaskScheduler .
virtual void TaskScheduler::setBackgroundHandling (int socketNum, int conditionSet, BackgroundHandlerProc * handlerProc, void * clientData) [pure virtual], [inherited]
Implemented in BasicTaskScheduler .
Referenced by TaskScheduler::disableBackgroundHandling(), and TaskScheduler::turnOnBackgroundReadHandling().
virtual void BasicTaskScheduler0::SingleStep (unsigned maxDelayTime = 0) [pure virtual]
Implemented in BasicTaskScheduler .
virtual void BasicTaskScheduler0::triggerEvent (EventTriggerId eventTriggerId, void * clientData = NULL) [virtual]
Implements TaskScheduler .
void TaskScheduler::turnOffBackgroundReadHandling (int socketNum) [inline], [inherited]
Definition at line 164 of file UsageEnvironment.hh.
References TaskScheduler::disableBackgroundHandling().
{ disableBackgroundHandling(socketNum); }
void TaskScheduler::turnOnBackgroundReadHandling (int socketNum, BackgroundHandlerProc * handlerProc, void * clientData) [inline], [inherited]
Definition at line 161 of file UsageEnvironment.hh.
References TaskScheduler::setBackgroundHandling(), and SOCKET_READABLE.
                                                                                                         {
    setBackgroundHandling(socketNum, SOCKET_READABLE, handlerProc, clientData);
  }
virtual void BasicTaskScheduler0::unscheduleDelayedTask (TaskToken & prevTask) [virtual]
Implements TaskScheduler .
Field Documentation
DelayQueue BasicTaskScheduler0::fDelayQueue [protected]
Definition at line 100 of file BasicUsageEnvironment0.hh.
HandlerSet* BasicTaskScheduler0::fHandlers [protected]
Definition at line 103 of file BasicUsageEnvironment0.hh.
int BasicTaskScheduler0::fLastHandledSocketNum [protected]
Definition at line 104 of file BasicUsageEnvironment0.hh.
EventTriggerId BasicTaskScheduler0::fLastUsedTriggerMask [protected]
Definition at line 108 of file BasicUsageEnvironment0.hh.
unsigned BasicTaskScheduler0::fLastUsedTriggerNum [protected]
Definition at line 111 of file BasicUsageEnvironment0.hh.
void* BasicTaskScheduler0::fTriggeredEventClientDatas[MAX_NUM_EVENT_TRIGGERS] [protected]
Definition at line 110 of file BasicUsageEnvironment0.hh.
TaskFunc* BasicTaskScheduler0::fTriggeredEventHandlers[MAX_NUM_EVENT_TRIGGERS] [protected]
Definition at line 109 of file BasicUsageEnvironment0.hh.
EventTriggerId volatile BasicTaskScheduler0::fTriggersAwaitingHandling [protected]
Definition at line 107 of file BasicUsageEnvironment0.hh.
The documentation for this class was generated from the following file:
BasicUsageEnvironment/include/BasicUsageEnvironment0.hh