ServerMediaSession Class Reference
#include <ServerMediaSession.hh>
Public Member Functions
char * generateSDPDescription ()
char const * streamName () const
Boolean addSubsession (ServerMediaSubsession *subsession)
unsigned numSubsessions () const
void testScaleFactor (float &scale)
float duration () const
virtual void noteLiveness ()
unsigned referenceCount () const
void incrementReferenceCount ()
void decrementReferenceCount ()
Boolean & deleteWhenUnreferenced ()
void deleteAllSubsessions ()
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
Static Public Member Functions
static ServerMediaSession * createNew (UsageEnvironment &env, char const *streamName=NULL, char const *info=NULL, char const *description=NULL, Boolean isSSM=False, char const *miscSDPLines=NULL)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, ServerMediaSession *&resultSession)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
ServerMediaSession (UsageEnvironment &env, char const *streamName, char const *info, char const *description, Boolean isSSM, char const *miscSDPLines)
virtual ~ServerMediaSession ()
TaskToken & nextTask ()
Private Member Functions
virtual Boolean isServerMediaSession () const
Private Attributes
Boolean fIsSSM
ServerMediaSubsession * fSubsessionsHead
ServerMediaSubsession * fSubsessionsTail
unsigned fSubsessionCounter
char * fStreamName
char * fInfoSDPString
char * fDescriptionSDPString
char * fMiscSDPLines
struct timeval fCreationTime
unsigned fReferenceCount
Boolean fDeleteWhenUnreferenced
Friends
class ServerMediaSubsessionIterator
Detailed Description
Definition at line 33 of file ServerMediaSession.hh.
Constructor & Destructor Documentation
ServerMediaSession::ServerMediaSession (UsageEnvironment & env, char const * streamName, char const * info, char const * description, Boolean isSSM, char const * miscSDPLines) [protected]
virtual ServerMediaSession::~ServerMediaSession () [protected], [virtual]
Member Function Documentation
Boolean ServerMediaSession::addSubsession (ServerMediaSubsession * subsession)
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static ServerMediaSession* ServerMediaSession::createNew (UsageEnvironment & env, char const * streamName = NULL, char const * info = NULL, char const * description = NULL, Boolean isSSM = False, char const * miscSDPLines = NULL) [static]
void ServerMediaSession::decrementReferenceCount () [inline]
Definition at line 67 of file ServerMediaSession.hh.
References fReferenceCount.
{ if (fReferenceCount > 0) --fReferenceCount; }
void ServerMediaSession::deleteAllSubsessions ()
Boolean& ServerMediaSession::deleteWhenUnreferenced () [inline]
Definition at line 68 of file ServerMediaSession.hh.
References fDeleteWhenUnreferenced.
{ return fDeleteWhenUnreferenced; }
float ServerMediaSession::duration () const
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
char* ServerMediaSession::generateSDPDescription ()
void ServerMediaSession::incrementReferenceCount () [inline]
Definition at line 66 of file ServerMediaSession.hh.
References fReferenceCount.
{ ++fReferenceCount; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean ServerMediaSession::isServerMediaSession () const [private], [virtual]
Reimplemented from Medium .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean ServerMediaSession::lookupByName (UsageEnvironment & env, char const * mediumName, ServerMediaSession *& resultSession) [static]
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
virtual void ServerMediaSession::noteLiveness () [virtual]
unsigned ServerMediaSession::numSubsessions () const [inline]
Definition at line 52 of file ServerMediaSession.hh.
References fSubsessionCounter.
{ return fSubsessionCounter; }
unsigned ServerMediaSession::referenceCount () const [inline]
Definition at line 65 of file ServerMediaSession.hh.
References fReferenceCount.
{ return fReferenceCount; }
char const* ServerMediaSession::streamName () const [inline]
Definition at line 49 of file ServerMediaSession.hh.
References fStreamName.
{ return fStreamName; }
void ServerMediaSession::testScaleFactor (float & scale)
Friends And Related Function Documentation
friend class ServerMediaSubsessionIterator [friend]
Definition at line 91 of file ServerMediaSession.hh.
Field Documentation
struct timeval ServerMediaSession::fCreationTime [private]
Definition at line 100 of file ServerMediaSession.hh.
Boolean ServerMediaSession::fDeleteWhenUnreferenced [private]
Definition at line 102 of file ServerMediaSession.hh.
Referenced by deleteWhenUnreferenced().
char* ServerMediaSession::fDescriptionSDPString [private]
Definition at line 98 of file ServerMediaSession.hh.
char* ServerMediaSession::fInfoSDPString [private]
Definition at line 97 of file ServerMediaSession.hh.
Boolean ServerMediaSession::fIsSSM [private]
Definition at line 88 of file ServerMediaSession.hh.
char* ServerMediaSession::fMiscSDPLines [private]
Definition at line 99 of file ServerMediaSession.hh.
unsigned ServerMediaSession::fReferenceCount [private]
Definition at line 101 of file ServerMediaSession.hh.
Referenced by decrementReferenceCount(), incrementReferenceCount(), and referenceCount().
char* ServerMediaSession::fStreamName [private]
Definition at line 96 of file ServerMediaSession.hh.
Referenced by streamName().
unsigned ServerMediaSession::fSubsessionCounter [private]
Definition at line 94 of file ServerMediaSession.hh.
Referenced by numSubsessions().
ServerMediaSubsession* ServerMediaSession::fSubsessionsHead [private]
Definition at line 92 of file ServerMediaSession.hh.
ServerMediaSubsession* ServerMediaSession::fSubsessionsTail [private]
Definition at line 93 of file ServerMediaSession.hh.
The documentation for this class was generated from the following file:
liveMedia/include/ServerMediaSession.hh