OggFile Class Reference
#include <OggFile.hh>
Public Types
typedef void(onCreationFunc) (OggFile *newFile, void *clientData)
Public Member Functions
OggTrack * lookup (u_int32_t trackNumber)
OggDemux * newDemux ()
char const * fileName () const
unsigned numTracks () const
FramedSource * createSourceForStreaming (FramedSource *baseSource, u_int32_t trackNumber, unsigned &estBitrate, unsigned &numFiltersInFrontOfTrack)
RTPSink * createRTPSinkForTrackNumber (u_int32_t trackNumber, Groupsock *rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic)
class OggTrackTable & trackTable ()
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static void createNew (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TaskToken & nextTask ()
Private Member Functions
OggFile (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData)
virtual ~OggFile ()
void handleEndOfBosPageParsing ()
void addTrack (OggTrack *newTrack)
void removeDemux (OggDemux *demux)
Static Private Member Functions
static void handleEndOfBosPageParsing (void *clientData)
Private Attributes
char const * fFileName
onCreationFunc * fOnCreation
void * fOnCreationClientData
class OggTrackTable * fTrackTable
HashTable * fDemuxesTable
class OggFileParser * fParserForInitialization
Friends
class OggFileParser
class OggDemux
Detailed Description
Definition at line 34 of file OggFile.hh.
Member Typedef Documentation
typedef void(OggFile::onCreationFunc) (OggFile *newFile, void *clientData)
Definition at line 36 of file OggFile.hh.
Constructor & Destructor Documentation
OggFile::OggFile (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData) [private]
virtual OggFile::~OggFile () [private], [virtual]
Member Function Documentation
void OggFile::addTrack (OggTrack * newTrack) [private]
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static void OggFile::createNew (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData) [static]
RTPSink* OggFile::createRTPSinkForTrackNumber (u_int32_t trackNumber, Groupsock * rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic)
FramedSource* OggFile::createSourceForStreaming (FramedSource * baseSource, u_int32_t trackNumber, unsigned & estBitrate, unsigned & numFiltersInFrontOfTrack)
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
char const* OggFile::fileName () const [inline]
Definition at line 51 of file OggFile.hh.
References fFileName.
{ return fFileName; }
static void OggFile::handleEndOfBosPageParsing (void * clientData) [static], [private]
void OggFile::handleEndOfBosPageParsing () [private]
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
OggTrack* OggFile::lookup (u_int32_t trackNumber)
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
OggDemux* OggFile::newDemux ()
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
unsigned OggFile::numTracks () const
void OggFile::removeDemux (OggDemux * demux) [private]
class OggTrackTable& OggFile::trackTable () [inline]
Definition at line 65 of file OggFile.hh.
References fTrackTable.
{ return *fTrackTable; }
Friends And Related Function Documentation
friend class OggDemux [friend]
Definition at line 80 of file OggFile.hh.
friend class OggFileParser [friend]
Definition at line 79 of file OggFile.hh.
Field Documentation
HashTable* OggFile::fDemuxesTable [private]
Definition at line 86 of file OggFile.hh.
char const* OggFile::fFileName [private]
Definition at line 81 of file OggFile.hh.
Referenced by fileName().
onCreationFunc* OggFile::fOnCreation [private]
Definition at line 82 of file OggFile.hh.
void* OggFile::fOnCreationClientData [private]
Definition at line 83 of file OggFile.hh.
class OggFileParser* OggFile::fParserForInitialization [private]
Definition at line 87 of file OggFile.hh.
class OggTrackTable* OggFile::fTrackTable [private]
Definition at line 85 of file OggFile.hh.
Referenced by trackTable().
The documentation for this class was generated from the following file:
liveMedia/include/OggFile.hh