GroupEId Class Reference
#include <GroupEId.hh>
Public Member Functions
GroupEId (struct in_addr const &groupAddr, portNumBits portNum, u_int8_t ttl)
GroupEId (struct in_addr const &groupAddr, struct in_addr const &sourceFilterAddr, portNumBits portNum)
struct in_addr const & groupAddress () const
struct in_addr const & sourceFilterAddress () const
Boolean isSSM () const
portNumBits portNum () const
u_int8_t ttl () const
Private Member Functions
void init (struct in_addr const &groupAddr, struct in_addr const &sourceFilterAddr, portNumBits portNum, u_int8_t ttl)
Private Attributes
struct in_addr fGroupAddress
struct in_addr fSourceFilterAddress
portNumBits fPortNum
u_int8_t fTTL
Detailed Description
Definition at line 32 of file GroupEId.hh.
Constructor & Destructor Documentation
GroupEId::GroupEId (struct in_addr const & groupAddr, portNumBits portNum, u_int8_t ttl)
GroupEId::GroupEId (struct in_addr const & groupAddr, struct in_addr const & sourceFilterAddr, portNumBits portNum)
Member Function Documentation
struct in_addr const& GroupEId::groupAddress () const [inline]
Definition at line 42 of file GroupEId.hh.
References fGroupAddress.
Referenced by Groupsock::groupAddress().
{ return fGroupAddress; }
void GroupEId::init (struct in_addr const & groupAddr, struct in_addr const & sourceFilterAddr, portNumBits portNum, u_int8_t ttl) [private]
Boolean GroupEId::isSSM () const
Referenced by Groupsock::isSSM().
portNumBits GroupEId::portNum () const [inline]
Definition at line 47 of file GroupEId.hh.
References fPortNum.
{ return fPortNum; }
struct in_addr const& GroupEId::sourceFilterAddress () const [inline]
Definition at line 43 of file GroupEId.hh.
References fSourceFilterAddress.
Referenced by Groupsock::sourceFilterAddress().
{ return fSourceFilterAddress; }
u_int8_t GroupEId::ttl () const [inline]
Definition at line 49 of file GroupEId.hh.
References fTTL.
Referenced by Groupsock::ttl().
{ return fTTL; }
Field Documentation
struct in_addr GroupEId::fGroupAddress [private]
Definition at line 58 of file GroupEId.hh.
Referenced by groupAddress().
portNumBits GroupEId::fPortNum [private]
Definition at line 60 of file GroupEId.hh.
Referenced by portNum().
struct in_addr GroupEId::fSourceFilterAddress [private]
Definition at line 59 of file GroupEId.hh.
Referenced by sourceFilterAddress().
u_int8_t GroupEId::fTTL [private]
Definition at line 61 of file GroupEId.hh.
Referenced by ttl().
The documentation for this class was generated from the following file:
groupsock/include/GroupEId.hh