MPEG1or2FileServerDemux Class Reference
#include <MPEG1or2FileServerDemux.hh>
Public Member Functions
ServerMediaSubsession * newAudioServerMediaSubsession ()
ServerMediaSubsession * newVideoServerMediaSubsession (Boolean iFramesOnly=False, double vshPeriod=5.0)
ServerMediaSubsession * newAC3AudioServerMediaSubsession ()
unsigned fileSize () const
float fileDuration () const
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static MPEG1or2FileServerDemux * createNew (UsageEnvironment &env, char const *fileName, Boolean reuseFirstSource)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TaskToken & nextTask ()
Private Member Functions
MPEG1or2FileServerDemux (UsageEnvironment &env, char const *fileName, Boolean reuseFirstSource)
virtual ~MPEG1or2FileServerDemux ()
MPEG1or2DemuxedElementaryStream * newElementaryStream (unsigned clientSessionId, u_int8_t streamIdTag)
Private Attributes
char const * fFileName
unsigned fFileSize
float fFileDuration
Boolean fReuseFirstSource
MPEG1or2Demux * fSession0Demux
MPEG1or2Demux * fLastCreatedDemux
unsigned fLastClientSessionId
Friends
class MPEG1or2DemuxedServerMediaSubsession
Detailed Description
Definition at line 31 of file MPEG1or2FileServerDemux.hh.
Constructor & Destructor Documentation
MPEG1or2FileServerDemux::MPEG1or2FileServerDemux (UsageEnvironment & env, char const * fileName, Boolean reuseFirstSource) [private]
virtual MPEG1or2FileServerDemux::~MPEG1or2FileServerDemux () [private], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static MPEG1or2FileServerDemux* MPEG1or2FileServerDemux::createNew (UsageEnvironment & env, char const * fileName, Boolean reuseFirstSource) [static]
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
float MPEG1or2FileServerDemux::fileDuration () const [inline]
Definition at line 44 of file MPEG1or2FileServerDemux.hh.
References fFileDuration.
{ return fFileDuration; }
unsigned MPEG1or2FileServerDemux::fileSize () const [inline]
Definition at line 43 of file MPEG1or2FileServerDemux.hh.
References fFileSize.
{ return fFileSize; }
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
ServerMediaSubsession* MPEG1or2FileServerDemux::newAC3AudioServerMediaSubsession ()
ServerMediaSubsession* MPEG1or2FileServerDemux::newAudioServerMediaSubsession ()
MPEG1or2DemuxedElementaryStream* MPEG1or2FileServerDemux::newElementaryStream (unsigned clientSessionId, u_int8_t streamIdTag) [private]
ServerMediaSubsession* MPEG1or2FileServerDemux::newVideoServerMediaSubsession (Boolean iFramesOnly = False, double vshPeriod = 5.0)
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
Friends And Related Function Documentation
friend class MPEG1or2DemuxedServerMediaSubsession [friend]
Definition at line 53 of file MPEG1or2FileServerDemux.hh.
Field Documentation
float MPEG1or2FileServerDemux::fFileDuration [private]
Definition at line 60 of file MPEG1or2FileServerDemux.hh.
Referenced by fileDuration().
char const* MPEG1or2FileServerDemux::fFileName [private]
Definition at line 58 of file MPEG1or2FileServerDemux.hh.
unsigned MPEG1or2FileServerDemux::fFileSize [private]
Definition at line 59 of file MPEG1or2FileServerDemux.hh.
Referenced by fileSize().
unsigned MPEG1or2FileServerDemux::fLastClientSessionId [private]
Definition at line 64 of file MPEG1or2FileServerDemux.hh.
MPEG1or2Demux* MPEG1or2FileServerDemux::fLastCreatedDemux [private]
Definition at line 63 of file MPEG1or2FileServerDemux.hh.
Boolean MPEG1or2FileServerDemux::fReuseFirstSource [private]
Definition at line 61 of file MPEG1or2FileServerDemux.hh.
MPEG1or2Demux* MPEG1or2FileServerDemux::fSession0Demux [private]
Definition at line 62 of file MPEG1or2FileServerDemux.hh.
The documentation for this class was generated from the following file:
liveMedia/include/MPEG1or2FileServerDemux.hh