HashTable Class Reference
#include <HashTable.hh>
Data Structures
class Iterator
Public Member Functions
virtual ~HashTable ()
virtual void * Add (char const *key, void *value)=0
virtual Boolean Remove (char const *key)=0
virtual void * Lookup (char const *key) const =0
virtual unsigned numEntries () const =0
Boolean IsEmpty () const
void * RemoveNext ()
void * getFirst ()
Static Public Member Functions
static HashTable * create (int keyType)
Protected Member Functions
HashTable ()
Detailed Description
Definition at line 27 of file HashTable.hh.
Constructor & Destructor Documentation
virtual HashTable::~HashTable () [virtual]
HashTable::HashTable () [protected]
Member Function Documentation
virtual void* HashTable::Add (char const * key, void * value) [pure virtual]
Implemented in BasicHashTable .
static HashTable* HashTable::create (int keyType) [static]
void* HashTable::getFirst ()
Boolean HashTable::IsEmpty () const [inline]
Definition at line 41 of file HashTable.hh.
References numEntries().
Referenced by DirectedNetInterfaceSet::IsEmpty().
{ return numEntries() == 0; }
virtual void* HashTable::Lookup (char const * key) const [pure virtual]
Implemented in BasicHashTable .
virtual unsigned HashTable::numEntries () const [pure virtual]
Implemented in BasicHashTable .
Referenced by IsEmpty().
virtual Boolean HashTable::Remove (char const * key) [pure virtual]
Implemented in BasicHashTable .
void* HashTable::RemoveNext ()
Referenced by AddressPortLookupTable::RemoveNext().
The documentation for this class was generated from the following file:
UsageEnvironment/include/HashTable.hh