MatroskaFile Class Reference
#include <MatroskaFile.hh>
Public Types
typedef void(onCreationFunc) (MatroskaFile *newFile, void *clientData)
Public Member Functions
MatroskaTrack * lookup (unsigned trackNumber) const
MatroskaDemux * newDemux ()
unsigned timecodeScale ()
float segmentDuration ()
float fileDuration ()
char const * fileName () const
unsigned chosenVideoTrackNumber ()
unsigned chosenAudioTrackNumber ()
unsigned chosenSubtitleTrackNumber ()
FramedSource * createSourceForStreaming (FramedSource *baseSource, unsigned trackNumber, unsigned &estBitrate, unsigned &numFiltersInFrontOfTrack)
RTPSink * createRTPSinkForTrackNumber (unsigned trackNumber, Groupsock *rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static void createNew (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData, char const *preferredLanguage=`eng`)
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
TaskToken & nextTask ()
Private Member Functions
MatroskaFile (UsageEnvironment &env, char const *fileName, onCreationFunc *onCreation, void *onCreationClientData, char const *preferredLanguage)
virtual ~MatroskaFile ()
void handleEndOfTrackHeaderParsing ()
void addTrack (MatroskaTrack *newTrack, unsigned trackNumber)
void addCuePoint (double cueTime, u_int64_t clusterOffsetInFile, unsigned blockNumWithinCluster)
Boolean lookupCuePoint (double &cueTime, u_int64_t &resultClusterOffsetInFile, unsigned &resultBlockNumWithinCluster)
void printCuePoints (FILE *fid)
void removeDemux (MatroskaDemux *demux)
Static Private Member Functions
static void handleEndOfTrackHeaderParsing (void *clientData)
Private Attributes
char const * fFileName
onCreationFunc * fOnCreation
void * fOnCreationClientData
char const * fPreferredLanguage
unsigned fTimecodeScale
float fSegmentDuration
u_int64_t fSegmentDataOffset
u_int64_t fClusterOffset
u_int64_t fCuesOffset
class MatroskaTrackTable * fTrackTable
HashTable * fDemuxesTable
class CuePoint * fCuePoints
unsigned fChosenVideoTrackNumber
unsigned fChosenAudioTrackNumber
unsigned fChosenSubtitleTrackNumber
class MatroskaFileParser * fParserForInitialization
Friends
class MatroskaFileParser
class MatroskaDemux
Detailed Description
Definition at line 34 of file MatroskaFile.hh.
Member Typedef Documentation
typedef void(MatroskaFile::onCreationFunc) (MatroskaFile *newFile, void *clientData)
Definition at line 36 of file MatroskaFile.hh.
Constructor & Destructor Documentation
MatroskaFile::MatroskaFile (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData, char const * preferredLanguage) [private]
virtual MatroskaFile::~MatroskaFile () [private], [virtual]
Member Function Documentation
void MatroskaFile::addCuePoint (double cueTime, u_int64_t clusterOffsetInFile, unsigned blockNumWithinCluster) [private]
void MatroskaFile::addTrack (MatroskaTrack * newTrack, unsigned trackNumber) [private]
unsigned MatroskaFile::chosenAudioTrackNumber () [inline]
Definition at line 56 of file MatroskaFile.hh.
References fChosenAudioTrackNumber.
{ return fChosenAudioTrackNumber; }
unsigned MatroskaFile::chosenSubtitleTrackNumber () [inline]
Definition at line 57 of file MatroskaFile.hh.
References fChosenSubtitleTrackNumber.
{ return fChosenSubtitleTrackNumber; }
unsigned MatroskaFile::chosenVideoTrackNumber () [inline]
Definition at line 55 of file MatroskaFile.hh.
References fChosenVideoTrackNumber.
{ return fChosenVideoTrackNumber; }
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
static void MatroskaFile::createNew (UsageEnvironment & env, char const * fileName, onCreationFunc * onCreation, void * onCreationClientData, char const * preferredLanguage = `eng`) [static]
RTPSink* MatroskaFile::createRTPSinkForTrackNumber (unsigned trackNumber, Groupsock * rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic)
FramedSource* MatroskaFile::createSourceForStreaming (FramedSource * baseSource, unsigned trackNumber, unsigned & estBitrate, unsigned & numFiltersInFrontOfTrack)
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
float MatroskaFile::fileDuration ()
Referenced by MatroskaFileServerDemux::fileDuration().
char const* MatroskaFile::fileName () const [inline]
Definition at line 53 of file MatroskaFile.hh.
References fFileName.
{ return fFileName; }
static void MatroskaFile::handleEndOfTrackHeaderParsing (void * clientData) [static], [private]
void MatroskaFile::handleEndOfTrackHeaderParsing () [private]
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
MatroskaTrack* MatroskaFile::lookup (unsigned trackNumber) const
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
Boolean MatroskaFile::lookupCuePoint (double & cueTime, u_int64_t & resultClusterOffsetInFile, unsigned & resultBlockNumWithinCluster) [private]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
MatroskaDemux* MatroskaFile::newDemux ()
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
void MatroskaFile::printCuePoints (FILE * fid) [private]
void MatroskaFile::removeDemux (MatroskaDemux * demux) [private]
float MatroskaFile::segmentDuration () [inline]
Definition at line 50 of file MatroskaFile.hh.
References fSegmentDuration.
{ return fSegmentDuration; } // in units of "timecodeScale()"
unsigned MatroskaFile::timecodeScale () [inline]
Definition at line 49 of file MatroskaFile.hh.
References fTimecodeScale.
{ return fTimecodeScale; } // in nanoseconds
Friends And Related Function Documentation
friend class MatroskaDemux [friend]
Definition at line 88 of file MatroskaFile.hh.
friend class MatroskaFileParser [friend]
Definition at line 87 of file MatroskaFile.hh.
Field Documentation
unsigned MatroskaFile::fChosenAudioTrackNumber [private]
Definition at line 101 of file MatroskaFile.hh.
Referenced by chosenAudioTrackNumber().
unsigned MatroskaFile::fChosenSubtitleTrackNumber [private]
Definition at line 101 of file MatroskaFile.hh.
Referenced by chosenSubtitleTrackNumber().
unsigned MatroskaFile::fChosenVideoTrackNumber [private]
Definition at line 101 of file MatroskaFile.hh.
Referenced by chosenVideoTrackNumber().
u_int64_t MatroskaFile::fClusterOffset [private]
Definition at line 96 of file MatroskaFile.hh.
class CuePoint* MatroskaFile::fCuePoints [private]
Definition at line 100 of file MatroskaFile.hh.
u_int64_t MatroskaFile::fCuesOffset [private]
Definition at line 96 of file MatroskaFile.hh.
HashTable* MatroskaFile::fDemuxesTable [private]
Definition at line 99 of file MatroskaFile.hh.
char const* MatroskaFile::fFileName [private]
Definition at line 89 of file MatroskaFile.hh.
Referenced by fileName().
onCreationFunc* MatroskaFile::fOnCreation [private]
Definition at line 90 of file MatroskaFile.hh.
void* MatroskaFile::fOnCreationClientData [private]
Definition at line 91 of file MatroskaFile.hh.
class MatroskaFileParser* MatroskaFile::fParserForInitialization [private]
Definition at line 102 of file MatroskaFile.hh.
char const* MatroskaFile::fPreferredLanguage [private]
Definition at line 92 of file MatroskaFile.hh.
u_int64_t MatroskaFile::fSegmentDataOffset [private]
Definition at line 96 of file MatroskaFile.hh.
float MatroskaFile::fSegmentDuration [private]
Definition at line 95 of file MatroskaFile.hh.
Referenced by segmentDuration().
unsigned MatroskaFile::fTimecodeScale [private]
Definition at line 94 of file MatroskaFile.hh.
Referenced by timecodeScale().
class MatroskaTrackTable* MatroskaFile::fTrackTable [private]
Definition at line 98 of file MatroskaFile.hh.
The documentation for this class was generated from the following file:
liveMedia/include/MatroskaFile.hh