TunnelEncapsulationTrailer Class Reference
#include <TunnelEncaps.hh>
Public Member Functions
Cookie & srcCookie ()
Cookie & dstCookie ()
u_int32_t & address ()
Port & port ()
u_int8_t & ttl ()
u_int8_t & command ()
u_int32_t & auxAddress ()
Private Member Functions
char * byteOffset (int charIndex)
Detailed Description
Definition at line 30 of file TunnelEncaps.hh.
Member Function Documentation
u_int32_t& TunnelEncapsulationTrailer::address () [inline]
Definition at line 48 of file TunnelEncaps.hh.
References byteOffset().
                { return *(u_int32_t*)byteOffset(4); }
u_int32_t& TunnelEncapsulationTrailer::auxAddress () [inline]
Definition at line 57 of file TunnelEncaps.hh.
References byteOffset().
                { return *(u_int32_t*)byteOffset(-4); }
char* TunnelEncapsulationTrailer::byteOffset (int charIndex) [inline], [private]
Definition at line 61 of file TunnelEncaps.hh.
Referenced by address(), auxAddress(), command(), dstCookie(), port(), srcCookie(), and ttl().
                { return ((char*)this) + charIndex; }
u_int8_t& TunnelEncapsulationTrailer::command () [inline]
Definition at line 54 of file TunnelEncaps.hh.
References byteOffset().
                { return *(u_int8_t*)byteOffset(11); }
Cookie& TunnelEncapsulationTrailer::dstCookie () [inline]
Definition at line 46 of file TunnelEncaps.hh.
References byteOffset().
                { return *(Cookie*)byteOffset(2); }
Port& TunnelEncapsulationTrailer::port () [inline]
Definition at line 50 of file TunnelEncaps.hh.
References byteOffset().
                { return *(Port*)byteOffset(8); }
Cookie& TunnelEncapsulationTrailer::srcCookie () [inline]
Definition at line 44 of file TunnelEncaps.hh.
References byteOffset().
                { return *(Cookie*)byteOffset(0); }
u_int8_t& TunnelEncapsulationTrailer::ttl () [inline]
Definition at line 52 of file TunnelEncaps.hh.
References byteOffset().
                { return *(u_int8_t*)byteOffset(10); }
The documentation for this class was generated from the following file:
groupsock/include/TunnelEncaps.hh