ServerMediaSubsession Class Reference
#include <ServerMediaSession.hh>
Public Member Functions
unsigned trackNumber () const
char const * trackId ()
virtual char const * sdpLines ()=0
virtual void getStreamParameters (unsigned clientSessionId, netAddressBits clientAddress, Port const &clientRTPPort, Port const &clientRTCPPort, int tcpSocketNum, unsigned char rtpChannelId, unsigned char rtcpChannelId, netAddressBits &destinationAddress, u_int8_t &destinationTTL, Boolean &isMulticast, Port &serverRTPPort, Port &serverRTCPPort, void *&streamToken)=0
virtual void startStream (unsigned clientSessionId, void *streamToken, TaskFunc *rtcpRRHandler, void *rtcpRRHandlerClientData, unsigned short &rtpSeqNum, unsigned &rtpTimestamp, ServerRequestAlternativeByteHandler *serverRequestAlternativeByteHandler, void *serverRequestAlternativeByteHandlerClientData)=0
virtual void pauseStream (unsigned clientSessionId, void *streamToken)
virtual void seekStream (unsigned clientSessionId, void *streamToken, double &seekNPT, double streamDuration, u_int64_t &numBytes)
virtual void seekStream (unsigned clientSessionId, void *streamToken, char *&absStart, char *&absEnd)
virtual void nullSeekStream (unsigned clientSessionId, void *streamToken, double streamEndTime, u_int64_t &numBytes)
virtual void setStreamScale (unsigned clientSessionId, void *streamToken, float scale)
virtual float getCurrentNPT (void *streamToken)
virtual FramedSource * getStreamSource (void *streamToken)
virtual void getRTPSinkandRTCP (void *streamToken, RTPSink const *&rtpSink, RTCPInstance const *&rtcp)=0
virtual void deleteStream (unsigned clientSessionId, void *&streamToken)
virtual void testScaleFactor (float &scale)
virtual float duration () const
virtual void getAbsoluteTimeRange (char *&absStartTime, char *&absEndTime) const
void setServerAddressAndPortForSDP (netAddressBits addressBits, portNumBits portBits)
UsageEnvironment & envir () const
char const * name () const
virtual Boolean isSource () const
virtual Boolean isSink () const
virtual Boolean isRTCPInstance () const
virtual Boolean isRTSPClient () const
virtual Boolean isRTSPServer () const
virtual Boolean isMediaSession () const
virtual Boolean isServerMediaSession () const
Static Public Member Functions
static Boolean lookupByName (UsageEnvironment &env, char const *mediumName, Medium *&resultMedium)
static void close (UsageEnvironment &env, char const *mediumName)
static void close (Medium *medium)
Protected Member Functions
ServerMediaSubsession (UsageEnvironment &env)
virtual ~ServerMediaSubsession ()
char const * rangeSDPLine () const
TaskToken & nextTask ()
Protected Attributes
ServerMediaSession * fParentSession
netAddressBits fServerAddressForSDP
portNumBits fPortNumForSDP
Private Attributes
ServerMediaSubsession * fNext
unsigned fTrackNumber
char const * fTrackId
Friends
class ServerMediaSession
class ServerMediaSubsessionIterator
Detailed Description
Definition at line 120 of file ServerMediaSession.hh.
Constructor & Destructor Documentation
ServerMediaSubsession::ServerMediaSubsession (UsageEnvironment & env) [protected]
virtual ServerMediaSubsession::~ServerMediaSubsession () [protected], [virtual]
Member Function Documentation
static void Medium::close (UsageEnvironment & env, char const * mediumName) [static], [inherited]
static void Medium::close (Medium * medium) [static], [inherited]
virtual void ServerMediaSubsession::deleteStream (unsigned clientSessionId, void *& streamToken) [virtual]
Reimplemented in OnDemandServerMediaSubsession , MPEG2TransportFileServerMediaSubsession , and PassiveServerMediaSubsession .
virtual float ServerMediaSubsession::duration () const [virtual]
Reimplemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , MPEG1or2DemuxedServerMediaSubsession , WAVAudioFileServerMediaSubsession , DVVideoFileServerMediaSubsession , and MatroskaFileServerMediaSubsession .
UsageEnvironment& Medium::envir () const [inline], [inherited]
Definition at line 59 of file Media.hh.
References Medium::fEnviron.
Referenced by MediaSubsession::env(), RTPInterface::envir(), GenericMediaServer::ClientConnection::envir(), and GenericMediaServer::ClientSession::envir().
{return fEnviron;}
virtual void ServerMediaSubsession::getAbsoluteTimeRange (char *& absStartTime, char *& absEndTime) const [virtual]
virtual float ServerMediaSubsession::getCurrentNPT (void * streamToken) [virtual]
Reimplemented in OnDemandServerMediaSubsession , and PassiveServerMediaSubsession .
virtual void ServerMediaSubsession::getRTPSinkandRTCP (void * streamToken, RTPSink const *& rtpSink, RTCPInstance const *& rtcp) [pure virtual]
Implemented in OnDemandServerMediaSubsession , and PassiveServerMediaSubsession .
virtual void ServerMediaSubsession::getStreamParameters (unsigned clientSessionId, netAddressBits clientAddress, Port const & clientRTPPort, Port const & clientRTCPPort, int tcpSocketNum, unsigned char rtpChannelId, unsigned char rtcpChannelId, netAddressBits & destinationAddress, u_int8_t & destinationTTL, Boolean & isMulticast, Port & serverRTPPort, Port & serverRTCPPort, void *& streamToken) [pure virtual]
Implemented in PassiveServerMediaSubsession , and OnDemandServerMediaSubsession .
virtual FramedSource* ServerMediaSubsession::getStreamSource (void * streamToken) [virtual]
Reimplemented in OnDemandServerMediaSubsession .
virtual Boolean Medium::isMediaSession () const [virtual], [inherited]
Reimplemented in MediaSession .
virtual Boolean Medium::isRTCPInstance () const [virtual], [inherited]
Reimplemented in RTCPInstance .
virtual Boolean Medium::isRTSPClient () const [virtual], [inherited]
Reimplemented in RTSPClient .
virtual Boolean Medium::isRTSPServer () const [virtual], [inherited]
Reimplemented in RTSPServer .
virtual Boolean Medium::isServerMediaSession () const [virtual], [inherited]
Reimplemented in ServerMediaSession .
virtual Boolean Medium::isSink () const [virtual], [inherited]
Reimplemented in MediaSink .
virtual Boolean Medium::isSource () const [virtual], [inherited]
Reimplemented in MediaSource .
static Boolean Medium::lookupByName (UsageEnvironment & env, char const * mediumName, Medium *& resultMedium) [static], [inherited]
char const* Medium::name () const [inline], [inherited]
Definition at line 61 of file Media.hh.
References Medium::fMediumName.
{return fMediumName;}
TaskToken& Medium::nextTask () [inline], [protected], [inherited]
Definition at line 77 of file Media.hh.
References Medium::fNextTask.
                        {
        return fNextTask;
  }
virtual void ServerMediaSubsession::nullSeekStream (unsigned clientSessionId, void * streamToken, double streamEndTime, u_int64_t & numBytes) [virtual]
Reimplemented in OnDemandServerMediaSubsession .
virtual void ServerMediaSubsession::pauseStream (unsigned clientSessionId, void * streamToken) [virtual]
Reimplemented in MPEG2TransportFileServerMediaSubsession , and OnDemandServerMediaSubsession .
char const* ServerMediaSubsession::rangeSDPLine () const [protected]
virtual char const* ServerMediaSubsession::sdpLines () [pure virtual]
Implemented in PassiveServerMediaSubsession , and OnDemandServerMediaSubsession .
virtual void ServerMediaSubsession::seekStream (unsigned clientSessionId, void * streamToken, double & seekNPT, double streamDuration, u_int64_t & numBytes) [virtual]
Reimplemented in MPEG2TransportFileServerMediaSubsession , and OnDemandServerMediaSubsession .
virtual void ServerMediaSubsession::seekStream (unsigned clientSessionId, void * streamToken, char *& absStart, char *& absEnd) [virtual]
Reimplemented in OnDemandServerMediaSubsession .
void ServerMediaSubsession::setServerAddressAndPortForSDP (netAddressBits addressBits, portNumBits portBits)
virtual void ServerMediaSubsession::setStreamScale (unsigned clientSessionId, void * streamToken, float scale) [virtual]
Reimplemented in MPEG2TransportFileServerMediaSubsession , and OnDemandServerMediaSubsession .
virtual void ServerMediaSubsession::startStream (unsigned clientSessionId, void * streamToken, TaskFunc * rtcpRRHandler, void * rtcpRRHandlerClientData, unsigned short & rtpSeqNum, unsigned & rtpTimestamp, ServerRequestAlternativeByteHandler * serverRequestAlternativeByteHandler, void * serverRequestAlternativeByteHandlerClientData) [pure virtual]
Implemented in MPEG2TransportFileServerMediaSubsession , PassiveServerMediaSubsession , and OnDemandServerMediaSubsession .
virtual void ServerMediaSubsession::testScaleFactor (float & scale) [virtual]
Reimplemented in MPEG2TransportFileServerMediaSubsession , MP3AudioFileServerMediaSubsession , and WAVAudioFileServerMediaSubsession .
char const* ServerMediaSubsession::trackId ()
unsigned ServerMediaSubsession::trackNumber () const [inline]
Definition at line 122 of file ServerMediaSession.hh.
References fTrackNumber.
{ return fTrackNumber; }
Friends And Related Function Documentation
friend class ServerMediaSession [friend]
Definition at line 195 of file ServerMediaSession.hh.
friend class ServerMediaSubsessionIterator [friend]
Definition at line 196 of file ServerMediaSession.hh.
Field Documentation
ServerMediaSubsession* ServerMediaSubsession::fNext [private]
Definition at line 197 of file ServerMediaSession.hh.
ServerMediaSession* ServerMediaSubsession::fParentSession [protected]
Definition at line 190 of file ServerMediaSession.hh.
portNumBits ServerMediaSubsession::fPortNumForSDP [protected]
Definition at line 192 of file ServerMediaSession.hh.
netAddressBits ServerMediaSubsession::fServerAddressForSDP [protected]
Definition at line 191 of file ServerMediaSession.hh.
char const* ServerMediaSubsession::fTrackId [private]
Definition at line 200 of file ServerMediaSession.hh.
unsigned ServerMediaSubsession::fTrackNumber [private]
Definition at line 199 of file ServerMediaSession.hh.
Referenced by trackNumber().
The documentation for this class was generated from the following file:
liveMedia/include/ServerMediaSession.hh